/********************************************************************************
** Form generated from reading UI file 'mv2_epicsDisplay_v2.ui'
**
** Created by: Qt User Interface Compiler version 5.5.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MV2_EPICSDISPLAY_V2_H
#define UI_MV2_EPICSDISPLAY_V2_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>
#include "QEAnalogIndicator.h"
#include "QEAnalogProgressBar.h"
#include "QELabel.h"
#include "QELineEdit.h"
#include "QEPushButton.h"
#include "QESimpleShape.h"
#include "QSimpleShape.h"

QT_BEGIN_NAMESPACE

class Ui_mainWindow
{
public:
    QWidget *centralwidget;
    QGroupBox *charts;
    QEPushButton *barscan;
    QEPushButton *barstrip;
    QEPushButton *anascan;
    QEPushButton *summary1;
    QLabel *name1;
    QLabel *name2;
    QLabel *name3;
    QLabel *name4;
    QLabel *name5;
    QEPushButton *summary1_2;
    QEPushButton *summary1_3;
    QEPushButton *summary1_4;
    QEPushButton *summary1_5;
    QEPushButton *barstrip_2;
    QEPushButton *barstrip_3;
    QEPushButton *barstrip_4;
    QEPushButton *barstrip_5;
    QLabel *name6;
    QEPushButton *barstrip6;
    QEPushButton *summary6;
    QGroupBox *scan;
    QGroupBox *Mode;
    QLabel *label_3;
    QLabel *label_6;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_8;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_12;
    QFrame *line;
    QLabel *label_13;
    QLabel *label_18;
    QLabel *label_19;
    QLabel *label_20;
    QLabel *label_21;
    QGroupBox *box1;
    QESimpleShape *ANA200;
    QESimpleShape *SS;
    QESimpleShape *BAR50;
    QESimpleShape *BAR100;
    QESimpleShape *BAR200;
    QESimpleShape *STOP;
    QFrame *line_2;
    QESimpleShape *archOn_2;
    QELabel *qelabel;
    QELabel *archTO_2;
    QELabel *archTime_2;
    QGroupBox *box2;
    QESimpleShape *ANA200_2;
    QESimpleShape *SS_2;
    QESimpleShape *BAR50_2;
    QESimpleShape *BAR100_2;
    QESimpleShape *BAR200_2;
    QESimpleShape *STOP_2;
    QFrame *line_3;
    QESimpleShape *archOn_3;
    QELabel *qelabel_2;
    QELabel *archTO_3;
    QELabel *archTime_3;
    QGroupBox *box3;
    QESimpleShape *ANA200_3;
    QESimpleShape *SS_3;
    QESimpleShape *BAR50_3;
    QESimpleShape *BAR100_3;
    QESimpleShape *BAR200_3;
    QESimpleShape *STOP_3;
    QFrame *line_4;
    QESimpleShape *archOn_4;
    QELabel *qelabel_3;
    QELabel *archTO_4;
    QELabel *archTime_4;
    QGroupBox *box4;
    QESimpleShape *ANA200_4;
    QESimpleShape *SS_4;
    QESimpleShape *BAR50_4;
    QESimpleShape *BAR100_4;
    QESimpleShape *BAR200_4;
    QESimpleShape *STOP_4;
    QFrame *line_5;
    QESimpleShape *archOn_5;
    QELabel *qelabel_4;
    QELabel *archTO_5;
    QELabel *archTime_5;
    QGroupBox *box5;
    QESimpleShape *ANA200_5;
    QESimpleShape *SS_5;
    QESimpleShape *BAR50_5;
    QESimpleShape *BAR100_5;
    QESimpleShape *BAR200_5;
    QESimpleShape *STOP_5;
    QFrame *line_6;
    QESimpleShape *archOn_6;
    QELabel *qelabel_5;
    QELabel *archTO_6;
    QELabel *archTime_6;
    QGroupBox *box6;
    QESimpleShape *ANA200_6;
    QESimpleShape *SS_6;
    QESimpleShape *BAR50_6;
    QESimpleShape *BAR100_6;
    QESimpleShape *BAR200_6;
    QESimpleShape *STOP_6;
    QFrame *line_7;
    QESimpleShape *archOn_7;
    QELabel *qelabel_6;
    QELabel *archTO_7;
    QELabel *archTime_7;
    QGroupBox *scan_2;
    QEPushButton *archStop2;
    QLabel *label_7;
    QELineEdit *archDT;
    QEPushButton *archStart;
    QGroupBox *percentBox;
    QEAnalogProgressBar *per1;
    QEAnalogProgressBar *per2;
    QEAnalogProgressBar *per3;
    QEAnalogProgressBar *per4;
    QEAnalogProgressBar *per5;
    QEAnalogProgressBar *per6;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *mainWindow)
    {
        if (mainWindow->objectName().isEmpty())
            mainWindow->setObjectName(QStringLiteral("mainWindow"));
        mainWindow->resize(718, 669);
        centralwidget = new QWidget(mainWindow);
        centralwidget->setObjectName(QStringLiteral("centralwidget"));
        charts = new QGroupBox(centralwidget);
        charts->setObjectName(QStringLiteral("charts"));
        charts->setGeometry(QRect(10, 10, 401, 171));
        barscan = new QEPushButton(charts);
        barscan->setObjectName(QStringLiteral("barscan"));
        barscan->setGeometry(QRect(270, 30, 121, 20));
        barscan->setCheckable(false);
        barstrip = new QEPushButton(charts);
        barstrip->setObjectName(QStringLiteral("barstrip"));
        barstrip->setGeometry(QRect(190, 30, 61, 20));
        barstrip->setCheckable(false);
        anascan = new QEPushButton(charts);
        anascan->setObjectName(QStringLiteral("anascan"));
        anascan->setGeometry(QRect(270, 50, 121, 21));
        anascan->setCheckable(false);
        summary1 = new QEPushButton(charts);
        summary1->setObjectName(QStringLiteral("summary1"));
        summary1->setGeometry(QRect(120, 30, 61, 20));
        summary1->setCheckable(false);
        name1 = new QLabel(charts);
        name1->setObjectName(QStringLiteral("name1"));
        name1->setGeometry(QRect(20, 30, 91, 21));
        name2 = new QLabel(charts);
        name2->setObjectName(QStringLiteral("name2"));
        name2->setGeometry(QRect(20, 50, 91, 21));
        name3 = new QLabel(charts);
        name3->setObjectName(QStringLiteral("name3"));
        name3->setGeometry(QRect(20, 70, 91, 21));
        name4 = new QLabel(charts);
        name4->setObjectName(QStringLiteral("name4"));
        name4->setGeometry(QRect(20, 90, 91, 21));
        name5 = new QLabel(charts);
        name5->setObjectName(QStringLiteral("name5"));
        name5->setGeometry(QRect(20, 110, 91, 21));
        summary1_2 = new QEPushButton(charts);
        summary1_2->setObjectName(QStringLiteral("summary1_2"));
        summary1_2->setGeometry(QRect(120, 50, 61, 20));
        summary1_2->setCheckable(false);
        summary1_3 = new QEPushButton(charts);
        summary1_3->setObjectName(QStringLiteral("summary1_3"));
        summary1_3->setGeometry(QRect(120, 70, 61, 20));
        summary1_3->setCheckable(false);
        summary1_4 = new QEPushButton(charts);
        summary1_4->setObjectName(QStringLiteral("summary1_4"));
        summary1_4->setGeometry(QRect(120, 90, 61, 20));
        summary1_4->setCheckable(false);
        summary1_5 = new QEPushButton(charts);
        summary1_5->setObjectName(QStringLiteral("summary1_5"));
        summary1_5->setGeometry(QRect(120, 110, 61, 20));
        summary1_5->setCheckable(false);
        barstrip_2 = new QEPushButton(charts);
        barstrip_2->setObjectName(QStringLiteral("barstrip_2"));
        barstrip_2->setGeometry(QRect(190, 50, 61, 20));
        barstrip_2->setCheckable(false);
        barstrip_3 = new QEPushButton(charts);
        barstrip_3->setObjectName(QStringLiteral("barstrip_3"));
        barstrip_3->setGeometry(QRect(190, 70, 61, 20));
        barstrip_3->setCheckable(false);
        barstrip_4 = new QEPushButton(charts);
        barstrip_4->setObjectName(QStringLiteral("barstrip_4"));
        barstrip_4->setGeometry(QRect(190, 90, 61, 20));
        barstrip_4->setCheckable(false);
        barstrip_5 = new QEPushButton(charts);
        barstrip_5->setObjectName(QStringLiteral("barstrip_5"));
        barstrip_5->setGeometry(QRect(190, 110, 61, 20));
        barstrip_5->setCheckable(false);
        name6 = new QLabel(charts);
        name6->setObjectName(QStringLiteral("name6"));
        name6->setGeometry(QRect(20, 130, 91, 21));
        barstrip6 = new QEPushButton(charts);
        barstrip6->setObjectName(QStringLiteral("barstrip6"));
        barstrip6->setGeometry(QRect(190, 130, 61, 20));
        barstrip6->setCheckable(false);
        summary6 = new QEPushButton(charts);
        summary6->setObjectName(QStringLiteral("summary6"));
        summary6->setGeometry(QRect(120, 130, 61, 20));
        summary6->setCheckable(false);
        scan = new QGroupBox(centralwidget);
        scan->setObjectName(QStringLiteral("scan"));
        scan->setGeometry(QRect(10, 220, 701, 401));
        Mode = new QGroupBox(scan);
        Mode->setObjectName(QStringLiteral("Mode"));
        Mode->setGeometry(QRect(10, 20, 81, 371));
        label_3 = new QLabel(Mode);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(10, 40, 47, 13));
        label_6 = new QLabel(Mode);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(10, 120, 61, 16));
        label_4 = new QLabel(Mode);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(10, 60, 47, 13));
        label_5 = new QLabel(Mode);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(10, 80, 47, 13));
        label_8 = new QLabel(Mode);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(10, 100, 47, 13));
        label_10 = new QLabel(Mode);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(10, 140, 47, 13));
        label_11 = new QLabel(Mode);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(10, 170, 61, 16));
        label_12 = new QLabel(Mode);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(10, 20, 47, 13));
        line = new QFrame(Mode);
        line->setObjectName(QStringLiteral("line"));
        line->setGeometry(QRect(0, 200, 71, 16));
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        label_13 = new QLabel(Mode);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(10, 220, 61, 16));
        label_18 = new QLabel(Mode);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(10, 250, 41, 16));
        label_19 = new QLabel(Mode);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(10, 290, 51, 20));
        label_20 = new QLabel(Mode);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(10, 320, 51, 20));
        label_21 = new QLabel(Mode);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(10, 340, 51, 20));
        label_3->raise();
        label_6->raise();
        label_4->raise();
        label_5->raise();
        label_8->raise();
        label_10->raise();
        label_11->raise();
        label_12->raise();
        line->raise();
        label_13->raise();
        label_18->raise();
        label_19->raise();
        label_20->raise();
        label_21->raise();
        box1 = new QGroupBox(scan);
        box1->setObjectName(QStringLiteral("box1"));
        box1->setGeometry(QRect(100, 20, 71, 371));
        ANA200 = new QESimpleShape(box1);
        ANA200->setObjectName(QStringLiteral("ANA200"));
        ANA200->setGeometry(QRect(10, 140, 16, 16));
        ANA200->setShape(QSimpleShape::ellipse);
        ANA200->setProperty("colour7", QVariant(QColor(200, 200, 200)));
        ANA200->setProperty("colour8", QVariant(QColor(0, 200, 0)));
        ANA200->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        SS = new QESimpleShape(box1);
        SS->setObjectName(QStringLiteral("SS"));
        SS->setGeometry(QRect(10, 170, 16, 16));
        SS->setShape(QSimpleShape::ellipse);
        SS->setProperty("colour0", QVariant(QColor(0, 200, 0)));
        SS->setProperty("colour1", QVariant(QColor(200, 200, 200)));
        SS->setProperty("flash0", QVariant(false));
        SS->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        BAR50 = new QESimpleShape(box1);
        BAR50->setObjectName(QStringLiteral("BAR50"));
        BAR50->setGeometry(QRect(10, 60, 16, 16));
        BAR50->setShape(QSimpleShape::ellipse);
        BAR50->setProperty("colour3", QVariant(QColor(200, 200, 200)));
        BAR50->setProperty("colour4", QVariant(QColor(200, 200, 200)));
        BAR50->setProperty("colour5", QVariant(QColor(0, 200, 0)));
        BAR50->setProperty("flash0", QVariant(false));
        BAR50->setProperty("flash1", QVariant(false));
        BAR50->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        BAR100 = new QESimpleShape(box1);
        BAR100->setObjectName(QStringLiteral("BAR100"));
        BAR100->setGeometry(QRect(10, 80, 16, 16));
        BAR100->setShape(QSimpleShape::ellipse);
        BAR100->setProperty("colour6", QVariant(QColor(0, 200, 0)));
        BAR100->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        BAR200 = new QESimpleShape(box1);
        BAR200->setObjectName(QStringLiteral("BAR200"));
        BAR200->setGeometry(QRect(10, 100, 16, 16));
        BAR200->setShape(QSimpleShape::ellipse);
        BAR200->setProperty("colour7", QVariant(QColor(0, 200, 0)));
        BAR200->setProperty("visible", QVariant(true));
        BAR200->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        STOP = new QESimpleShape(box1);
        STOP->setObjectName(QStringLiteral("STOP"));
        STOP->setGeometry(QRect(10, 20, 16, 16));
        STOP->setFocusPolicy(Qt::NoFocus);
        STOP->setContextMenuPolicy(Qt::CustomContextMenu);
        STOP->setShape(QSimpleShape::ellipse);
        STOP->setProperty("colour0", QVariant(QColor(255, 255, 0)));
        STOP->setProperty("colour1", QVariant(QColor(255, 0, 0)));
        STOP->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        line_2 = new QFrame(box1);
        line_2->setObjectName(QStringLiteral("line_2"));
        line_2->setGeometry(QRect(10, 200, 21, 16));
        line_2->setFrameShape(QFrame::HLine);
        line_2->setFrameShadow(QFrame::Sunken);
        archOn_2 = new QESimpleShape(box1);
        archOn_2->setObjectName(QStringLiteral("archOn_2"));
        archOn_2->setGeometry(QRect(10, 220, 16, 16));
        archOn_2->setFocusPolicy(Qt::NoFocus);
        archOn_2->setContextMenuPolicy(Qt::CustomContextMenu);
        archOn_2->setShape(QSimpleShape::ellipse);
        archOn_2->setProperty("colour0", QVariant(QColor(200, 200, 200)));
        archOn_2->setProperty("colour1", QVariant(QColor(0, 255, 0)));
        archOn_2->setProperty("colour2", QVariant(QColor(255, 0, 0)));
        archOn_2->setProperty("colour3", QVariant(QColor(0, 255, 0)));
        archOn_2->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        qelabel = new QELabel(box1);
        qelabel->setObjectName(QStringLiteral("qelabel"));
        qelabel->setGeometry(QRect(10, 250, 22, 13));
        archTO_2 = new QELabel(box1);
        archTO_2->setObjectName(QStringLiteral("archTO_2"));
        archTO_2->setGeometry(QRect(10, 290, 31, 21));
        archTime_2 = new QELabel(box1);
        archTime_2->setObjectName(QStringLiteral("archTime_2"));
        archTime_2->setGeometry(QRect(10, 330, 31, 21));
        box2 = new QGroupBox(scan);
        box2->setObjectName(QStringLiteral("box2"));
        box2->setGeometry(QRect(170, 20, 71, 371));
        ANA200_2 = new QESimpleShape(box2);
        ANA200_2->setObjectName(QStringLiteral("ANA200_2"));
        ANA200_2->setGeometry(QRect(10, 140, 16, 16));
        ANA200_2->setShape(QSimpleShape::ellipse);
        ANA200_2->setProperty("colour7", QVariant(QColor(200, 200, 200)));
        ANA200_2->setProperty("colour8", QVariant(QColor(0, 200, 0)));
        ANA200_2->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        SS_2 = new QESimpleShape(box2);
        SS_2->setObjectName(QStringLiteral("SS_2"));
        SS_2->setGeometry(QRect(10, 170, 16, 16));
        SS_2->setShape(QSimpleShape::ellipse);
        SS_2->setProperty("colour0", QVariant(QColor(0, 200, 0)));
        SS_2->setProperty("colour1", QVariant(QColor(200, 200, 200)));
        SS_2->setProperty("flash0", QVariant(false));
        SS_2->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        BAR50_2 = new QESimpleShape(box2);
        BAR50_2->setObjectName(QStringLiteral("BAR50_2"));
        BAR50_2->setGeometry(QRect(10, 60, 16, 16));
        BAR50_2->setShape(QSimpleShape::ellipse);
        BAR50_2->setProperty("colour3", QVariant(QColor(200, 200, 200)));
        BAR50_2->setProperty("colour4", QVariant(QColor(200, 200, 200)));
        BAR50_2->setProperty("colour5", QVariant(QColor(0, 200, 0)));
        BAR50_2->setProperty("flash0", QVariant(false));
        BAR50_2->setProperty("flash1", QVariant(false));
        BAR50_2->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        BAR100_2 = new QESimpleShape(box2);
        BAR100_2->setObjectName(QStringLiteral("BAR100_2"));
        BAR100_2->setGeometry(QRect(10, 80, 16, 16));
        BAR100_2->setShape(QSimpleShape::ellipse);
        BAR100_2->setProperty("colour6", QVariant(QColor(0, 200, 0)));
        BAR100_2->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        BAR200_2 = new QESimpleShape(box2);
        BAR200_2->setObjectName(QStringLiteral("BAR200_2"));
        BAR200_2->setGeometry(QRect(10, 100, 16, 16));
        BAR200_2->setShape(QSimpleShape::ellipse);
        BAR200_2->setProperty("colour7", QVariant(QColor(0, 200, 0)));
        BAR200_2->setProperty("visible", QVariant(true));
        BAR200_2->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        STOP_2 = new QESimpleShape(box2);
        STOP_2->setObjectName(QStringLiteral("STOP_2"));
        STOP_2->setGeometry(QRect(10, 20, 16, 16));
        STOP_2->setFocusPolicy(Qt::NoFocus);
        STOP_2->setContextMenuPolicy(Qt::CustomContextMenu);
        STOP_2->setShape(QSimpleShape::ellipse);
        STOP_2->setProperty("colour0", QVariant(QColor(255, 255, 0)));
        STOP_2->setProperty("colour1", QVariant(QColor(255, 0, 0)));
        STOP_2->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        line_3 = new QFrame(box2);
        line_3->setObjectName(QStringLiteral("line_3"));
        line_3->setGeometry(QRect(10, 200, 21, 16));
        line_3->setFrameShape(QFrame::HLine);
        line_3->setFrameShadow(QFrame::Sunken);
        archOn_3 = new QESimpleShape(box2);
        archOn_3->setObjectName(QStringLiteral("archOn_3"));
        archOn_3->setGeometry(QRect(10, 220, 16, 16));
        archOn_3->setFocusPolicy(Qt::NoFocus);
        archOn_3->setContextMenuPolicy(Qt::CustomContextMenu);
        archOn_3->setShape(QSimpleShape::ellipse);
        archOn_3->setProperty("colour0", QVariant(QColor(200, 200, 200)));
        archOn_3->setProperty("colour1", QVariant(QColor(0, 255, 0)));
        archOn_3->setProperty("colour2", QVariant(QColor(255, 0, 0)));
        archOn_3->setProperty("colour3", QVariant(QColor(0, 255, 0)));
        archOn_3->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        qelabel_2 = new QELabel(box2);
        qelabel_2->setObjectName(QStringLiteral("qelabel_2"));
        qelabel_2->setGeometry(QRect(10, 250, 22, 13));
        archTO_3 = new QELabel(box2);
        archTO_3->setObjectName(QStringLiteral("archTO_3"));
        archTO_3->setGeometry(QRect(10, 290, 31, 21));
        archTime_3 = new QELabel(box2);
        archTime_3->setObjectName(QStringLiteral("archTime_3"));
        archTime_3->setGeometry(QRect(10, 330, 31, 21));
        box3 = new QGroupBox(scan);
        box3->setObjectName(QStringLiteral("box3"));
        box3->setGeometry(QRect(240, 20, 71, 371));
        ANA200_3 = new QESimpleShape(box3);
        ANA200_3->setObjectName(QStringLiteral("ANA200_3"));
        ANA200_3->setGeometry(QRect(10, 140, 16, 16));
        ANA200_3->setShape(QSimpleShape::ellipse);
        ANA200_3->setProperty("colour7", QVariant(QColor(200, 200, 200)));
        ANA200_3->setProperty("colour8", QVariant(QColor(0, 200, 0)));
        ANA200_3->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        SS_3 = new QESimpleShape(box3);
        SS_3->setObjectName(QStringLiteral("SS_3"));
        SS_3->setGeometry(QRect(10, 170, 16, 16));
        SS_3->setShape(QSimpleShape::ellipse);
        SS_3->setProperty("colour0", QVariant(QColor(0, 200, 0)));
        SS_3->setProperty("colour1", QVariant(QColor(200, 200, 200)));
        SS_3->setProperty("flash0", QVariant(false));
        SS_3->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        BAR50_3 = new QESimpleShape(box3);
        BAR50_3->setObjectName(QStringLiteral("BAR50_3"));
        BAR50_3->setGeometry(QRect(10, 60, 16, 16));
        BAR50_3->setShape(QSimpleShape::ellipse);
        BAR50_3->setProperty("colour3", QVariant(QColor(200, 200, 200)));
        BAR50_3->setProperty("colour4", QVariant(QColor(200, 200, 200)));
        BAR50_3->setProperty("colour5", QVariant(QColor(0, 200, 0)));
        BAR50_3->setProperty("flash0", QVariant(false));
        BAR50_3->setProperty("flash1", QVariant(false));
        BAR50_3->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        BAR100_3 = new QESimpleShape(box3);
        BAR100_3->setObjectName(QStringLiteral("BAR100_3"));
        BAR100_3->setGeometry(QRect(10, 80, 16, 16));
        BAR100_3->setShape(QSimpleShape::ellipse);
        BAR100_3->setProperty("colour6", QVariant(QColor(0, 200, 0)));
        BAR100_3->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        BAR200_3 = new QESimpleShape(box3);
        BAR200_3->setObjectName(QStringLiteral("BAR200_3"));
        BAR200_3->setGeometry(QRect(10, 100, 16, 16));
        BAR200_3->setShape(QSimpleShape::ellipse);
        BAR200_3->setProperty("colour7", QVariant(QColor(0, 200, 0)));
        BAR200_3->setProperty("visible", QVariant(true));
        BAR200_3->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        STOP_3 = new QESimpleShape(box3);
        STOP_3->setObjectName(QStringLiteral("STOP_3"));
        STOP_3->setGeometry(QRect(10, 20, 16, 16));
        STOP_3->setFocusPolicy(Qt::NoFocus);
        STOP_3->setContextMenuPolicy(Qt::CustomContextMenu);
        STOP_3->setShape(QSimpleShape::ellipse);
        STOP_3->setProperty("colour0", QVariant(QColor(255, 255, 0)));
        STOP_3->setProperty("colour1", QVariant(QColor(255, 0, 0)));
        STOP_3->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        line_4 = new QFrame(box3);
        line_4->setObjectName(QStringLiteral("line_4"));
        line_4->setGeometry(QRect(10, 200, 21, 16));
        line_4->setFrameShape(QFrame::HLine);
        line_4->setFrameShadow(QFrame::Sunken);
        archOn_4 = new QESimpleShape(box3);
        archOn_4->setObjectName(QStringLiteral("archOn_4"));
        archOn_4->setGeometry(QRect(10, 220, 16, 16));
        archOn_4->setFocusPolicy(Qt::NoFocus);
        archOn_4->setContextMenuPolicy(Qt::CustomContextMenu);
        archOn_4->setShape(QSimpleShape::ellipse);
        archOn_4->setProperty("colour0", QVariant(QColor(200, 200, 200)));
        archOn_4->setProperty("colour1", QVariant(QColor(0, 255, 0)));
        archOn_4->setProperty("colour2", QVariant(QColor(255, 0, 0)));
        archOn_4->setProperty("colour3", QVariant(QColor(0, 255, 0)));
        archOn_4->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        qelabel_3 = new QELabel(box3);
        qelabel_3->setObjectName(QStringLiteral("qelabel_3"));
        qelabel_3->setGeometry(QRect(10, 250, 22, 13));
        archTO_4 = new QELabel(box3);
        archTO_4->setObjectName(QStringLiteral("archTO_4"));
        archTO_4->setGeometry(QRect(10, 290, 31, 21));
        archTime_4 = new QELabel(box3);
        archTime_4->setObjectName(QStringLiteral("archTime_4"));
        archTime_4->setGeometry(QRect(10, 330, 31, 21));
        box4 = new QGroupBox(scan);
        box4->setObjectName(QStringLiteral("box4"));
        box4->setGeometry(QRect(310, 20, 71, 371));
        ANA200_4 = new QESimpleShape(box4);
        ANA200_4->setObjectName(QStringLiteral("ANA200_4"));
        ANA200_4->setGeometry(QRect(10, 140, 16, 16));
        ANA200_4->setShape(QSimpleShape::ellipse);
        ANA200_4->setProperty("colour7", QVariant(QColor(200, 200, 200)));
        ANA200_4->setProperty("colour8", QVariant(QColor(0, 200, 0)));
        ANA200_4->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        SS_4 = new QESimpleShape(box4);
        SS_4->setObjectName(QStringLiteral("SS_4"));
        SS_4->setGeometry(QRect(10, 170, 16, 16));
        SS_4->setShape(QSimpleShape::ellipse);
        SS_4->setProperty("colour0", QVariant(QColor(0, 200, 0)));
        SS_4->setProperty("colour1", QVariant(QColor(200, 200, 200)));
        SS_4->setProperty("flash0", QVariant(false));
        SS_4->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        BAR50_4 = new QESimpleShape(box4);
        BAR50_4->setObjectName(QStringLiteral("BAR50_4"));
        BAR50_4->setGeometry(QRect(10, 60, 16, 16));
        BAR50_4->setShape(QSimpleShape::ellipse);
        BAR50_4->setProperty("colour3", QVariant(QColor(200, 200, 200)));
        BAR50_4->setProperty("colour4", QVariant(QColor(200, 200, 200)));
        BAR50_4->setProperty("colour5", QVariant(QColor(0, 200, 0)));
        BAR50_4->setProperty("flash0", QVariant(false));
        BAR50_4->setProperty("flash1", QVariant(false));
        BAR50_4->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        BAR100_4 = new QESimpleShape(box4);
        BAR100_4->setObjectName(QStringLiteral("BAR100_4"));
        BAR100_4->setGeometry(QRect(10, 80, 16, 16));
        BAR100_4->setShape(QSimpleShape::ellipse);
        BAR100_4->setProperty("colour6", QVariant(QColor(0, 200, 0)));
        BAR100_4->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        BAR200_4 = new QESimpleShape(box4);
        BAR200_4->setObjectName(QStringLiteral("BAR200_4"));
        BAR200_4->setGeometry(QRect(10, 100, 16, 16));
        BAR200_4->setShape(QSimpleShape::ellipse);
        BAR200_4->setProperty("colour7", QVariant(QColor(0, 200, 0)));
        BAR200_4->setProperty("visible", QVariant(true));
        BAR200_4->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        STOP_4 = new QESimpleShape(box4);
        STOP_4->setObjectName(QStringLiteral("STOP_4"));
        STOP_4->setGeometry(QRect(10, 20, 16, 16));
        STOP_4->setFocusPolicy(Qt::NoFocus);
        STOP_4->setContextMenuPolicy(Qt::CustomContextMenu);
        STOP_4->setShape(QSimpleShape::ellipse);
        STOP_4->setProperty("colour0", QVariant(QColor(255, 255, 0)));
        STOP_4->setProperty("colour1", QVariant(QColor(255, 0, 0)));
        STOP_4->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        line_5 = new QFrame(box4);
        line_5->setObjectName(QStringLiteral("line_5"));
        line_5->setGeometry(QRect(10, 200, 21, 16));
        line_5->setFrameShape(QFrame::HLine);
        line_5->setFrameShadow(QFrame::Sunken);
        archOn_5 = new QESimpleShape(box4);
        archOn_5->setObjectName(QStringLiteral("archOn_5"));
        archOn_5->setGeometry(QRect(10, 220, 16, 16));
        archOn_5->setFocusPolicy(Qt::NoFocus);
        archOn_5->setContextMenuPolicy(Qt::CustomContextMenu);
        archOn_5->setShape(QSimpleShape::ellipse);
        archOn_5->setProperty("colour0", QVariant(QColor(200, 200, 200)));
        archOn_5->setProperty("colour1", QVariant(QColor(0, 255, 0)));
        archOn_5->setProperty("colour2", QVariant(QColor(255, 0, 0)));
        archOn_5->setProperty("colour3", QVariant(QColor(0, 255, 0)));
        archOn_5->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        qelabel_4 = new QELabel(box4);
        qelabel_4->setObjectName(QStringLiteral("qelabel_4"));
        qelabel_4->setGeometry(QRect(10, 250, 22, 13));
        archTO_5 = new QELabel(box4);
        archTO_5->setObjectName(QStringLiteral("archTO_5"));
        archTO_5->setGeometry(QRect(10, 290, 31, 21));
        archTime_5 = new QELabel(box4);
        archTime_5->setObjectName(QStringLiteral("archTime_5"));
        archTime_5->setGeometry(QRect(10, 330, 31, 21));
        box5 = new QGroupBox(scan);
        box5->setObjectName(QStringLiteral("box5"));
        box5->setGeometry(QRect(380, 20, 71, 371));
        ANA200_5 = new QESimpleShape(box5);
        ANA200_5->setObjectName(QStringLiteral("ANA200_5"));
        ANA200_5->setGeometry(QRect(10, 140, 16, 16));
        ANA200_5->setShape(QSimpleShape::ellipse);
        ANA200_5->setProperty("colour7", QVariant(QColor(200, 200, 200)));
        ANA200_5->setProperty("colour8", QVariant(QColor(0, 200, 0)));
        ANA200_5->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        SS_5 = new QESimpleShape(box5);
        SS_5->setObjectName(QStringLiteral("SS_5"));
        SS_5->setGeometry(QRect(10, 170, 16, 16));
        SS_5->setShape(QSimpleShape::ellipse);
        SS_5->setProperty("colour0", QVariant(QColor(0, 200, 0)));
        SS_5->setProperty("colour1", QVariant(QColor(200, 200, 200)));
        SS_5->setProperty("flash0", QVariant(false));
        SS_5->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        BAR50_5 = new QESimpleShape(box5);
        BAR50_5->setObjectName(QStringLiteral("BAR50_5"));
        BAR50_5->setGeometry(QRect(10, 60, 16, 16));
        BAR50_5->setShape(QSimpleShape::ellipse);
        BAR50_5->setProperty("colour3", QVariant(QColor(200, 200, 200)));
        BAR50_5->setProperty("colour4", QVariant(QColor(200, 200, 200)));
        BAR50_5->setProperty("colour5", QVariant(QColor(0, 200, 0)));
        BAR50_5->setProperty("flash0", QVariant(false));
        BAR50_5->setProperty("flash1", QVariant(false));
        BAR50_5->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        BAR100_5 = new QESimpleShape(box5);
        BAR100_5->setObjectName(QStringLiteral("BAR100_5"));
        BAR100_5->setGeometry(QRect(10, 80, 16, 16));
        BAR100_5->setShape(QSimpleShape::ellipse);
        BAR100_5->setProperty("colour6", QVariant(QColor(0, 200, 0)));
        BAR100_5->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        BAR200_5 = new QESimpleShape(box5);
        BAR200_5->setObjectName(QStringLiteral("BAR200_5"));
        BAR200_5->setGeometry(QRect(10, 100, 16, 16));
        BAR200_5->setShape(QSimpleShape::ellipse);
        BAR200_5->setProperty("colour7", QVariant(QColor(0, 200, 0)));
        BAR200_5->setProperty("visible", QVariant(true));
        BAR200_5->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        STOP_5 = new QESimpleShape(box5);
        STOP_5->setObjectName(QStringLiteral("STOP_5"));
        STOP_5->setGeometry(QRect(10, 20, 16, 16));
        STOP_5->setFocusPolicy(Qt::NoFocus);
        STOP_5->setContextMenuPolicy(Qt::CustomContextMenu);
        STOP_5->setShape(QSimpleShape::ellipse);
        STOP_5->setProperty("colour0", QVariant(QColor(255, 255, 0)));
        STOP_5->setProperty("colour1", QVariant(QColor(255, 0, 0)));
        STOP_5->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        line_6 = new QFrame(box5);
        line_6->setObjectName(QStringLiteral("line_6"));
        line_6->setGeometry(QRect(10, 200, 21, 16));
        line_6->setFrameShape(QFrame::HLine);
        line_6->setFrameShadow(QFrame::Sunken);
        archOn_6 = new QESimpleShape(box5);
        archOn_6->setObjectName(QStringLiteral("archOn_6"));
        archOn_6->setGeometry(QRect(10, 220, 16, 16));
        archOn_6->setFocusPolicy(Qt::NoFocus);
        archOn_6->setContextMenuPolicy(Qt::CustomContextMenu);
        archOn_6->setShape(QSimpleShape::ellipse);
        archOn_6->setProperty("colour0", QVariant(QColor(200, 200, 200)));
        archOn_6->setProperty("colour1", QVariant(QColor(0, 255, 0)));
        archOn_6->setProperty("colour2", QVariant(QColor(255, 0, 0)));
        archOn_6->setProperty("colour3", QVariant(QColor(0, 255, 0)));
        archOn_6->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        qelabel_5 = new QELabel(box5);
        qelabel_5->setObjectName(QStringLiteral("qelabel_5"));
        qelabel_5->setGeometry(QRect(10, 250, 22, 13));
        archTO_6 = new QELabel(box5);
        archTO_6->setObjectName(QStringLiteral("archTO_6"));
        archTO_6->setGeometry(QRect(10, 290, 31, 21));
        archTime_6 = new QELabel(box5);
        archTime_6->setObjectName(QStringLiteral("archTime_6"));
        archTime_6->setGeometry(QRect(10, 330, 31, 21));
        box6 = new QGroupBox(scan);
        box6->setObjectName(QStringLiteral("box6"));
        box6->setGeometry(QRect(450, 20, 71, 371));
        ANA200_6 = new QESimpleShape(box6);
        ANA200_6->setObjectName(QStringLiteral("ANA200_6"));
        ANA200_6->setGeometry(QRect(10, 140, 16, 16));
        ANA200_6->setShape(QSimpleShape::ellipse);
        ANA200_6->setProperty("colour7", QVariant(QColor(200, 200, 200)));
        ANA200_6->setProperty("colour8", QVariant(QColor(0, 200, 0)));
        ANA200_6->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        SS_6 = new QESimpleShape(box6);
        SS_6->setObjectName(QStringLiteral("SS_6"));
        SS_6->setGeometry(QRect(10, 170, 16, 16));
        SS_6->setShape(QSimpleShape::ellipse);
        SS_6->setProperty("colour0", QVariant(QColor(0, 200, 0)));
        SS_6->setProperty("colour1", QVariant(QColor(200, 200, 200)));
        SS_6->setProperty("flash0", QVariant(false));
        SS_6->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        BAR50_6 = new QESimpleShape(box6);
        BAR50_6->setObjectName(QStringLiteral("BAR50_6"));
        BAR50_6->setGeometry(QRect(10, 60, 16, 16));
        BAR50_6->setShape(QSimpleShape::ellipse);
        BAR50_6->setProperty("colour3", QVariant(QColor(200, 200, 200)));
        BAR50_6->setProperty("colour4", QVariant(QColor(200, 200, 200)));
        BAR50_6->setProperty("colour5", QVariant(QColor(0, 200, 0)));
        BAR50_6->setProperty("flash0", QVariant(false));
        BAR50_6->setProperty("flash1", QVariant(false));
        BAR50_6->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        BAR100_6 = new QESimpleShape(box6);
        BAR100_6->setObjectName(QStringLiteral("BAR100_6"));
        BAR100_6->setGeometry(QRect(10, 80, 16, 16));
        BAR100_6->setShape(QSimpleShape::ellipse);
        BAR100_6->setProperty("colour6", QVariant(QColor(0, 200, 0)));
        BAR100_6->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        BAR200_6 = new QESimpleShape(box6);
        BAR200_6->setObjectName(QStringLiteral("BAR200_6"));
        BAR200_6->setGeometry(QRect(10, 100, 16, 16));
        BAR200_6->setShape(QSimpleShape::ellipse);
        BAR200_6->setProperty("colour7", QVariant(QColor(0, 200, 0)));
        BAR200_6->setProperty("visible", QVariant(true));
        BAR200_6->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        STOP_6 = new QESimpleShape(box6);
        STOP_6->setObjectName(QStringLiteral("STOP_6"));
        STOP_6->setGeometry(QRect(10, 20, 16, 16));
        STOP_6->setFocusPolicy(Qt::NoFocus);
        STOP_6->setContextMenuPolicy(Qt::CustomContextMenu);
        STOP_6->setShape(QSimpleShape::ellipse);
        STOP_6->setProperty("colour0", QVariant(QColor(255, 255, 0)));
        STOP_6->setProperty("colour1", QVariant(QColor(255, 0, 0)));
        STOP_6->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        line_7 = new QFrame(box6);
        line_7->setObjectName(QStringLiteral("line_7"));
        line_7->setGeometry(QRect(10, 200, 21, 16));
        line_7->setFrameShape(QFrame::HLine);
        line_7->setFrameShadow(QFrame::Sunken);
        archOn_7 = new QESimpleShape(box6);
        archOn_7->setObjectName(QStringLiteral("archOn_7"));
        archOn_7->setGeometry(QRect(10, 220, 16, 16));
        archOn_7->setFocusPolicy(Qt::NoFocus);
        archOn_7->setContextMenuPolicy(Qt::CustomContextMenu);
        archOn_7->setShape(QSimpleShape::ellipse);
        archOn_7->setProperty("colour0", QVariant(QColor(200, 200, 200)));
        archOn_7->setProperty("colour1", QVariant(QColor(0, 255, 0)));
        archOn_7->setProperty("colour2", QVariant(QColor(255, 0, 0)));
        archOn_7->setProperty("colour3", QVariant(QColor(0, 255, 0)));
        archOn_7->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        qelabel_6 = new QELabel(box6);
        qelabel_6->setObjectName(QStringLiteral("qelabel_6"));
        qelabel_6->setGeometry(QRect(10, 250, 22, 13));
        archTO_7 = new QELabel(box6);
        archTO_7->setObjectName(QStringLiteral("archTO_7"));
        archTO_7->setGeometry(QRect(10, 290, 31, 21));
        archTime_7 = new QELabel(box6);
        archTime_7->setObjectName(QStringLiteral("archTime_7"));
        archTime_7->setGeometry(QRect(10, 330, 31, 21));
        scan_2 = new QGroupBox(scan);
        scan_2->setObjectName(QStringLiteral("scan_2"));
        scan_2->setGeometry(QRect(530, 220, 161, 171));
        archStop2 = new QEPushButton(scan_2);
        archStop2->setObjectName(QStringLiteral("archStop2"));
        archStop2->setGeometry(QRect(10, 50, 81, 20));
        label_7 = new QLabel(scan_2);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(10, 70, 81, 16));
        archDT = new QELineEdit(scan_2);
        archDT->setObjectName(QStringLiteral("archDT"));
        archDT->setGeometry(QRect(10, 90, 141, 20));
        archDT->setProperty("format", QVariant(QELineEdit::Default));
        archStart = new QEPushButton(scan_2);
        archStart->setObjectName(QStringLiteral("archStart"));
        archStart->setGeometry(QRect(10, 20, 81, 31));
        percentBox = new QGroupBox(centralwidget);
        percentBox->setObjectName(QStringLiteral("percentBox"));
        percentBox->setGeometry(QRect(540, 230, 161, 211));
        per1 = new QEAnalogProgressBar(percentBox);
        per1->setObjectName(QStringLiteral("per1"));
        per1->setGeometry(QRect(20, 20, 16, 171));
        per1->setOrientation(QEAnalogIndicator::Bottom_To_Top);
        per2 = new QEAnalogProgressBar(percentBox);
        per2->setObjectName(QStringLiteral("per2"));
        per2->setGeometry(QRect(40, 20, 16, 171));
        per2->setOrientation(QEAnalogIndicator::Bottom_To_Top);
        per3 = new QEAnalogProgressBar(percentBox);
        per3->setObjectName(QStringLiteral("per3"));
        per3->setGeometry(QRect(60, 20, 16, 171));
        per3->setOrientation(QEAnalogIndicator::Bottom_To_Top);
        per4 = new QEAnalogProgressBar(percentBox);
        per4->setObjectName(QStringLiteral("per4"));
        per4->setGeometry(QRect(80, 20, 16, 171));
        per4->setOrientation(QEAnalogIndicator::Bottom_To_Top);
        per5 = new QEAnalogProgressBar(percentBox);
        per5->setObjectName(QStringLiteral("per5"));
        per5->setGeometry(QRect(100, 20, 16, 171));
        per5->setOrientation(QEAnalogIndicator::Bottom_To_Top);
        per6 = new QEAnalogProgressBar(percentBox);
        per6->setObjectName(QStringLiteral("per6"));
        per6->setGeometry(QRect(120, 20, 16, 171));
        per6->setOrientation(QEAnalogIndicator::Bottom_To_Top);
        per2->raise();
        per3->raise();
        per4->raise();
        per5->raise();
        per1->raise();
        per6->raise();
        mainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(mainWindow);
        menubar->setObjectName(QStringLiteral("menubar"));
        menubar->setGeometry(QRect(0, 0, 718, 21));
        mainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(mainWindow);
        statusbar->setObjectName(QStringLiteral("statusbar"));
        mainWindow->setStatusBar(statusbar);

        retranslateUi(mainWindow);

        QMetaObject::connectSlotsByName(mainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *mainWindow)
    {
        mainWindow->setWindowTitle(QApplication::translate("mainWindow", "MainWindow", 0));
        charts->setTitle(QApplication::translate("mainWindow", "RGA plots", 0));
        barscan->setText(QApplication::translate("mainWindow", "All RGA Bar Chart", 0));
        barscan->setProperty("variable", QVariant(QString()));
        barscan->setProperty("altReadbackVariable", QVariant(QString()));
        barscan->setPressText(QApplication::translate("mainWindow", "1", 0));
        barscan->setProperty("guiFile", QVariant(QApplication::translate("mainWindow", "barchart.ui", 0)));
        barstrip->setText(QApplication::translate("mainWindow", "Strip chart", 0));
        barstrip->setProperty("variable", QVariant(QString()));
        barstrip->setProperty("altReadbackVariable", QVariant(QString()));
        barstrip->setProperty("variableSubstitutions", QVariant(QString()));
        barstrip->setPressText(QApplication::translate("mainWindow", "1", 0));
        barstrip->setProperty("guiFile", QVariant(QApplication::translate("mainWindow", "mv2_main_bar.ui", 0)));
        anascan->setText(QApplication::translate("mainWindow", "All RGA Analog Scan", 0));
        anascan->setProperty("variable", QVariant(QString()));
        anascan->setProperty("altReadbackVariable", QVariant(QString()));
        anascan->setPressText(QApplication::translate("mainWindow", "1", 0));
        anascan->setProperty("guiFile", QVariant(QApplication::translate("mainWindow", "barchart_ana.ui", 0)));
        summary1->setText(QApplication::translate("mainWindow", "summary", 0));
        summary1->setProperty("variable", QVariant(QString()));
        summary1->setProperty("altReadbackVariable", QVariant(QString()));
        summary1->setProperty("variableSubstitutions", QVariant(QString()));
        summary1->setPressText(QApplication::translate("mainWindow", "1", 0));
        summary1->setProperty("guiFile", QVariant(QApplication::translate("mainWindow", "mv2_main_bar.ui", 0)));
        name1->setText(QApplication::translate("mainWindow", "Name", 0));
        name2->setText(QApplication::translate("mainWindow", "Name", 0));
        name3->setText(QApplication::translate("mainWindow", "Name", 0));
        name4->setText(QApplication::translate("mainWindow", "Name", 0));
        name5->setText(QApplication::translate("mainWindow", "Name", 0));
        summary1_2->setText(QApplication::translate("mainWindow", "summary", 0));
        summary1_2->setProperty("variable", QVariant(QString()));
        summary1_2->setProperty("altReadbackVariable", QVariant(QString()));
        summary1_2->setProperty("variableSubstitutions", QVariant(QString()));
        summary1_2->setPressText(QApplication::translate("mainWindow", "1", 0));
        summary1_2->setProperty("guiFile", QVariant(QApplication::translate("mainWindow", "mv2_main_bar.ui", 0)));
        summary1_3->setText(QApplication::translate("mainWindow", "summary", 0));
        summary1_3->setProperty("variable", QVariant(QString()));
        summary1_3->setProperty("altReadbackVariable", QVariant(QString()));
        summary1_3->setProperty("variableSubstitutions", QVariant(QString()));
        summary1_3->setPressText(QApplication::translate("mainWindow", "1", 0));
        summary1_3->setProperty("guiFile", QVariant(QApplication::translate("mainWindow", "mv2_main_bar.ui", 0)));
        summary1_4->setText(QApplication::translate("mainWindow", "summary", 0));
        summary1_4->setProperty("variable", QVariant(QString()));
        summary1_4->setProperty("altReadbackVariable", QVariant(QString()));
        summary1_4->setProperty("variableSubstitutions", QVariant(QString()));
        summary1_4->setPressText(QApplication::translate("mainWindow", "1", 0));
        summary1_4->setProperty("guiFile", QVariant(QApplication::translate("mainWindow", "mv2_main_bar.ui", 0)));
        summary1_5->setText(QApplication::translate("mainWindow", "summary", 0));
        summary1_5->setProperty("variable", QVariant(QString()));
        summary1_5->setProperty("altReadbackVariable", QVariant(QString()));
        summary1_5->setProperty("variableSubstitutions", QVariant(QString()));
        summary1_5->setPressText(QApplication::translate("mainWindow", "1", 0));
        summary1_5->setProperty("guiFile", QVariant(QApplication::translate("mainWindow", "mv2_main_bar.ui", 0)));
        barstrip_2->setText(QApplication::translate("mainWindow", "Strip chart", 0));
        barstrip_2->setProperty("variable", QVariant(QString()));
        barstrip_2->setProperty("altReadbackVariable", QVariant(QString()));
        barstrip_2->setProperty("variableSubstitutions", QVariant(QString()));
        barstrip_2->setPressText(QApplication::translate("mainWindow", "1", 0));
        barstrip_2->setProperty("guiFile", QVariant(QApplication::translate("mainWindow", "mv2_main_bar.ui", 0)));
        barstrip_3->setText(QApplication::translate("mainWindow", "Strip chart", 0));
        barstrip_3->setProperty("variable", QVariant(QString()));
        barstrip_3->setProperty("altReadbackVariable", QVariant(QString()));
        barstrip_3->setProperty("variableSubstitutions", QVariant(QString()));
        barstrip_3->setPressText(QApplication::translate("mainWindow", "1", 0));
        barstrip_3->setProperty("guiFile", QVariant(QApplication::translate("mainWindow", "mv2_main_bar.ui", 0)));
        barstrip_4->setText(QApplication::translate("mainWindow", "Strip chart", 0));
        barstrip_4->setProperty("variable", QVariant(QString()));
        barstrip_4->setProperty("altReadbackVariable", QVariant(QString()));
        barstrip_4->setProperty("variableSubstitutions", QVariant(QString()));
        barstrip_4->setPressText(QApplication::translate("mainWindow", "1", 0));
        barstrip_4->setProperty("guiFile", QVariant(QApplication::translate("mainWindow", "mv2_main_bar.ui", 0)));
        barstrip_5->setText(QApplication::translate("mainWindow", "Strip chart", 0));
        barstrip_5->setProperty("variable", QVariant(QString()));
        barstrip_5->setProperty("altReadbackVariable", QVariant(QString()));
        barstrip_5->setProperty("variableSubstitutions", QVariant(QString()));
        barstrip_5->setPressText(QApplication::translate("mainWindow", "1", 0));
        barstrip_5->setProperty("guiFile", QVariant(QApplication::translate("mainWindow", "mv2_main_bar.ui", 0)));
        name6->setText(QApplication::translate("mainWindow", "Name", 0));
        barstrip6->setText(QApplication::translate("mainWindow", "Strip chart", 0));
        barstrip6->setProperty("variable", QVariant(QString()));
        barstrip6->setProperty("altReadbackVariable", QVariant(QString()));
        barstrip6->setProperty("variableSubstitutions", QVariant(QString()));
        barstrip6->setPressText(QApplication::translate("mainWindow", "1", 0));
        barstrip6->setProperty("guiFile", QVariant(QApplication::translate("mainWindow", "mv2_main_bar.ui", 0)));
        summary6->setText(QApplication::translate("mainWindow", "summary", 0));
        summary6->setProperty("variable", QVariant(QString()));
        summary6->setProperty("altReadbackVariable", QVariant(QString()));
        summary6->setProperty("variableSubstitutions", QVariant(QString()));
        summary6->setPressText(QApplication::translate("mainWindow", "1", 0));
        summary6->setProperty("guiFile", QVariant(QApplication::translate("mainWindow", "mv2_main_bar.ui", 0)));
        scan->setTitle(QApplication::translate("mainWindow", "Scan", 0));
        Mode->setTitle(QApplication::translate("mainWindow", "Set All:", 0));
        label_3->setText(QApplication::translate("mainWindow", "Bar Chart", 0));
        label_6->setText(QApplication::translate("mainWindow", "Analog Scan", 0));
        label_4->setText(QApplication::translate("mainWindow", "1-50", 0));
        label_5->setText(QApplication::translate("mainWindow", "1-100", 0));
        label_8->setText(QApplication::translate("mainWindow", "1-200", 0));
        label_10->setText(QApplication::translate("mainWindow", "1-200", 0));
        label_11->setText(QApplication::translate("mainWindow", "Single Scan", 0));
        label_12->setText(QApplication::translate("mainWindow", "STOP", 0));
        label_13->setText(QApplication::translate("mainWindow", "Archive On", 0));
        label_18->setText(QApplication::translate("mainWindow", "Mode", 0));
        label_19->setText(QApplication::translate("mainWindow", "Tiimouts", 0));
        label_20->setText(QApplication::translate("mainWindow", "Next ANA", 0));
        label_21->setText(QApplication::translate("mainWindow", "seconds", 0));
        box1->setTitle(QApplication::translate("mainWindow", "RGA", 0));
        ANA200->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):HEADSTA", 0)));
        SS->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):SCAN", 0)));
        BAR50->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):HEADSTA", 0)));
        BAR100->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):HEADSTA", 0)));
        BAR200->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):HEADSTA", 0)));
        STOP->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):HEADSTA", 0)));
        STOP->setProperty("variableSubstitutions", QVariant(QString()));
        archOn_2->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(GRGA):MODE", 0)));
        archOn_2->setProperty("variableSubstitutions", QVariant(QString()));
        archTO_2->setProperty("variable", QVariant(QApplication::translate("mainWindow", "GRGA:ANAT", 0)));
        archTime_2->setProperty("variable", QVariant(QApplication::translate("mainWindow", "GRGA:ANAT", 0)));
        box2->setTitle(QApplication::translate("mainWindow", "RGA", 0));
        ANA200_2->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):HEADSTA", 0)));
        SS_2->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):SCAN", 0)));
        BAR50_2->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):HEADSTA", 0)));
        BAR100_2->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):HEADSTA", 0)));
        BAR200_2->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):HEADSTA", 0)));
        STOP_2->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):HEADSTA", 0)));
        STOP_2->setProperty("variableSubstitutions", QVariant(QString()));
        archOn_3->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(GRGA):MODE", 0)));
        archOn_3->setProperty("variableSubstitutions", QVariant(QString()));
        archTO_3->setProperty("variable", QVariant(QApplication::translate("mainWindow", "GRGA:ANAT", 0)));
        archTime_3->setProperty("variable", QVariant(QApplication::translate("mainWindow", "GRGA:ANAT", 0)));
        box3->setTitle(QApplication::translate("mainWindow", "RGA", 0));
        ANA200_3->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):HEADSTA", 0)));
        SS_3->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):SCAN", 0)));
        BAR50_3->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):HEADSTA", 0)));
        BAR100_3->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):HEADSTA", 0)));
        BAR200_3->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):HEADSTA", 0)));
        STOP_3->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):HEADSTA", 0)));
        STOP_3->setProperty("variableSubstitutions", QVariant(QString()));
        archOn_4->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(GRGA):MODE", 0)));
        archOn_4->setProperty("variableSubstitutions", QVariant(QString()));
        archTO_4->setProperty("variable", QVariant(QApplication::translate("mainWindow", "GRGA:ANAT", 0)));
        archTime_4->setProperty("variable", QVariant(QApplication::translate("mainWindow", "GRGA:ANAT", 0)));
        box4->setTitle(QApplication::translate("mainWindow", "RGA", 0));
        ANA200_4->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):HEADSTA", 0)));
        SS_4->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):SCAN", 0)));
        BAR50_4->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):HEADSTA", 0)));
        BAR100_4->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):HEADSTA", 0)));
        BAR200_4->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):HEADSTA", 0)));
        STOP_4->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):HEADSTA", 0)));
        STOP_4->setProperty("variableSubstitutions", QVariant(QString()));
        archOn_5->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(GRGA):MODE", 0)));
        archOn_5->setProperty("variableSubstitutions", QVariant(QString()));
        archTO_5->setProperty("variable", QVariant(QApplication::translate("mainWindow", "GRGA:ANAT", 0)));
        archTime_5->setProperty("variable", QVariant(QApplication::translate("mainWindow", "GRGA:ANAT", 0)));
        box5->setTitle(QApplication::translate("mainWindow", "RGA", 0));
        ANA200_5->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):HEADSTA", 0)));
        SS_5->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):SCAN", 0)));
        BAR50_5->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):HEADSTA", 0)));
        BAR100_5->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):HEADSTA", 0)));
        BAR200_5->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):HEADSTA", 0)));
        STOP_5->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):HEADSTA", 0)));
        STOP_5->setProperty("variableSubstitutions", QVariant(QString()));
        archOn_6->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(GRGA):MODE", 0)));
        archOn_6->setProperty("variableSubstitutions", QVariant(QString()));
        archTO_6->setProperty("variable", QVariant(QApplication::translate("mainWindow", "GRGA:ANAT", 0)));
        archTime_6->setProperty("variable", QVariant(QApplication::translate("mainWindow", "GRGA:ANAT", 0)));
        box6->setTitle(QApplication::translate("mainWindow", "RGA", 0));
        ANA200_6->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):HEADSTA", 0)));
        SS_6->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):SCAN", 0)));
        BAR50_6->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):HEADSTA", 0)));
        BAR100_6->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):HEADSTA", 0)));
        BAR200_6->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):HEADSTA", 0)));
        STOP_6->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):HEADSTA", 0)));
        STOP_6->setProperty("variableSubstitutions", QVariant(QString()));
        archOn_7->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(GRGA):MODE", 0)));
        archOn_7->setProperty("variableSubstitutions", QVariant(QString()));
        archTO_7->setProperty("variable", QVariant(QApplication::translate("mainWindow", "GRGA:ANAT", 0)));
        archTime_7->setProperty("variable", QVariant(QApplication::translate("mainWindow", "GRGA:ANAT", 0)));
        scan_2->setTitle(QApplication::translate("mainWindow", "Archiver", 0));
        archStop2->setText(QApplication::translate("mainWindow", "Stop", 0));
        archStop2->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(GRGA):ARCH", 0)));
        archStop2->setProperty("altReadbackVariable", QVariant(QString()));
        archStop2->setProperty("variableSubstitutions", QVariant(QString()));
        archStop2->setClickText(QApplication::translate("mainWindow", "0", 0));
        archStop2->setClickCheckedText(QString());
        label_7->setText(QApplication::translate("mainWindow", "Archiver started", 0));
        archStart->setText(QApplication::translate("mainWindow", "Start", 0));
        archStart->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(GRGA):ARCH", 0)));
        archStart->setProperty("altReadbackVariable", QVariant(QString()));
        archStart->setProperty("variableSubstitutions", QVariant(QString()));
        archStart->setClickText(QApplication::translate("mainWindow", "1", 0));
        archStart->setClickCheckedText(QString());
        percentBox->setTitle(QApplication::translate("mainWindow", "Percent Scanned: 1-6", 0));
        per1->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):PERSCANNED", 0)));
        per2->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA2):PERSCANNED", 0)));
        per3->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA3):PERSCANNED", 0)));
        per4->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA4):PERSCANNED", 0)));
        per5->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA5):PERSCANNED", 0)));
        per6->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA6):PERSCANNED", 0)));
    } // retranslateUi

};

namespace Ui {
    class mainWindow: public Ui_mainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MV2_EPICSDISPLAY_V2_H
