/********************************************************************************
** Form generated from reading UI file 'mv2_epicsDisplay.ui'
**
** Created by: Qt User Interface Compiler version 5.7.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MV2_EPICSDISPLAY_H
#define UI_MV2_EPICSDISPLAY_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>
#include "QEAnalogIndicator.h"
#include "QEAnalogProgressBar.h"
#include "QECheckBox.h"
#include "QELabel.h"
#include "QEPushButton.h"
#include "QESimpleShape.h"
#include "QSimpleShape.h"

QT_BEGIN_NAMESPACE

class Ui_mainWindow
{
public:
    QWidget *centralwidget;
    QGroupBox *charts;
    QEPushButton *barscan;
    QEPushButton *barstrip;
    QEPushButton *anascan;
    QEPushButton *summary3;
    QEPushButton *summary1;
    QEPushButton *summary4;
    QEPushButton *summary2;
    QGroupBox *scan;
    QGroupBox *Mode;
    QLabel *label_3;
    QEPushButton *qepushbutton_34;
    QEPushButton *qebutton50;
    QEPushButton *qebutton200;
    QLabel *label_6;
    QECheckBox *qecheckbox_3;
    QEPushButton *qebutton100;
    QEPushButton *qepushbutton_30;
    QGroupBox *RGA1;
    QESimpleShape *qesimpleshape_13;
    QESimpleShape *qesimpleshape_14;
    QESimpleShape *qesimpleshape_15;
    QESimpleShape *qesimpleshape_16;
    QESimpleShape *qesimpleshape_17;
    QESimpleShape *qesimpleshape_18;
    QGroupBox *groupBox;
    QEAnalogProgressBar *qeanalogprogressbar;
    QEAnalogProgressBar *qeanalogprogressbar_2;
    QEAnalogProgressBar *qeanalogprogressbar_3;
    QEAnalogProgressBar *qeanalogprogressbar_4;
    QGroupBox *RGA1_2;
    QESimpleShape *qesimpleshape_25;
    QESimpleShape *qesimpleshape_26;
    QESimpleShape *qesimpleshape_27;
    QESimpleShape *qesimpleshape_28;
    QESimpleShape *qesimpleshape_29;
    QESimpleShape *qesimpleshape_30;
    QGroupBox *RGA1_3;
    QESimpleShape *qesimpleshape_31;
    QESimpleShape *qesimpleshape_32;
    QESimpleShape *qesimpleshape_33;
    QESimpleShape *qesimpleshape_34;
    QESimpleShape *qesimpleshape_35;
    QESimpleShape *qesimpleshape_36;
    QGroupBox *RGA1_4;
    QESimpleShape *qesimpleshape_37;
    QESimpleShape *qesimpleshape_38;
    QESimpleShape *qesimpleshape_39;
    QESimpleShape *qesimpleshape_40;
    QESimpleShape *qesimpleshape_41;
    QESimpleShape *qesimpleshape_42;
    QGroupBox *scan_2;
    QESimpleShape *qesimpleshape_19;
    QEPushButton *qepushbutton_31;
    QEPushButton *qepushbutton_32;
    QESimpleShape *qesimpleshape_20;
    QESimpleShape *qesimpleshape_21;
    QELabel *qelabel_2;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *label_9;
    QELabel *qelabel_3;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *mainWindow)
    {
        if (mainWindow->objectName().isEmpty())
            mainWindow->setObjectName(QStringLiteral("mainWindow"));
        mainWindow->resize(550, 499);
        centralwidget = new QWidget(mainWindow);
        centralwidget->setObjectName(QStringLiteral("centralwidget"));
        charts = new QGroupBox(centralwidget);
        charts->setObjectName(QStringLiteral("charts"));
        charts->setGeometry(QRect(10, 10, 511, 71));
        barscan = new QEPushButton(charts);
        barscan->setObjectName(QStringLiteral("barscan"));
        barscan->setGeometry(QRect(380, 20, 121, 20));
        barscan->setCheckable(false);
        barstrip = new QEPushButton(charts);
        barstrip->setObjectName(QStringLiteral("barstrip"));
        barstrip->setGeometry(QRect(220, 20, 141, 20));
        barstrip->setCheckable(false);
        anascan = new QEPushButton(charts);
        anascan->setObjectName(QStringLiteral("anascan"));
        anascan->setGeometry(QRect(380, 40, 121, 21));
        anascan->setCheckable(false);
        summary3 = new QEPushButton(charts);
        summary3->setObjectName(QStringLiteral("summary3"));
        summary3->setGeometry(QRect(10, 40, 91, 20));
        summary3->setCheckable(false);
        summary1 = new QEPushButton(charts);
        summary1->setObjectName(QStringLiteral("summary1"));
        summary1->setGeometry(QRect(10, 20, 91, 20));
        summary1->setCheckable(false);
        summary4 = new QEPushButton(charts);
        summary4->setObjectName(QStringLiteral("summary4"));
        summary4->setGeometry(QRect(100, 40, 101, 20));
        summary4->setCheckable(false);
        summary2 = new QEPushButton(charts);
        summary2->setObjectName(QStringLiteral("summary2"));
        summary2->setGeometry(QRect(100, 20, 101, 20));
        summary2->setCheckable(false);
        scan = new QGroupBox(centralwidget);
        scan->setObjectName(QStringLiteral("scan"));
        scan->setGeometry(QRect(10, 90, 511, 231));
        Mode = new QGroupBox(scan);
        Mode->setObjectName(QStringLiteral("Mode"));
        Mode->setGeometry(QRect(10, 20, 131, 201));
        label_3 = new QLabel(Mode);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(10, 40, 47, 13));
        qepushbutton_34 = new QEPushButton(Mode);
        qepushbutton_34->setObjectName(QStringLiteral("qepushbutton_34"));
        qepushbutton_34->setGeometry(QRect(10, 140, 77, 20));
        qebutton50 = new QEPushButton(Mode);
        qebutton50->setObjectName(QStringLiteral("qebutton50"));
        qebutton50->setGeometry(QRect(10, 60, 77, 20));
        qebutton200 = new QEPushButton(Mode);
        qebutton200->setObjectName(QStringLiteral("qebutton200"));
        qebutton200->setGeometry(QRect(10, 100, 77, 20));
        label_6 = new QLabel(Mode);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(10, 120, 121, 16));
        qecheckbox_3 = new QECheckBox(Mode);
        qecheckbox_3->setObjectName(QStringLiteral("qecheckbox_3"));
        qecheckbox_3->setGeometry(QRect(10, 170, 81, 21));
        qecheckbox_3->setChecked(false);
        qecheckbox_3->setWriteOnPress(false);
        qecheckbox_3->setWriteOnClick(true);
        qebutton100 = new QEPushButton(Mode);
        qebutton100->setObjectName(QStringLiteral("qebutton100"));
        qebutton100->setGeometry(QRect(10, 80, 77, 20));
        qepushbutton_30 = new QEPushButton(Mode);
        qepushbutton_30->setObjectName(QStringLiteral("qepushbutton_30"));
        qepushbutton_30->setGeometry(QRect(10, 20, 77, 20));
        RGA1 = new QGroupBox(scan);
        RGA1->setObjectName(QStringLiteral("RGA1"));
        RGA1->setGeometry(QRect(140, 20, 41, 201));
        qesimpleshape_13 = new QESimpleShape(RGA1);
        qesimpleshape_13->setObjectName(QStringLiteral("qesimpleshape_13"));
        qesimpleshape_13->setGeometry(QRect(10, 20, 16, 16));
        qesimpleshape_13->setFocusPolicy(Qt::NoFocus);
        qesimpleshape_13->setContextMenuPolicy(Qt::CustomContextMenu);
        qesimpleshape_13->setShape(QSimpleShape::ellipse);
        qesimpleshape_13->setProperty("colour0", QVariant(QColor(255, 255, 0)));
        qesimpleshape_13->setProperty("colour1", QVariant(QColor(255, 0, 0)));
        qesimpleshape_13->setProperty("displayAlarmStateOption", QVariant::fromValue(QESimpleShape::Never));
        qesimpleshape_14 = new QESimpleShape(RGA1);
        qesimpleshape_14->setObjectName(QStringLiteral("qesimpleshape_14"));
        qesimpleshape_14->setGeometry(QRect(10, 140, 16, 16));
        qesimpleshape_14->setShape(QSimpleShape::ellipse);
        qesimpleshape_14->setProperty("colour7", QVariant(QColor(200, 200, 200)));
        qesimpleshape_14->setProperty("colour8", QVariant(QColor(0, 200, 0)));
        qesimpleshape_14->setProperty("displayAlarmStateOption", QVariant::fromValue(QESimpleShape::Never));
        qesimpleshape_15 = new QESimpleShape(RGA1);
        qesimpleshape_15->setObjectName(QStringLiteral("qesimpleshape_15"));
        qesimpleshape_15->setGeometry(QRect(10, 170, 16, 16));
        qesimpleshape_15->setShape(QSimpleShape::ellipse);
        qesimpleshape_15->setProperty("colour0", QVariant(QColor(0, 255, 0)));
        qesimpleshape_15->setProperty("colour1", QVariant(QColor(200, 200, 200)));
        qesimpleshape_15->setProperty("flash0", QVariant(false));
        qesimpleshape_15->setProperty("displayAlarmStateOption", QVariant::fromValue(QESimpleShape::Never));
        qesimpleshape_16 = new QESimpleShape(RGA1);
        qesimpleshape_16->setObjectName(QStringLiteral("qesimpleshape_16"));
        qesimpleshape_16->setGeometry(QRect(10, 60, 16, 16));
        qesimpleshape_16->setShape(QSimpleShape::ellipse);
        qesimpleshape_16->setProperty("colour3", QVariant(QColor(200, 200, 200)));
        qesimpleshape_16->setProperty("colour4", QVariant(QColor(200, 200, 200)));
        qesimpleshape_16->setProperty("colour5", QVariant(QColor(0, 200, 0)));
        qesimpleshape_16->setProperty("flash0", QVariant(false));
        qesimpleshape_16->setProperty("flash1", QVariant(false));
        qesimpleshape_16->setProperty("displayAlarmStateOption", QVariant::fromValue(QESimpleShape::Never));
        qesimpleshape_17 = new QESimpleShape(RGA1);
        qesimpleshape_17->setObjectName(QStringLiteral("qesimpleshape_17"));
        qesimpleshape_17->setGeometry(QRect(10, 80, 16, 16));
        qesimpleshape_17->setShape(QSimpleShape::ellipse);
        qesimpleshape_17->setProperty("colour6", QVariant(QColor(0, 200, 0)));
        qesimpleshape_17->setProperty("displayAlarmStateOption", QVariant::fromValue(QESimpleShape::Never));
        qesimpleshape_18 = new QESimpleShape(RGA1);
        qesimpleshape_18->setObjectName(QStringLiteral("qesimpleshape_18"));
        qesimpleshape_18->setGeometry(QRect(10, 100, 16, 16));
        qesimpleshape_18->setShape(QSimpleShape::ellipse);
        qesimpleshape_18->setProperty("colour7", QVariant(QColor(0, 200, 0)));
        qesimpleshape_18->setProperty("visible", QVariant(true));
        qesimpleshape_18->setProperty("displayAlarmStateOption", QVariant::fromValue(QESimpleShape::Never));
        groupBox = new QGroupBox(scan);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(320, 20, 151, 201));
        qeanalogprogressbar = new QEAnalogProgressBar(groupBox);
        qeanalogprogressbar->setObjectName(QStringLiteral("qeanalogprogressbar"));
        qeanalogprogressbar->setGeometry(QRect(20, 20, 21, 171));
        qeanalogprogressbar->setOrientation(QEAnalogIndicator::Bottom_To_Top);
        qeanalogprogressbar_2 = new QEAnalogProgressBar(groupBox);
        qeanalogprogressbar_2->setObjectName(QStringLiteral("qeanalogprogressbar_2"));
        qeanalogprogressbar_2->setGeometry(QRect(50, 20, 21, 171));
        qeanalogprogressbar_2->setOrientation(QEAnalogIndicator::Bottom_To_Top);
        qeanalogprogressbar_3 = new QEAnalogProgressBar(groupBox);
        qeanalogprogressbar_3->setObjectName(QStringLiteral("qeanalogprogressbar_3"));
        qeanalogprogressbar_3->setGeometry(QRect(80, 20, 21, 171));
        qeanalogprogressbar_3->setOrientation(QEAnalogIndicator::Bottom_To_Top);
        qeanalogprogressbar_4 = new QEAnalogProgressBar(groupBox);
        qeanalogprogressbar_4->setObjectName(QStringLiteral("qeanalogprogressbar_4"));
        qeanalogprogressbar_4->setGeometry(QRect(110, 20, 21, 171));
        qeanalogprogressbar_4->setOrientation(QEAnalogIndicator::Bottom_To_Top);
        RGA1_2 = new QGroupBox(scan);
        RGA1_2->setObjectName(QStringLiteral("RGA1_2"));
        RGA1_2->setGeometry(QRect(180, 20, 41, 201));
        qesimpleshape_25 = new QESimpleShape(RGA1_2);
        qesimpleshape_25->setObjectName(QStringLiteral("qesimpleshape_25"));
        qesimpleshape_25->setGeometry(QRect(10, 20, 16, 16));
        qesimpleshape_25->setFocusPolicy(Qt::NoFocus);
        qesimpleshape_25->setContextMenuPolicy(Qt::CustomContextMenu);
        qesimpleshape_25->setShape(QSimpleShape::ellipse);
        qesimpleshape_25->setProperty("colour0", QVariant(QColor(255, 255, 0)));
        qesimpleshape_25->setProperty("colour1", QVariant(QColor(255, 0, 0)));
        qesimpleshape_25->setProperty("displayAlarmStateOption", QVariant::fromValue(QESimpleShape::Never));
        qesimpleshape_26 = new QESimpleShape(RGA1_2);
        qesimpleshape_26->setObjectName(QStringLiteral("qesimpleshape_26"));
        qesimpleshape_26->setGeometry(QRect(10, 140, 16, 16));
        qesimpleshape_26->setShape(QSimpleShape::ellipse);
        qesimpleshape_26->setProperty("colour7", QVariant(QColor(200, 200, 200)));
        qesimpleshape_26->setProperty("colour8", QVariant(QColor(0, 200, 0)));
        qesimpleshape_26->setProperty("displayAlarmStateOption", QVariant::fromValue(QESimpleShape::Never));
        qesimpleshape_27 = new QESimpleShape(RGA1_2);
        qesimpleshape_27->setObjectName(QStringLiteral("qesimpleshape_27"));
        qesimpleshape_27->setGeometry(QRect(10, 170, 16, 16));
        qesimpleshape_27->setShape(QSimpleShape::ellipse);
        qesimpleshape_27->setProperty("colour0", QVariant(QColor(0, 255, 0)));
        qesimpleshape_27->setProperty("colour1", QVariant(QColor(200, 200, 200)));
        qesimpleshape_27->setProperty("flash0", QVariant(false));
        qesimpleshape_27->setProperty("displayAlarmStateOption", QVariant::fromValue(QESimpleShape::Never));
        qesimpleshape_28 = new QESimpleShape(RGA1_2);
        qesimpleshape_28->setObjectName(QStringLiteral("qesimpleshape_28"));
        qesimpleshape_28->setGeometry(QRect(10, 60, 16, 16));
        qesimpleshape_28->setShape(QSimpleShape::ellipse);
        qesimpleshape_28->setProperty("colour3", QVariant(QColor(200, 200, 200)));
        qesimpleshape_28->setProperty("colour4", QVariant(QColor(200, 200, 200)));
        qesimpleshape_28->setProperty("colour5", QVariant(QColor(0, 200, 0)));
        qesimpleshape_28->setProperty("flash0", QVariant(false));
        qesimpleshape_28->setProperty("flash1", QVariant(false));
        qesimpleshape_28->setProperty("displayAlarmStateOption", QVariant::fromValue(QESimpleShape::Never));
        qesimpleshape_29 = new QESimpleShape(RGA1_2);
        qesimpleshape_29->setObjectName(QStringLiteral("qesimpleshape_29"));
        qesimpleshape_29->setGeometry(QRect(10, 80, 16, 16));
        qesimpleshape_29->setShape(QSimpleShape::ellipse);
        qesimpleshape_29->setProperty("colour6", QVariant(QColor(0, 200, 0)));
        qesimpleshape_29->setProperty("displayAlarmStateOption", QVariant::fromValue(QESimpleShape::Never));
        qesimpleshape_30 = new QESimpleShape(RGA1_2);
        qesimpleshape_30->setObjectName(QStringLiteral("qesimpleshape_30"));
        qesimpleshape_30->setGeometry(QRect(10, 100, 16, 16));
        qesimpleshape_30->setShape(QSimpleShape::ellipse);
        qesimpleshape_30->setProperty("colour7", QVariant(QColor(0, 200, 0)));
        qesimpleshape_30->setProperty("displayAlarmStateOption", QVariant::fromValue(QESimpleShape::Never));
        RGA1_3 = new QGroupBox(scan);
        RGA1_3->setObjectName(QStringLiteral("RGA1_3"));
        RGA1_3->setGeometry(QRect(260, 20, 41, 201));
        qesimpleshape_31 = new QESimpleShape(RGA1_3);
        qesimpleshape_31->setObjectName(QStringLiteral("qesimpleshape_31"));
        qesimpleshape_31->setGeometry(QRect(10, 20, 16, 16));
        qesimpleshape_31->setFocusPolicy(Qt::NoFocus);
        qesimpleshape_31->setContextMenuPolicy(Qt::CustomContextMenu);
        qesimpleshape_31->setShape(QSimpleShape::ellipse);
        qesimpleshape_31->setProperty("colour0", QVariant(QColor(255, 255, 0)));
        qesimpleshape_31->setProperty("colour1", QVariant(QColor(255, 0, 0)));
        qesimpleshape_31->setProperty("displayAlarmStateOption", QVariant::fromValue(QESimpleShape::Never));
        qesimpleshape_32 = new QESimpleShape(RGA1_3);
        qesimpleshape_32->setObjectName(QStringLiteral("qesimpleshape_32"));
        qesimpleshape_32->setGeometry(QRect(10, 140, 16, 16));
        qesimpleshape_32->setShape(QSimpleShape::ellipse);
        qesimpleshape_32->setProperty("colour7", QVariant(QColor(200, 200, 200)));
        qesimpleshape_32->setProperty("colour8", QVariant(QColor(0, 200, 0)));
        qesimpleshape_32->setProperty("displayAlarmStateOption", QVariant::fromValue(QESimpleShape::Never));
        qesimpleshape_33 = new QESimpleShape(RGA1_3);
        qesimpleshape_33->setObjectName(QStringLiteral("qesimpleshape_33"));
        qesimpleshape_33->setGeometry(QRect(10, 170, 16, 16));
        qesimpleshape_33->setShape(QSimpleShape::ellipse);
        qesimpleshape_33->setProperty("colour0", QVariant(QColor(0, 255, 0)));
        qesimpleshape_33->setProperty("colour1", QVariant(QColor(200, 200, 200)));
        qesimpleshape_33->setProperty("flash0", QVariant(false));
        qesimpleshape_33->setProperty("displayAlarmStateOption", QVariant::fromValue(QESimpleShape::Never));
        qesimpleshape_34 = new QESimpleShape(RGA1_3);
        qesimpleshape_34->setObjectName(QStringLiteral("qesimpleshape_34"));
        qesimpleshape_34->setGeometry(QRect(10, 60, 16, 16));
        qesimpleshape_34->setShape(QSimpleShape::ellipse);
        qesimpleshape_34->setProperty("colour3", QVariant(QColor(200, 200, 200)));
        qesimpleshape_34->setProperty("colour4", QVariant(QColor(200, 200, 200)));
        qesimpleshape_34->setProperty("colour5", QVariant(QColor(0, 200, 0)));
        qesimpleshape_34->setProperty("flash0", QVariant(false));
        qesimpleshape_34->setProperty("flash1", QVariant(false));
        qesimpleshape_34->setProperty("displayAlarmStateOption", QVariant::fromValue(QESimpleShape::Never));
        qesimpleshape_35 = new QESimpleShape(RGA1_3);
        qesimpleshape_35->setObjectName(QStringLiteral("qesimpleshape_35"));
        qesimpleshape_35->setGeometry(QRect(10, 80, 16, 16));
        qesimpleshape_35->setShape(QSimpleShape::ellipse);
        qesimpleshape_35->setProperty("colour6", QVariant(QColor(0, 200, 0)));
        qesimpleshape_35->setProperty("displayAlarmStateOption", QVariant::fromValue(QESimpleShape::Never));
        qesimpleshape_36 = new QESimpleShape(RGA1_3);
        qesimpleshape_36->setObjectName(QStringLiteral("qesimpleshape_36"));
        qesimpleshape_36->setGeometry(QRect(10, 100, 16, 16));
        qesimpleshape_36->setShape(QSimpleShape::ellipse);
        qesimpleshape_36->setProperty("colour7", QVariant(QColor(0, 200, 0)));
        qesimpleshape_36->setProperty("displayAlarmStateOption", QVariant::fromValue(QESimpleShape::Never));
        RGA1_4 = new QGroupBox(scan);
        RGA1_4->setObjectName(QStringLiteral("RGA1_4"));
        RGA1_4->setGeometry(QRect(220, 20, 41, 201));
        qesimpleshape_37 = new QESimpleShape(RGA1_4);
        qesimpleshape_37->setObjectName(QStringLiteral("qesimpleshape_37"));
        qesimpleshape_37->setGeometry(QRect(10, 20, 16, 16));
        qesimpleshape_37->setFocusPolicy(Qt::NoFocus);
        qesimpleshape_37->setContextMenuPolicy(Qt::CustomContextMenu);
        qesimpleshape_37->setShape(QSimpleShape::ellipse);
        qesimpleshape_37->setProperty("colour0", QVariant(QColor(255, 255, 0)));
        qesimpleshape_37->setProperty("colour1", QVariant(QColor(255, 0, 0)));
        qesimpleshape_37->setProperty("displayAlarmStateOption", QVariant::fromValue(QESimpleShape::Never));
        qesimpleshape_38 = new QESimpleShape(RGA1_4);
        qesimpleshape_38->setObjectName(QStringLiteral("qesimpleshape_38"));
        qesimpleshape_38->setGeometry(QRect(10, 140, 16, 16));
        qesimpleshape_38->setShape(QSimpleShape::ellipse);
        qesimpleshape_38->setProperty("colour7", QVariant(QColor(200, 200, 200)));
        qesimpleshape_38->setProperty("colour8", QVariant(QColor(0, 200, 0)));
        qesimpleshape_38->setProperty("displayAlarmStateOption", QVariant::fromValue(QESimpleShape::Never));
        qesimpleshape_39 = new QESimpleShape(RGA1_4);
        qesimpleshape_39->setObjectName(QStringLiteral("qesimpleshape_39"));
        qesimpleshape_39->setGeometry(QRect(10, 170, 16, 16));
        qesimpleshape_39->setShape(QSimpleShape::ellipse);
        qesimpleshape_39->setProperty("colour0", QVariant(QColor(0, 255, 0)));
        qesimpleshape_39->setProperty("colour1", QVariant(QColor(200, 200, 200)));
        qesimpleshape_39->setProperty("flash0", QVariant(false));
        qesimpleshape_39->setProperty("displayAlarmStateOption", QVariant::fromValue(QESimpleShape::Never));
        qesimpleshape_40 = new QESimpleShape(RGA1_4);
        qesimpleshape_40->setObjectName(QStringLiteral("qesimpleshape_40"));
        qesimpleshape_40->setGeometry(QRect(10, 60, 16, 16));
        qesimpleshape_40->setShape(QSimpleShape::ellipse);
        qesimpleshape_40->setProperty("colour3", QVariant(QColor(200, 200, 200)));
        qesimpleshape_40->setProperty("colour4", QVariant(QColor(200, 200, 200)));
        qesimpleshape_40->setProperty("colour5", QVariant(QColor(0, 200, 0)));
        qesimpleshape_40->setProperty("flash0", QVariant(false));
        qesimpleshape_40->setProperty("flash1", QVariant(false));
        qesimpleshape_40->setProperty("displayAlarmStateOption", QVariant::fromValue(QESimpleShape::Never));
        qesimpleshape_41 = new QESimpleShape(RGA1_4);
        qesimpleshape_41->setObjectName(QStringLiteral("qesimpleshape_41"));
        qesimpleshape_41->setGeometry(QRect(10, 80, 16, 16));
        qesimpleshape_41->setShape(QSimpleShape::ellipse);
        qesimpleshape_41->setProperty("colour6", QVariant(QColor(0, 200, 0)));
        qesimpleshape_41->setProperty("displayAlarmStateOption", QVariant::fromValue(QESimpleShape::Never));
        qesimpleshape_42 = new QESimpleShape(RGA1_4);
        qesimpleshape_42->setObjectName(QStringLiteral("qesimpleshape_42"));
        qesimpleshape_42->setGeometry(QRect(10, 100, 16, 16));
        qesimpleshape_42->setShape(QSimpleShape::ellipse);
        qesimpleshape_42->setProperty("colour7", QVariant(QColor(0, 200, 0)));
        qesimpleshape_42->setProperty("displayAlarmStateOption", QVariant::fromValue(QESimpleShape::Never));
        scan_2 = new QGroupBox(centralwidget);
        scan_2->setObjectName(QStringLiteral("scan_2"));
        scan_2->setGeometry(QRect(10, 330, 301, 131));
        qesimpleshape_19 = new QESimpleShape(scan_2);
        qesimpleshape_19->setObjectName(QStringLiteral("qesimpleshape_19"));
        qesimpleshape_19->setGeometry(QRect(270, 30, 21, 21));
        qesimpleshape_19->setFocusPolicy(Qt::NoFocus);
        qesimpleshape_19->setContextMenuPolicy(Qt::CustomContextMenu);
        qesimpleshape_19->setShape(QSimpleShape::ellipse);
        qesimpleshape_19->setProperty("colour0", QVariant(QColor(200, 200, 200)));
        qesimpleshape_19->setProperty("colour1", QVariant(QColor(0, 255, 0)));
        qesimpleshape_19->setProperty("colour2", QVariant(QColor(0, 255, 0)));
        qesimpleshape_19->setProperty("colour3", QVariant(QColor(0, 255, 0)));
        qesimpleshape_19->setProperty("displayAlarmStateOption", QVariant::fromValue(QESimpleShape::Never));
        qepushbutton_31 = new QEPushButton(scan_2);
        qepushbutton_31->setObjectName(QStringLiteral("qepushbutton_31"));
        qepushbutton_31->setGeometry(QRect(10, 100, 81, 20));
        qepushbutton_32 = new QEPushButton(scan_2);
        qepushbutton_32->setObjectName(QStringLiteral("qepushbutton_32"));
        qepushbutton_32->setGeometry(QRect(10, 20, 81, 71));
        qesimpleshape_20 = new QESimpleShape(scan_2);
        qesimpleshape_20->setObjectName(QStringLiteral("qesimpleshape_20"));
        qesimpleshape_20->setGeometry(QRect(270, 90, 21, 21));
        qesimpleshape_20->setFocusPolicy(Qt::NoFocus);
        qesimpleshape_20->setContextMenuPolicy(Qt::CustomContextMenu);
        qesimpleshape_20->setShape(QSimpleShape::ellipse);
        qesimpleshape_20->setProperty("colour0", QVariant(QColor(200, 200, 200)));
        qesimpleshape_20->setProperty("colour1", QVariant(QColor(205, 200, 200)));
        qesimpleshape_20->setProperty("colour3", QVariant(QColor(0, 255, 0)));
        qesimpleshape_20->setProperty("displayAlarmStateOption", QVariant::fromValue(QESimpleShape::Never));
        qesimpleshape_21 = new QESimpleShape(scan_2);
        qesimpleshape_21->setObjectName(QStringLiteral("qesimpleshape_21"));
        qesimpleshape_21->setGeometry(QRect(270, 60, 21, 21));
        qesimpleshape_21->setFocusPolicy(Qt::NoFocus);
        qesimpleshape_21->setContextMenuPolicy(Qt::CustomContextMenu);
        qesimpleshape_21->setShape(QSimpleShape::ellipse);
        qesimpleshape_21->setProperty("colour0", QVariant(QColor(200, 200, 200)));
        qesimpleshape_21->setProperty("colour1", QVariant(QColor(200, 200, 200)));
        qesimpleshape_21->setProperty("colour2", QVariant(QColor(0, 255, 0)));
        qesimpleshape_21->setProperty("displayAlarmStateOption", QVariant::fromValue(QESimpleShape::Never));
        qelabel_2 = new QELabel(scan_2);
        qelabel_2->setObjectName(QStringLiteral("qelabel_2"));
        qelabel_2->setGeometry(QRect(220, 90, 41, 21));
        label_7 = new QLabel(scan_2);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(110, 30, 81, 16));
        label_8 = new QLabel(scan_2);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(110, 60, 101, 20));
        label_9 = new QLabel(scan_2);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(110, 90, 101, 20));
        qelabel_3 = new QELabel(scan_2);
        qelabel_3->setObjectName(QStringLiteral("qelabel_3"));
        qelabel_3->setGeometry(QRect(220, 60, 41, 21));
        mainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(mainWindow);
        menubar->setObjectName(QStringLiteral("menubar"));
        menubar->setGeometry(QRect(0, 0, 550, 21));
        mainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(mainWindow);
        statusbar->setObjectName(QStringLiteral("statusbar"));
        mainWindow->setStatusBar(statusbar);

        retranslateUi(mainWindow);

        QMetaObject::connectSlotsByName(mainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *mainWindow)
    {
        mainWindow->setWindowTitle(QApplication::translate("mainWindow", "MainWindow", 0));
        charts->setTitle(QApplication::translate("mainWindow", "RGA plots", 0));
        barscan->setText(QApplication::translate("mainWindow", "RGA Bar Chart", 0));
        barscan->setProperty("variable", QVariant(QString()));
        barscan->setProperty("altReadbackVariable", QVariant(QString()));
        barscan->setPressText(QApplication::translate("mainWindow", "1", 0));
        barscan->setProperty("guiFile", QVariant(QApplication::translate("mainWindow", "barchart.ui", 0)));
        barstrip->setText(QApplication::translate("mainWindow", "RGA Strip chart", 0));
        barstrip->setProperty("variable", QVariant(QString()));
        barstrip->setProperty("altReadbackVariable", QVariant(QString()));
        barstrip->setProperty("variableSubstitutions", QVariant(QString()));
        barstrip->setPressText(QApplication::translate("mainWindow", "1", 0));
        barstrip->setProperty("guiFile", QVariant(QApplication::translate("mainWindow", "mv2_main_bar.ui", 0)));
        anascan->setText(QApplication::translate("mainWindow", "RGA Analogue Scan", 0));
        anascan->setProperty("variable", QVariant(QString()));
        anascan->setProperty("altReadbackVariable", QVariant(QString()));
        anascan->setPressText(QApplication::translate("mainWindow", "1", 0));
        anascan->setProperty("guiFile", QVariant(QApplication::translate("mainWindow", "barchart_ana.ui", 0)));
        summary3->setText(QApplication::translate("mainWindow", "RGA summary 3", 0));
        summary3->setProperty("variable", QVariant(QString()));
        summary3->setProperty("altReadbackVariable", QVariant(QString()));
        summary3->setProperty("variableSubstitutions", QVariant(QString()));
        summary3->setPressText(QApplication::translate("mainWindow", "3", 0));
        summary3->setClickText(QApplication::translate("mainWindow", "3", 0));
        summary3->setProperty("guiFile", QVariant(QApplication::translate("mainWindow", "mv2_main_bar.ui", 0)));
        summary1->setText(QApplication::translate("mainWindow", "RGA summary 1", 0));
        summary1->setProperty("variable", QVariant(QString()));
        summary1->setProperty("altReadbackVariable", QVariant(QString()));
        summary1->setProperty("variableSubstitutions", QVariant(QString()));
        summary1->setPressText(QApplication::translate("mainWindow", "1", 0));
        summary1->setProperty("guiFile", QVariant(QApplication::translate("mainWindow", "mv2_main_bar.ui", 0)));
        summary4->setText(QApplication::translate("mainWindow", "RGA Summary 4", 0));
        summary4->setProperty("variable", QVariant(QString()));
        summary4->setProperty("altReadbackVariable", QVariant(QString()));
        summary4->setProperty("variableSubstitutions", QVariant(QString()));
        summary4->setPressText(QApplication::translate("mainWindow", "4", 0));
        summary4->setClickText(QApplication::translate("mainWindow", "4", 0));
        summary4->setProperty("guiFile", QVariant(QApplication::translate("mainWindow", "mv2_main_bar.ui", 0)));
        summary2->setText(QApplication::translate("mainWindow", "RGA Summary 2", 0));
        summary2->setProperty("variable", QVariant(QString()));
        summary2->setProperty("altReadbackVariable", QVariant(QString()));
        summary2->setProperty("variableSubstitutions", QVariant(QString()));
        summary2->setPressText(QApplication::translate("mainWindow", "2", 0));
        summary2->setClickText(QApplication::translate("mainWindow", "2", 0));
        summary2->setProperty("guiFile", QVariant(QApplication::translate("mainWindow", "mv2_main_bar.ui", 0)));
        scan->setTitle(QApplication::translate("mainWindow", "Scan", 0));
        Mode->setTitle(QApplication::translate("mainWindow", "Set All:", 0));
        label_3->setText(QApplication::translate("mainWindow", "Bar Chart", 0));
        qepushbutton_34->setText(QApplication::translate("mainWindow", "1-200", 0));
        qepushbutton_34->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(GRGA):CON", 0)));
        qepushbutton_34->setProperty("altReadbackVariable", QVariant(QString()));
        qepushbutton_34->setProperty("variableSubstitutions", QVariant(QString()));
        qepushbutton_34->setClickText(QApplication::translate("mainWindow", "8", 0));
        qepushbutton_34->setClickCheckedText(QString());
        qebutton50->setText(QApplication::translate("mainWindow", "1-50", 0));
        qebutton50->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(GRGA):CON", 0)));
        qebutton50->setProperty("altReadbackVariable", QVariant(QString()));
        qebutton50->setProperty("variableSubstitutions", QVariant(QString()));
        qebutton50->setClickText(QApplication::translate("mainWindow", "5", 0));
        qebutton50->setClickCheckedText(QString());
        qebutton200->setText(QApplication::translate("mainWindow", "1-200", 0));
        qebutton200->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(GRGA):CON", 0)));
        qebutton200->setProperty("altReadbackVariable", QVariant(QString()));
        qebutton200->setProperty("variableSubstitutions", QVariant(QApplication::translate("mainWindow", ")", 0)));
        qebutton200->setClickText(QApplication::translate("mainWindow", "7", 0));
        qebutton200->setClickCheckedText(QString());
        label_6->setText(QApplication::translate("mainWindow", "Analog Scan (32 ppp)", 0));
        qecheckbox_3->setText(QApplication::translate("mainWindow", "Single Scan", 0));
        qecheckbox_3->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(GRGA):SETSCAN", 0)));
        qecheckbox_3->setPressText(QApplication::translate("mainWindow", "0", 0));
        qecheckbox_3->setReleaseText(QApplication::translate("mainWindow", "1", 0));
        qecheckbox_3->setClickText(QApplication::translate("mainWindow", "1", 0));
        qecheckbox_3->setClickCheckedText(QApplication::translate("mainWindow", "0", 0));
        qebutton100->setText(QApplication::translate("mainWindow", "1-100", 0));
        qebutton100->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(GRGA):CON", 0)));
        qebutton100->setProperty("altReadbackVariable", QVariant(QString()));
        qebutton100->setProperty("variableSubstitutions", QVariant(QString()));
        qebutton100->setClickText(QApplication::translate("mainWindow", "6", 0));
        qebutton100->setClickCheckedText(QString());
        qepushbutton_30->setText(QApplication::translate("mainWindow", "Stop", 0));
        qepushbutton_30->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(GRGA):CON", 0)));
        qepushbutton_30->setProperty("altReadbackVariable", QVariant(QString()));
        qepushbutton_30->setProperty("variableSubstitutions", QVariant(QString()));
        qepushbutton_30->setClickText(QApplication::translate("mainWindow", "Stop", 0));
        qepushbutton_30->setClickCheckedText(QString());
        RGA1->setTitle(QApplication::translate("mainWindow", "RG1", 0));
        qesimpleshape_13->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):HEADSTA", 0)));
        qesimpleshape_13->setProperty("variableSubstitutions", QVariant(QString()));
        qesimpleshape_14->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):HEADSTA", 0)));
        qesimpleshape_15->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):SCAN", 0)));
        qesimpleshape_16->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):HEADSTA", 0)));
        qesimpleshape_17->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):HEADSTA", 0)));
        qesimpleshape_18->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):HEADSTA", 0)));
        groupBox->setTitle(QApplication::translate("mainWindow", "Percent Scanned: 1-4", 0));
        qeanalogprogressbar->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):PERSCANNED", 0)));
        qeanalogprogressbar_2->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA2):PERSCANNED", 0)));
        qeanalogprogressbar_3->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA3):PERSCANNED", 0)));
        qeanalogprogressbar_4->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA4):PERSCANNED", 0)));
        RGA1_2->setTitle(QApplication::translate("mainWindow", "RG2", 0));
        qesimpleshape_25->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA2):HEADSTA", 0)));
        qesimpleshape_25->setProperty("variableSubstitutions", QVariant(QString()));
        qesimpleshape_26->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA2):HEADSTA", 0)));
        qesimpleshape_27->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA2):SCAN", 0)));
        qesimpleshape_28->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA2):HEADSTA", 0)));
        qesimpleshape_29->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA2):HEADSTA", 0)));
        qesimpleshape_30->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA2):HEADSTA", 0)));
        RGA1_3->setTitle(QApplication::translate("mainWindow", "RGA4", 0));
        qesimpleshape_31->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA4):HEADSTA", 0)));
        qesimpleshape_31->setProperty("variableSubstitutions", QVariant(QString()));
        qesimpleshape_32->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA4):HEADSTA", 0)));
        qesimpleshape_33->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA4):SCAN", 0)));
        qesimpleshape_34->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA4):HEADSTA", 0)));
        qesimpleshape_35->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA4):HEADSTA", 0)));
        qesimpleshape_36->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA4):HEADSTA", 0)));
        RGA1_4->setTitle(QApplication::translate("mainWindow", "RGA3", 0));
        qesimpleshape_37->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA3):HEADSTA", 0)));
        qesimpleshape_37->setProperty("variableSubstitutions", QVariant(QString()));
        qesimpleshape_38->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA3):HEADSTA", 0)));
        qesimpleshape_39->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA3):SCAN", 0)));
        qesimpleshape_40->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA3):HEADSTA", 0)));
        qesimpleshape_41->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA3):HEADSTA", 0)));
        qesimpleshape_42->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA3):HEADSTA", 0)));
        scan_2->setTitle(QApplication::translate("mainWindow", "Archive", 0));
        qesimpleshape_19->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(GRGA):MODE", 0)));
        qesimpleshape_19->setProperty("variableSubstitutions", QVariant(QString()));
        qepushbutton_31->setText(QApplication::translate("mainWindow", "Stop", 0));
        qepushbutton_31->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(GRGA):ARCH", 0)));
        qepushbutton_31->setProperty("altReadbackVariable", QVariant(QString()));
        qepushbutton_31->setProperty("variableSubstitutions", QVariant(QString()));
        qepushbutton_31->setClickText(QApplication::translate("mainWindow", "0", 0));
        qepushbutton_31->setClickCheckedText(QString());
        qepushbutton_32->setText(QApplication::translate("mainWindow", "Start", 0));
        qepushbutton_32->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(GRGA):ARCH", 0)));
        qepushbutton_32->setProperty("altReadbackVariable", QVariant(QString()));
        qepushbutton_32->setProperty("variableSubstitutions", QVariant(QString()));
        qepushbutton_32->setClickText(QApplication::translate("mainWindow", "1", 0));
        qepushbutton_32->setClickCheckedText(QString());
        qesimpleshape_20->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(GRGA):MODE", 0)));
        qesimpleshape_20->setProperty("variableSubstitutions", QVariant(QString()));
        qesimpleshape_21->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(GRGA):MODE", 0)));
        qesimpleshape_21->setProperty("variableSubstitutions", QVariant(QString()));
        qelabel_2->setProperty("variable", QVariant(QApplication::translate("mainWindow", "GRGA:ANAT", 0)));
        label_7->setText(QApplication::translate("mainWindow", "Archiver running", 0));
        label_8->setText(QApplication::translate("mainWindow", "Time until Bar Scan", 0));
        label_9->setText(QApplication::translate("mainWindow", "Time until Ana Scan", 0));
        qelabel_3->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(GRGA):BART", 0)));
    } // retranslateUi

};

namespace Ui {
    class mainWindow: public Ui_mainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MV2_EPICSDISPLAY_H
