/********************************************************************************
** Form generated from reading UI file 'mv2_epicsDisplay.ui'
**
** Created by: Qt User Interface Compiler version 5.5.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MV2_EPICSDISPLAY_H
#define UI_MV2_EPICSDISPLAY_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>
#include "QEAnalogIndicator.h"
#include "QEAnalogProgressBar.h"
#include "QECheckBox.h"
#include "QELabel.h"
#include "QELineEdit.h"
#include "QEPushButton.h"
#include "QESimpleShape.h"
#include "QSimpleShape.h"

QT_BEGIN_NAMESPACE

class Ui_mainWindow
{
public:
    QWidget *centralwidget;
    QGroupBox *charts;
    QEPushButton *barscan;
    QEPushButton *barstrip;
    QEPushButton *anascan;
    QEPushButton *summary3;
    QEPushButton *summary1;
    QEPushButton *summary4;
    QEPushButton *summary2;
    QGroupBox *scan;
    QGroupBox *Mode;
    QLabel *label_3;
    QEPushButton *archAna;
    QEPushButton *arch50;
    QEPushButton *arch200;
    QLabel *label_6;
    QECheckBox *archSS;
    QEPushButton *arch100;
    QEPushButton *archStop;
    QGroupBox *RGA1;
    QESimpleShape *qesimpleshape_13;
    QESimpleShape *qesimpleshape_14;
    QESimpleShape *qesimpleshape_15;
    QESimpleShape *qesimpleshape_16;
    QESimpleShape *qesimpleshape_17;
    QESimpleShape *qesimpleshape_18;
    QGroupBox *groupBox;
    QEAnalogProgressBar *qeanalogprogressbar;
    QEAnalogProgressBar *qeanalogprogressbar_2;
    QEAnalogProgressBar *qeanalogprogressbar_3;
    QEAnalogProgressBar *qeanalogprogressbar_4;
    QGroupBox *RGA1_2;
    QESimpleShape *qesimpleshape_25;
    QESimpleShape *qesimpleshape_26;
    QESimpleShape *qesimpleshape_27;
    QESimpleShape *qesimpleshape_28;
    QESimpleShape *qesimpleshape_29;
    QESimpleShape *qesimpleshape_30;
    QGroupBox *RGA1_3;
    QESimpleShape *qesimpleshape_31;
    QESimpleShape *qesimpleshape_32;
    QESimpleShape *qesimpleshape_33;
    QESimpleShape *qesimpleshape_34;
    QESimpleShape *qesimpleshape_35;
    QESimpleShape *qesimpleshape_36;
    QGroupBox *RGA1_4;
    QESimpleShape *qesimpleshape_37;
    QESimpleShape *qesimpleshape_38;
    QESimpleShape *qesimpleshape_39;
    QESimpleShape *qesimpleshape_40;
    QESimpleShape *qesimpleshape_41;
    QESimpleShape *qesimpleshape_42;
    QGroupBox *scan_2;
    QESimpleShape *archOn;
    QEPushButton *archStop2;
    QEPushButton *archStart;
    QESimpleShape *archAnaOn;
    QELabel *archTime;
    QLabel *label_7;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QESimpleShape *archFil;
    QLabel *label_12;
    QESimpleShape *archScan;
    QLabel *lablex;
    QELabel *archFailC;
    QEPushButton *archFailR;
    QLabel *label_14;
    QELabel *archTO;
    QLabel *label_15;
    QELineEdit *archTOVal;
    QELineEdit *archDT;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *mainWindow)
    {
        if (mainWindow->objectName().isEmpty())
            mainWindow->setObjectName(QStringLiteral("mainWindow"));
        mainWindow->resize(543, 564);
        centralwidget = new QWidget(mainWindow);
        centralwidget->setObjectName(QStringLiteral("centralwidget"));
        charts = new QGroupBox(centralwidget);
        charts->setObjectName(QStringLiteral("charts"));
        charts->setGeometry(QRect(10, 10, 511, 71));
        barscan = new QEPushButton(charts);
        barscan->setObjectName(QStringLiteral("barscan"));
        barscan->setGeometry(QRect(380, 20, 121, 20));
        barscan->setCheckable(false);
        barstrip = new QEPushButton(charts);
        barstrip->setObjectName(QStringLiteral("barstrip"));
        barstrip->setGeometry(QRect(220, 20, 141, 20));
        barstrip->setCheckable(false);
        anascan = new QEPushButton(charts);
        anascan->setObjectName(QStringLiteral("anascan"));
        anascan->setGeometry(QRect(380, 40, 121, 21));
        anascan->setCheckable(false);
        summary3 = new QEPushButton(charts);
        summary3->setObjectName(QStringLiteral("summary3"));
        summary3->setGeometry(QRect(10, 40, 91, 20));
        summary3->setCheckable(false);
        summary1 = new QEPushButton(charts);
        summary1->setObjectName(QStringLiteral("summary1"));
        summary1->setGeometry(QRect(10, 20, 91, 20));
        summary1->setCheckable(false);
        summary4 = new QEPushButton(charts);
        summary4->setObjectName(QStringLiteral("summary4"));
        summary4->setGeometry(QRect(100, 40, 101, 20));
        summary4->setCheckable(false);
        summary2 = new QEPushButton(charts);
        summary2->setObjectName(QStringLiteral("summary2"));
        summary2->setGeometry(QRect(100, 20, 101, 20));
        summary2->setCheckable(false);
        scan = new QGroupBox(centralwidget);
        scan->setObjectName(QStringLiteral("scan"));
        scan->setGeometry(QRect(10, 90, 511, 231));
        Mode = new QGroupBox(scan);
        Mode->setObjectName(QStringLiteral("Mode"));
        Mode->setGeometry(QRect(10, 20, 131, 201));
        label_3 = new QLabel(Mode);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(10, 40, 47, 13));
        archAna = new QEPushButton(Mode);
        archAna->setObjectName(QStringLiteral("archAna"));
        archAna->setGeometry(QRect(10, 140, 77, 20));
        arch50 = new QEPushButton(Mode);
        arch50->setObjectName(QStringLiteral("arch50"));
        arch50->setGeometry(QRect(10, 60, 77, 20));
        arch200 = new QEPushButton(Mode);
        arch200->setObjectName(QStringLiteral("arch200"));
        arch200->setGeometry(QRect(10, 100, 77, 20));
        label_6 = new QLabel(Mode);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(10, 120, 121, 16));
        archSS = new QECheckBox(Mode);
        archSS->setObjectName(QStringLiteral("archSS"));
        archSS->setGeometry(QRect(10, 170, 81, 21));
        archSS->setChecked(false);
        archSS->setWriteOnPress(false);
        archSS->setWriteOnClick(true);
        arch100 = new QEPushButton(Mode);
        arch100->setObjectName(QStringLiteral("arch100"));
        arch100->setGeometry(QRect(10, 80, 77, 20));
        archStop = new QEPushButton(Mode);
        archStop->setObjectName(QStringLiteral("archStop"));
        archStop->setGeometry(QRect(10, 20, 77, 20));
        RGA1 = new QGroupBox(scan);
        RGA1->setObjectName(QStringLiteral("RGA1"));
        RGA1->setGeometry(QRect(140, 20, 41, 201));
        qesimpleshape_13 = new QESimpleShape(RGA1);
        qesimpleshape_13->setObjectName(QStringLiteral("qesimpleshape_13"));
        qesimpleshape_13->setGeometry(QRect(10, 20, 16, 16));
        qesimpleshape_13->setFocusPolicy(Qt::NoFocus);
        qesimpleshape_13->setContextMenuPolicy(Qt::CustomContextMenu);
        qesimpleshape_13->setShape(QSimpleShape::ellipse);
        qesimpleshape_13->setProperty("colour0", QVariant(QColor(255, 255, 0)));
        qesimpleshape_13->setProperty("colour1", QVariant(QColor(255, 0, 0)));
        qesimpleshape_13->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        qesimpleshape_14 = new QESimpleShape(RGA1);
        qesimpleshape_14->setObjectName(QStringLiteral("qesimpleshape_14"));
        qesimpleshape_14->setGeometry(QRect(10, 140, 16, 16));
        qesimpleshape_14->setShape(QSimpleShape::ellipse);
        qesimpleshape_14->setProperty("colour7", QVariant(QColor(200, 200, 200)));
        qesimpleshape_14->setProperty("colour8", QVariant(QColor(0, 200, 0)));
        qesimpleshape_14->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        qesimpleshape_15 = new QESimpleShape(RGA1);
        qesimpleshape_15->setObjectName(QStringLiteral("qesimpleshape_15"));
        qesimpleshape_15->setGeometry(QRect(10, 170, 16, 16));
        qesimpleshape_15->setShape(QSimpleShape::ellipse);
        qesimpleshape_15->setProperty("colour0", QVariant(QColor(0, 255, 0)));
        qesimpleshape_15->setProperty("colour1", QVariant(QColor(200, 200, 200)));
        qesimpleshape_15->setProperty("flash0", QVariant(false));
        qesimpleshape_15->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        qesimpleshape_16 = new QESimpleShape(RGA1);
        qesimpleshape_16->setObjectName(QStringLiteral("qesimpleshape_16"));
        qesimpleshape_16->setGeometry(QRect(10, 60, 16, 16));
        qesimpleshape_16->setShape(QSimpleShape::ellipse);
        qesimpleshape_16->setProperty("colour3", QVariant(QColor(200, 200, 200)));
        qesimpleshape_16->setProperty("colour4", QVariant(QColor(200, 200, 200)));
        qesimpleshape_16->setProperty("colour5", QVariant(QColor(0, 200, 0)));
        qesimpleshape_16->setProperty("flash0", QVariant(false));
        qesimpleshape_16->setProperty("flash1", QVariant(false));
        qesimpleshape_16->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        qesimpleshape_17 = new QESimpleShape(RGA1);
        qesimpleshape_17->setObjectName(QStringLiteral("qesimpleshape_17"));
        qesimpleshape_17->setGeometry(QRect(10, 80, 16, 16));
        qesimpleshape_17->setShape(QSimpleShape::ellipse);
        qesimpleshape_17->setProperty("colour6", QVariant(QColor(0, 200, 0)));
        qesimpleshape_17->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        qesimpleshape_18 = new QESimpleShape(RGA1);
        qesimpleshape_18->setObjectName(QStringLiteral("qesimpleshape_18"));
        qesimpleshape_18->setGeometry(QRect(10, 100, 16, 16));
        qesimpleshape_18->setShape(QSimpleShape::ellipse);
        qesimpleshape_18->setProperty("colour7", QVariant(QColor(0, 200, 0)));
        qesimpleshape_18->setProperty("visible", QVariant(true));
        qesimpleshape_18->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        groupBox = new QGroupBox(scan);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(320, 20, 151, 201));
        qeanalogprogressbar = new QEAnalogProgressBar(groupBox);
        qeanalogprogressbar->setObjectName(QStringLiteral("qeanalogprogressbar"));
        qeanalogprogressbar->setGeometry(QRect(20, 20, 21, 171));
        qeanalogprogressbar->setOrientation(QEAnalogIndicator::Bottom_To_Top);
        qeanalogprogressbar_2 = new QEAnalogProgressBar(groupBox);
        qeanalogprogressbar_2->setObjectName(QStringLiteral("qeanalogprogressbar_2"));
        qeanalogprogressbar_2->setGeometry(QRect(50, 20, 21, 171));
        qeanalogprogressbar_2->setOrientation(QEAnalogIndicator::Bottom_To_Top);
        qeanalogprogressbar_3 = new QEAnalogProgressBar(groupBox);
        qeanalogprogressbar_3->setObjectName(QStringLiteral("qeanalogprogressbar_3"));
        qeanalogprogressbar_3->setGeometry(QRect(80, 20, 21, 171));
        qeanalogprogressbar_3->setOrientation(QEAnalogIndicator::Bottom_To_Top);
        qeanalogprogressbar_4 = new QEAnalogProgressBar(groupBox);
        qeanalogprogressbar_4->setObjectName(QStringLiteral("qeanalogprogressbar_4"));
        qeanalogprogressbar_4->setGeometry(QRect(110, 20, 21, 171));
        qeanalogprogressbar_4->setOrientation(QEAnalogIndicator::Bottom_To_Top);
        RGA1_2 = new QGroupBox(scan);
        RGA1_2->setObjectName(QStringLiteral("RGA1_2"));
        RGA1_2->setGeometry(QRect(180, 20, 41, 201));
        qesimpleshape_25 = new QESimpleShape(RGA1_2);
        qesimpleshape_25->setObjectName(QStringLiteral("qesimpleshape_25"));
        qesimpleshape_25->setGeometry(QRect(10, 20, 16, 16));
        qesimpleshape_25->setFocusPolicy(Qt::NoFocus);
        qesimpleshape_25->setContextMenuPolicy(Qt::CustomContextMenu);
        qesimpleshape_25->setShape(QSimpleShape::ellipse);
        qesimpleshape_25->setProperty("colour0", QVariant(QColor(255, 255, 0)));
        qesimpleshape_25->setProperty("colour1", QVariant(QColor(255, 0, 0)));
        qesimpleshape_25->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        qesimpleshape_26 = new QESimpleShape(RGA1_2);
        qesimpleshape_26->setObjectName(QStringLiteral("qesimpleshape_26"));
        qesimpleshape_26->setGeometry(QRect(10, 140, 16, 16));
        qesimpleshape_26->setShape(QSimpleShape::ellipse);
        qesimpleshape_26->setProperty("colour7", QVariant(QColor(200, 200, 200)));
        qesimpleshape_26->setProperty("colour8", QVariant(QColor(0, 200, 0)));
        qesimpleshape_26->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        qesimpleshape_27 = new QESimpleShape(RGA1_2);
        qesimpleshape_27->setObjectName(QStringLiteral("qesimpleshape_27"));
        qesimpleshape_27->setGeometry(QRect(10, 170, 16, 16));
        qesimpleshape_27->setShape(QSimpleShape::ellipse);
        qesimpleshape_27->setProperty("colour0", QVariant(QColor(0, 255, 0)));
        qesimpleshape_27->setProperty("colour1", QVariant(QColor(200, 200, 200)));
        qesimpleshape_27->setProperty("flash0", QVariant(false));
        qesimpleshape_27->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        qesimpleshape_28 = new QESimpleShape(RGA1_2);
        qesimpleshape_28->setObjectName(QStringLiteral("qesimpleshape_28"));
        qesimpleshape_28->setGeometry(QRect(10, 60, 16, 16));
        qesimpleshape_28->setShape(QSimpleShape::ellipse);
        qesimpleshape_28->setProperty("colour3", QVariant(QColor(200, 200, 200)));
        qesimpleshape_28->setProperty("colour4", QVariant(QColor(200, 200, 200)));
        qesimpleshape_28->setProperty("colour5", QVariant(QColor(0, 200, 0)));
        qesimpleshape_28->setProperty("flash0", QVariant(false));
        qesimpleshape_28->setProperty("flash1", QVariant(false));
        qesimpleshape_28->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        qesimpleshape_29 = new QESimpleShape(RGA1_2);
        qesimpleshape_29->setObjectName(QStringLiteral("qesimpleshape_29"));
        qesimpleshape_29->setGeometry(QRect(10, 80, 16, 16));
        qesimpleshape_29->setShape(QSimpleShape::ellipse);
        qesimpleshape_29->setProperty("colour6", QVariant(QColor(0, 200, 0)));
        qesimpleshape_29->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        qesimpleshape_30 = new QESimpleShape(RGA1_2);
        qesimpleshape_30->setObjectName(QStringLiteral("qesimpleshape_30"));
        qesimpleshape_30->setGeometry(QRect(10, 100, 16, 16));
        qesimpleshape_30->setShape(QSimpleShape::ellipse);
        qesimpleshape_30->setProperty("colour7", QVariant(QColor(0, 200, 0)));
        qesimpleshape_30->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        RGA1_3 = new QGroupBox(scan);
        RGA1_3->setObjectName(QStringLiteral("RGA1_3"));
        RGA1_3->setGeometry(QRect(260, 20, 41, 201));
        qesimpleshape_31 = new QESimpleShape(RGA1_3);
        qesimpleshape_31->setObjectName(QStringLiteral("qesimpleshape_31"));
        qesimpleshape_31->setGeometry(QRect(10, 20, 16, 16));
        qesimpleshape_31->setFocusPolicy(Qt::NoFocus);
        qesimpleshape_31->setContextMenuPolicy(Qt::CustomContextMenu);
        qesimpleshape_31->setShape(QSimpleShape::ellipse);
        qesimpleshape_31->setProperty("colour0", QVariant(QColor(255, 255, 0)));
        qesimpleshape_31->setProperty("colour1", QVariant(QColor(255, 0, 0)));
        qesimpleshape_31->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        qesimpleshape_32 = new QESimpleShape(RGA1_3);
        qesimpleshape_32->setObjectName(QStringLiteral("qesimpleshape_32"));
        qesimpleshape_32->setGeometry(QRect(10, 140, 16, 16));
        qesimpleshape_32->setShape(QSimpleShape::ellipse);
        qesimpleshape_32->setProperty("colour7", QVariant(QColor(200, 200, 200)));
        qesimpleshape_32->setProperty("colour8", QVariant(QColor(0, 200, 0)));
        qesimpleshape_32->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        qesimpleshape_33 = new QESimpleShape(RGA1_3);
        qesimpleshape_33->setObjectName(QStringLiteral("qesimpleshape_33"));
        qesimpleshape_33->setGeometry(QRect(10, 170, 16, 16));
        qesimpleshape_33->setShape(QSimpleShape::ellipse);
        qesimpleshape_33->setProperty("colour0", QVariant(QColor(0, 255, 0)));
        qesimpleshape_33->setProperty("colour1", QVariant(QColor(200, 200, 200)));
        qesimpleshape_33->setProperty("flash0", QVariant(false));
        qesimpleshape_33->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        qesimpleshape_34 = new QESimpleShape(RGA1_3);
        qesimpleshape_34->setObjectName(QStringLiteral("qesimpleshape_34"));
        qesimpleshape_34->setGeometry(QRect(10, 60, 16, 16));
        qesimpleshape_34->setShape(QSimpleShape::ellipse);
        qesimpleshape_34->setProperty("colour3", QVariant(QColor(200, 200, 200)));
        qesimpleshape_34->setProperty("colour4", QVariant(QColor(200, 200, 200)));
        qesimpleshape_34->setProperty("colour5", QVariant(QColor(0, 200, 0)));
        qesimpleshape_34->setProperty("flash0", QVariant(false));
        qesimpleshape_34->setProperty("flash1", QVariant(false));
        qesimpleshape_34->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        qesimpleshape_35 = new QESimpleShape(RGA1_3);
        qesimpleshape_35->setObjectName(QStringLiteral("qesimpleshape_35"));
        qesimpleshape_35->setGeometry(QRect(10, 80, 16, 16));
        qesimpleshape_35->setShape(QSimpleShape::ellipse);
        qesimpleshape_35->setProperty("colour6", QVariant(QColor(0, 200, 0)));
        qesimpleshape_35->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        qesimpleshape_36 = new QESimpleShape(RGA1_3);
        qesimpleshape_36->setObjectName(QStringLiteral("qesimpleshape_36"));
        qesimpleshape_36->setGeometry(QRect(10, 100, 16, 16));
        qesimpleshape_36->setShape(QSimpleShape::ellipse);
        qesimpleshape_36->setProperty("colour7", QVariant(QColor(0, 200, 0)));
        qesimpleshape_36->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        RGA1_4 = new QGroupBox(scan);
        RGA1_4->setObjectName(QStringLiteral("RGA1_4"));
        RGA1_4->setGeometry(QRect(220, 20, 41, 201));
        qesimpleshape_37 = new QESimpleShape(RGA1_4);
        qesimpleshape_37->setObjectName(QStringLiteral("qesimpleshape_37"));
        qesimpleshape_37->setGeometry(QRect(10, 20, 16, 16));
        qesimpleshape_37->setFocusPolicy(Qt::NoFocus);
        qesimpleshape_37->setContextMenuPolicy(Qt::CustomContextMenu);
        qesimpleshape_37->setShape(QSimpleShape::ellipse);
        qesimpleshape_37->setProperty("colour0", QVariant(QColor(255, 255, 0)));
        qesimpleshape_37->setProperty("colour1", QVariant(QColor(255, 0, 0)));
        qesimpleshape_37->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        qesimpleshape_38 = new QESimpleShape(RGA1_4);
        qesimpleshape_38->setObjectName(QStringLiteral("qesimpleshape_38"));
        qesimpleshape_38->setGeometry(QRect(10, 140, 16, 16));
        qesimpleshape_38->setShape(QSimpleShape::ellipse);
        qesimpleshape_38->setProperty("colour7", QVariant(QColor(200, 200, 200)));
        qesimpleshape_38->setProperty("colour8", QVariant(QColor(0, 200, 0)));
        qesimpleshape_38->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        qesimpleshape_39 = new QESimpleShape(RGA1_4);
        qesimpleshape_39->setObjectName(QStringLiteral("qesimpleshape_39"));
        qesimpleshape_39->setGeometry(QRect(10, 170, 16, 16));
        qesimpleshape_39->setShape(QSimpleShape::ellipse);
        qesimpleshape_39->setProperty("colour0", QVariant(QColor(0, 255, 0)));
        qesimpleshape_39->setProperty("colour1", QVariant(QColor(200, 200, 200)));
        qesimpleshape_39->setProperty("flash0", QVariant(false));
        qesimpleshape_39->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        qesimpleshape_40 = new QESimpleShape(RGA1_4);
        qesimpleshape_40->setObjectName(QStringLiteral("qesimpleshape_40"));
        qesimpleshape_40->setGeometry(QRect(10, 60, 16, 16));
        qesimpleshape_40->setShape(QSimpleShape::ellipse);
        qesimpleshape_40->setProperty("colour3", QVariant(QColor(200, 200, 200)));
        qesimpleshape_40->setProperty("colour4", QVariant(QColor(200, 200, 200)));
        qesimpleshape_40->setProperty("colour5", QVariant(QColor(0, 200, 0)));
        qesimpleshape_40->setProperty("flash0", QVariant(false));
        qesimpleshape_40->setProperty("flash1", QVariant(false));
        qesimpleshape_40->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        qesimpleshape_41 = new QESimpleShape(RGA1_4);
        qesimpleshape_41->setObjectName(QStringLiteral("qesimpleshape_41"));
        qesimpleshape_41->setGeometry(QRect(10, 80, 16, 16));
        qesimpleshape_41->setShape(QSimpleShape::ellipse);
        qesimpleshape_41->setProperty("colour6", QVariant(QColor(0, 200, 0)));
        qesimpleshape_41->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        qesimpleshape_42 = new QESimpleShape(RGA1_4);
        qesimpleshape_42->setObjectName(QStringLiteral("qesimpleshape_42"));
        qesimpleshape_42->setGeometry(QRect(10, 100, 16, 16));
        qesimpleshape_42->setShape(QSimpleShape::ellipse);
        qesimpleshape_42->setProperty("colour7", QVariant(QColor(0, 200, 0)));
        qesimpleshape_42->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        scan_2 = new QGroupBox(centralwidget);
        scan_2->setObjectName(QStringLiteral("scan_2"));
        scan_2->setGeometry(QRect(10, 330, 511, 161));
        archOn = new QESimpleShape(scan_2);
        archOn->setObjectName(QStringLiteral("archOn"));
        archOn->setGeometry(QRect(330, 10, 21, 21));
        archOn->setFocusPolicy(Qt::NoFocus);
        archOn->setContextMenuPolicy(Qt::CustomContextMenu);
        archOn->setShape(QSimpleShape::ellipse);
        archOn->setProperty("colour0", QVariant(QColor(200, 200, 200)));
        archOn->setProperty("colour1", QVariant(QColor(0, 255, 0)));
        archOn->setProperty("colour2", QVariant(QColor(255, 0, 0)));
        archOn->setProperty("colour3", QVariant(QColor(0, 255, 0)));
        archOn->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        archStop2 = new QEPushButton(scan_2);
        archStop2->setObjectName(QStringLiteral("archStop2"));
        archStop2->setGeometry(QRect(10, 100, 81, 20));
        archStart = new QEPushButton(scan_2);
        archStart->setObjectName(QStringLiteral("archStart"));
        archStart->setGeometry(QRect(10, 20, 81, 71));
        archAnaOn = new QESimpleShape(scan_2);
        archAnaOn->setObjectName(QStringLiteral("archAnaOn"));
        archAnaOn->setGeometry(QRect(440, 10, 21, 21));
        archAnaOn->setFocusPolicy(Qt::NoFocus);
        archAnaOn->setContextMenuPolicy(Qt::CustomContextMenu);
        archAnaOn->setShape(QSimpleShape::ellipse);
        archAnaOn->setProperty("colour0", QVariant(QColor(200, 200, 200)));
        archAnaOn->setProperty("colour1", QVariant(QColor(205, 200, 200)));
        archAnaOn->setProperty("colour2", QVariant(QColor(0, 255, 0)));
        archAnaOn->setProperty("colour3", QVariant(QColor(0, 255, 0)));
        archAnaOn->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        archTime = new QELabel(scan_2);
        archTime->setObjectName(QStringLiteral("archTime"));
        archTime->setGeometry(QRect(240, 40, 31, 21));
        label_7 = new QLabel(scan_2);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(100, 10, 81, 16));
        label_9 = new QLabel(scan_2);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(100, 40, 131, 20));
        label_10 = new QLabel(scan_2);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(360, 10, 71, 20));
        label_11 = new QLabel(scan_2);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(100, 70, 91, 20));
        archFil = new QESimpleShape(scan_2);
        archFil->setObjectName(QStringLiteral("archFil"));
        archFil->setGeometry(QRect(210, 70, 21, 21));
        archFil->setFocusPolicy(Qt::NoFocus);
        archFil->setContextMenuPolicy(Qt::CustomContextMenu);
        archFil->setShape(QSimpleShape::ellipse);
        archFil->setProperty("colour0", QVariant(QColor(200, 200, 200)));
        archFil->setProperty("colour1", QVariant(QColor(200, 200, 200)));
        archFil->setProperty("colour2", QVariant(QColor(0, 136, 255)));
        archFil->setProperty("colour3", QVariant(QColor(255, 247, 0)));
        archFil->setProperty("colour4", QVariant(QColor(200, 164, 32)));
        archFil->setProperty("colour6", QVariant(QColor(200, 0, 0)));
        archFil->setProperty("colour15", QVariant(QColor(200, 0, 0)));
        archFil->setProperty("flash15", QVariant(false));
        archFil->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        label_12 = new QLabel(scan_2);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(250, 70, 81, 20));
        archScan = new QESimpleShape(scan_2);
        archScan->setObjectName(QStringLiteral("archScan"));
        archScan->setGeometry(QRect(330, 70, 21, 21));
        archScan->setFocusPolicy(Qt::NoFocus);
        archScan->setContextMenuPolicy(Qt::CustomContextMenu);
        archScan->setShape(QSimpleShape::ellipse);
        archScan->setProperty("colour0", QVariant(QColor(200, 200, 200)));
        archScan->setProperty("colour1", QVariant(QColor(205, 200, 200)));
        archScan->setProperty("colour3", QVariant(QColor(0, 255, 0)));
        archScan->setProperty("colour15", QVariant(QColor(200, 0, 0)));
        archScan->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        lablex = new QLabel(scan_2);
        lablex->setObjectName(QStringLiteral("lablex"));
        lablex->setGeometry(QRect(100, 100, 101, 20));
        archFailC = new QELabel(scan_2);
        archFailC->setObjectName(QStringLiteral("archFailC"));
        archFailC->setGeometry(QRect(440, 40, 31, 21));
        archFailR = new QEPushButton(scan_2);
        archFailR->setObjectName(QStringLiteral("archFailR"));
        archFailR->setGeometry(QRect(360, 100, 81, 20));
        label_14 = new QLabel(scan_2);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(360, 40, 61, 20));
        archTO = new QELabel(scan_2);
        archTO->setObjectName(QStringLiteral("archTO"));
        archTO->setGeometry(QRect(440, 70, 31, 21));
        label_15 = new QLabel(scan_2);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(360, 70, 81, 20));
        archTOVal = new QELineEdit(scan_2);
        archTOVal->setObjectName(QStringLiteral("archTOVal"));
        archTOVal->setGeometry(QRect(210, 100, 61, 20));
        archDT = new QELineEdit(scan_2);
        archDT->setObjectName(QStringLiteral("archDT"));
        archDT->setGeometry(QRect(180, 10, 131, 20));
        archDT->setProperty("format", QVariant(QELineEdit::Default));
        mainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(mainWindow);
        menubar->setObjectName(QStringLiteral("menubar"));
        menubar->setGeometry(QRect(0, 0, 543, 21));
        mainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(mainWindow);
        statusbar->setObjectName(QStringLiteral("statusbar"));
        mainWindow->setStatusBar(statusbar);

        retranslateUi(mainWindow);

        QMetaObject::connectSlotsByName(mainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *mainWindow)
    {
        mainWindow->setWindowTitle(QApplication::translate("mainWindow", "MainWindow", 0));
        charts->setTitle(QApplication::translate("mainWindow", "RGA plots", 0));
        barscan->setText(QApplication::translate("mainWindow", "RGA Bar Chart", 0));
        barscan->setProperty("variable", QVariant(QString()));
        barscan->setProperty("altReadbackVariable", QVariant(QString()));
        barscan->setPressText(QApplication::translate("mainWindow", "1", 0));
        barscan->setProperty("guiFile", QVariant(QApplication::translate("mainWindow", "barchart.ui", 0)));
        barstrip->setText(QApplication::translate("mainWindow", "RGA Strip chart", 0));
        barstrip->setProperty("variable", QVariant(QString()));
        barstrip->setProperty("altReadbackVariable", QVariant(QString()));
        barstrip->setProperty("variableSubstitutions", QVariant(QString()));
        barstrip->setPressText(QApplication::translate("mainWindow", "1", 0));
        barstrip->setProperty("guiFile", QVariant(QApplication::translate("mainWindow", "mv2_main_bar.ui", 0)));
        anascan->setText(QApplication::translate("mainWindow", "RGA Analog Scan", 0));
        anascan->setProperty("variable", QVariant(QString()));
        anascan->setProperty("altReadbackVariable", QVariant(QString()));
        anascan->setPressText(QApplication::translate("mainWindow", "1", 0));
        anascan->setProperty("guiFile", QVariant(QApplication::translate("mainWindow", "barchart_ana.ui", 0)));
        summary3->setText(QApplication::translate("mainWindow", "RGA summary 3", 0));
        summary3->setProperty("variable", QVariant(QString()));
        summary3->setProperty("altReadbackVariable", QVariant(QString()));
        summary3->setProperty("variableSubstitutions", QVariant(QString()));
        summary3->setPressText(QApplication::translate("mainWindow", "3", 0));
        summary3->setClickText(QApplication::translate("mainWindow", "3", 0));
        summary3->setProperty("guiFile", QVariant(QApplication::translate("mainWindow", "mv2_main_bar.ui", 0)));
        summary1->setText(QApplication::translate("mainWindow", "RGA summary 1", 0));
        summary1->setProperty("variable", QVariant(QString()));
        summary1->setProperty("altReadbackVariable", QVariant(QString()));
        summary1->setProperty("variableSubstitutions", QVariant(QString()));
        summary1->setPressText(QApplication::translate("mainWindow", "1", 0));
        summary1->setProperty("guiFile", QVariant(QApplication::translate("mainWindow", "mv2_main_bar.ui", 0)));
        summary4->setText(QApplication::translate("mainWindow", "RGA Summary 4", 0));
        summary4->setProperty("variable", QVariant(QString()));
        summary4->setProperty("altReadbackVariable", QVariant(QString()));
        summary4->setProperty("variableSubstitutions", QVariant(QString()));
        summary4->setPressText(QApplication::translate("mainWindow", "4", 0));
        summary4->setClickText(QApplication::translate("mainWindow", "4", 0));
        summary4->setProperty("guiFile", QVariant(QApplication::translate("mainWindow", "mv2_main_bar.ui", 0)));
        summary2->setText(QApplication::translate("mainWindow", "RGA Summary 2", 0));
        summary2->setProperty("variable", QVariant(QString()));
        summary2->setProperty("altReadbackVariable", QVariant(QString()));
        summary2->setProperty("variableSubstitutions", QVariant(QString()));
        summary2->setPressText(QApplication::translate("mainWindow", "2", 0));
        summary2->setClickText(QApplication::translate("mainWindow", "2", 0));
        summary2->setProperty("guiFile", QVariant(QApplication::translate("mainWindow", "mv2_main_bar.ui", 0)));
        scan->setTitle(QApplication::translate("mainWindow", "Scan", 0));
        Mode->setTitle(QApplication::translate("mainWindow", "Set All:", 0));
        label_3->setText(QApplication::translate("mainWindow", "Bar Chart", 0));
        archAna->setText(QApplication::translate("mainWindow", "1-200", 0));
        archAna->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(GRGA):CON", 0)));
        archAna->setProperty("altReadbackVariable", QVariant(QString()));
        archAna->setProperty("variableSubstitutions", QVariant(QString()));
        archAna->setClickText(QApplication::translate("mainWindow", "8", 0));
        archAna->setClickCheckedText(QString());
        arch50->setText(QApplication::translate("mainWindow", "1-50", 0));
        arch50->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(GRGA):CON", 0)));
        arch50->setProperty("altReadbackVariable", QVariant(QString()));
        arch50->setProperty("variableSubstitutions", QVariant(QString()));
        arch50->setClickText(QApplication::translate("mainWindow", "5", 0));
        arch50->setClickCheckedText(QString());
        arch200->setText(QApplication::translate("mainWindow", "1-200", 0));
        arch200->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(GRGA):CON", 0)));
        arch200->setProperty("altReadbackVariable", QVariant(QString()));
        arch200->setProperty("variableSubstitutions", QVariant(QApplication::translate("mainWindow", ")", 0)));
        arch200->setClickText(QApplication::translate("mainWindow", "7", 0));
        arch200->setClickCheckedText(QString());
        label_6->setText(QApplication::translate("mainWindow", "Analog Scan (32 ppp)", 0));
        archSS->setText(QApplication::translate("mainWindow", "Single Scan", 0));
        archSS->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(GRGA):SETSCAN", 0)));
        archSS->setPressText(QApplication::translate("mainWindow", "0", 0));
        archSS->setReleaseText(QApplication::translate("mainWindow", "1", 0));
        archSS->setClickText(QApplication::translate("mainWindow", "1", 0));
        archSS->setClickCheckedText(QApplication::translate("mainWindow", "0", 0));
        arch100->setText(QApplication::translate("mainWindow", "1-100", 0));
        arch100->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(GRGA):CON", 0)));
        arch100->setProperty("altReadbackVariable", QVariant(QString()));
        arch100->setProperty("variableSubstitutions", QVariant(QString()));
        arch100->setClickText(QApplication::translate("mainWindow", "6", 0));
        arch100->setClickCheckedText(QString());
        archStop->setText(QApplication::translate("mainWindow", "Stop", 0));
        archStop->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(GRGA):CON", 0)));
        archStop->setProperty("altReadbackVariable", QVariant(QString()));
        archStop->setProperty("variableSubstitutions", QVariant(QString()));
        archStop->setClickText(QApplication::translate("mainWindow", "0", 0));
        archStop->setClickCheckedText(QString());
        RGA1->setTitle(QApplication::translate("mainWindow", "RG1", 0));
        qesimpleshape_13->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):HEADSTA", 0)));
        qesimpleshape_13->setProperty("variableSubstitutions", QVariant(QString()));
        qesimpleshape_14->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):HEADSTA", 0)));
        qesimpleshape_15->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):SCAN", 0)));
        qesimpleshape_16->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):HEADSTA", 0)));
        qesimpleshape_17->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):HEADSTA", 0)));
        qesimpleshape_18->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):HEADSTA", 0)));
        groupBox->setTitle(QApplication::translate("mainWindow", "Percent Scanned: 1-4", 0));
        qeanalogprogressbar->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA1):PERSCANNED", 0)));
        qeanalogprogressbar_2->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA2):PERSCANNED", 0)));
        qeanalogprogressbar_3->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA3):PERSCANNED", 0)));
        qeanalogprogressbar_4->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA4):PERSCANNED", 0)));
        RGA1_2->setTitle(QApplication::translate("mainWindow", "RG2", 0));
        qesimpleshape_25->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA2):HEADSTA", 0)));
        qesimpleshape_25->setProperty("variableSubstitutions", QVariant(QString()));
        qesimpleshape_26->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA2):HEADSTA", 0)));
        qesimpleshape_27->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA2):SCAN", 0)));
        qesimpleshape_28->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA2):HEADSTA", 0)));
        qesimpleshape_29->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA2):HEADSTA", 0)));
        qesimpleshape_30->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA2):HEADSTA", 0)));
        RGA1_3->setTitle(QApplication::translate("mainWindow", "RGA4", 0));
        qesimpleshape_31->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA4):HEADSTA", 0)));
        qesimpleshape_31->setProperty("variableSubstitutions", QVariant(QString()));
        qesimpleshape_32->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA4):HEADSTA", 0)));
        qesimpleshape_33->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA4):SCAN", 0)));
        qesimpleshape_34->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA4):HEADSTA", 0)));
        qesimpleshape_35->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA4):HEADSTA", 0)));
        qesimpleshape_36->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA4):HEADSTA", 0)));
        RGA1_4->setTitle(QApplication::translate("mainWindow", "RGA3", 0));
        qesimpleshape_37->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA3):HEADSTA", 0)));
        qesimpleshape_37->setProperty("variableSubstitutions", QVariant(QString()));
        qesimpleshape_38->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA3):HEADSTA", 0)));
        qesimpleshape_39->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA3):SCAN", 0)));
        qesimpleshape_40->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA3):HEADSTA", 0)));
        qesimpleshape_41->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA3):HEADSTA", 0)));
        qesimpleshape_42->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(RGA3):HEADSTA", 0)));
        scan_2->setTitle(QApplication::translate("mainWindow", "Archive", 0));
        archOn->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(GRGA):MODE", 0)));
        archOn->setProperty("variableSubstitutions", QVariant(QString()));
        archStop2->setText(QApplication::translate("mainWindow", "Stop", 0));
        archStop2->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(GRGA):ARCH", 0)));
        archStop2->setProperty("altReadbackVariable", QVariant(QString()));
        archStop2->setProperty("variableSubstitutions", QVariant(QString()));
        archStop2->setClickText(QApplication::translate("mainWindow", "0", 0));
        archStop2->setClickCheckedText(QString());
        archStart->setText(QApplication::translate("mainWindow", "Start", 0));
        archStart->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(GRGA):ARCH", 0)));
        archStart->setProperty("altReadbackVariable", QVariant(QString()));
        archStart->setProperty("variableSubstitutions", QVariant(QString()));
        archStart->setClickText(QApplication::translate("mainWindow", "1", 0));
        archStart->setClickCheckedText(QString());
        archAnaOn->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(GRGA):MODE", 0)));
        archAnaOn->setProperty("variableSubstitutions", QVariant(QString()));
        archTime->setProperty("variable", QVariant(QApplication::translate("mainWindow", "GRGA:ANAT", 0)));
        label_7->setText(QApplication::translate("mainWindow", "Archiver on/off", 0));
        label_9->setText(QApplication::translate("mainWindow", "Seconds until Analog scan", 0));
        label_10->setText(QApplication::translate("mainWindow", "Analog scan", 0));
        label_11->setText(QApplication::translate("mainWindow", "Filament mismatch", 0));
        archFil->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(GRGA):MODE", 0)));
        archFil->setProperty("variableSubstitutions", QVariant(QString()));
        label_12->setText(QApplication::translate("mainWindow", "Scan mismatch", 0));
        archScan->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(GRGA):MODE", 0)));
        archScan->setProperty("variableSubstitutions", QVariant(QString()));
        lablex->setText(QApplication::translate("mainWindow", "Analog timout secs", 0));
        archFailC->setProperty("variable", QVariant(QApplication::translate("mainWindow", "GRGA:ANAT", 0)));
        archFailR->setText(QApplication::translate("mainWindow", "Reset", 0));
        archFailR->setProperty("variable", QVariant(QApplication::translate("mainWindow", "$(GRGA):ARCH", 0)));
        archFailR->setProperty("altReadbackVariable", QVariant(QString()));
        archFailR->setProperty("variableSubstitutions", QVariant(QString()));
        archFailR->setClickText(QApplication::translate("mainWindow", "0", 0));
        archFailR->setClickCheckedText(QString());
        label_14->setText(QApplication::translate("mainWindow", "Analog fail", 0));
        archTO->setProperty("variable", QVariant(QApplication::translate("mainWindow", "GRGA:ANAT", 0)));
        label_15->setText(QApplication::translate("mainWindow", "Analog timouts", 0));
    } // retranslateUi

};

namespace Ui {
    class mainWindow: public Ui_mainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MV2_EPICSDISPLAY_H
