/********************************************************************************
** Form generated from reading UI file 'mv2_rgaDisplay.ui'
**
** Created by: Qt User Interface Compiler version 5.5.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MV2_RGADISPLAY_H
#define UI_MV2_RGADISPLAY_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>
#include "QBitStatus.h"
#include "QEBitStatus.h"
#include "QECheckBox.h"
#include "QELabel.h"
#include "QEPushButton.h"
#include "QESimpleShape.h"
#include "QSimpleShape.h"

QT_BEGIN_NAMESPACE

class Ui_rgaWindow
{
public:
    QWidget *centralwidget;
    QGroupBox *status;
    QGroupBox *Filament;
    QEBitStatus *qebitstatus_4;
    QLabel *label_4;
    QLabel *label;
    QEBitStatus *qebitstatus;
    QLabel *label_2;
    QEBitStatus *qebitstatus_2;
    QELabel *qelabel;
    QEPushButton *qepushbutton_2;
    QEPushButton *qepushbutton;
    QGroupBox *RGAstat;
    QEBitStatus *qebitstatus_19;
    QLabel *label_5;
    QLabel *label_25;
    QELabel *qelabel_51;
    QGroupBox *Mode_2;
    QLabel *label_7;
    QEPushButton *qepushbutton_35;
    QEPushButton *qebutton50_2;
    QEPushButton *qebutton200_2;
    QLabel *label_8;
    QECheckBox *qecheckbox_4;
    QEPushButton *qebutton100_2;
    QEPushButton *qepushbutton_31;
    QGroupBox *Mode_3;
    QEPushButton *qebutton50_4;
    QEPushButton *qebutton200_4;
    QEPushButton *qebutton100_4;
    QEPushButton *qepushbutton_33;
    QESimpleShape *qesimpleshape_19;
    QESimpleShape *qesimpleshape_20;
    QESimpleShape *qesimpleshape_21;
    QESimpleShape *qesimpleshape_22;
    QGroupBox *status_2;
    QGroupBox *Filament_3;
    QEBitStatus *qebitstatus_7;
    QLabel *label_17;
    QLabel *label_18;
    QEBitStatus *qebitstatus_8;
    QLabel *label_19;
    QEBitStatus *qebitstatus_9;
    QELabel *qelabel_3;
    QEPushButton *qepushbutton_5;
    QEPushButton *qepushbutton_6;
    QGroupBox *RGAstat_3;
    QEBitStatus *qebitstatus_21;
    QLabel *label_20;
    QLabel *label_27;
    QELabel *qelabel_53;
    QGroupBox *Mode_6;
    QLabel *label_21;
    QEPushButton *qepushbutton_40;
    QEPushButton *qebutton50_7;
    QEPushButton *qebutton200_7;
    QLabel *label_22;
    QECheckBox *qecheckbox_7;
    QEPushButton *qebutton100_7;
    QEPushButton *qepushbutton_41;
    QGroupBox *Mode_7;
    QEPushButton *qebutton50_8;
    QEPushButton *qebutton200_8;
    QEPushButton *qebutton100_8;
    QEPushButton *qepushbutton_42;
    QESimpleShape *qesimpleshape_31;
    QESimpleShape *qesimpleshape_32;
    QESimpleShape *qesimpleshape_33;
    QESimpleShape *qesimpleshape_34;
    QGroupBox *status_3;
    QGroupBox *Filament_4;
    QEBitStatus *qebitstatus_10;
    QLabel *label_23;
    QLabel *label_24;
    QEBitStatus *qebitstatus_11;
    QLabel *label_28;
    QEBitStatus *qebitstatus_12;
    QELabel *qelabel_4;
    QEPushButton *qepushbutton_7;
    QEPushButton *qepushbutton_8;
    QGroupBox *RGAstat_4;
    QEBitStatus *qebitstatus_22;
    QLabel *label_29;
    QLabel *label_30;
    QELabel *qelabel_54;
    QGroupBox *Mode_8;
    QLabel *label_31;
    QEPushButton *qepushbutton_43;
    QEPushButton *qebutton50_9;
    QEPushButton *qebutton200_9;
    QLabel *label_32;
    QECheckBox *qecheckbox_8;
    QEPushButton *qebutton100_9;
    QEPushButton *qepushbutton_44;
    QGroupBox *Mode_9;
    QEPushButton *qebutton50_10;
    QEPushButton *qebutton200_10;
    QEPushButton *qebutton100_10;
    QEPushButton *qepushbutton_45;
    QESimpleShape *qesimpleshape_23;
    QESimpleShape *qesimpleshape_24;
    QESimpleShape *qesimpleshape_25;
    QESimpleShape *qesimpleshape_26;
    QGroupBox *status_4;
    QGroupBox *Filament_5;
    QEBitStatus *qebitstatus_13;
    QLabel *label_33;
    QLabel *label_34;
    QEBitStatus *qebitstatus_14;
    QLabel *label_35;
    QEBitStatus *qebitstatus_15;
    QELabel *qelabel_5;
    QEPushButton *qepushbutton_9;
    QEPushButton *qepushbutton_10;
    QGroupBox *RGAstat_5;
    QEBitStatus *qebitstatus_23;
    QLabel *label_36;
    QLabel *label_37;
    QELabel *qelabel_55;
    QGroupBox *Mode_10;
    QLabel *label_38;
    QEPushButton *qepushbutton_46;
    QEPushButton *qebutton50_11;
    QEPushButton *qebutton200_11;
    QLabel *label_39;
    QECheckBox *qecheckbox_9;
    QEPushButton *qebutton100_11;
    QEPushButton *qepushbutton_47;
    QGroupBox *Mode_11;
    QEPushButton *qebutton50_12;
    QEPushButton *qebutton200_12;
    QEPushButton *qebutton100_12;
    QEPushButton *qepushbutton_48;
    QESimpleShape *qesimpleshape_27;
    QESimpleShape *qesimpleshape_28;
    QESimpleShape *qesimpleshape_29;
    QESimpleShape *qesimpleshape_30;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *rgaWindow)
    {
        if (rgaWindow->objectName().isEmpty())
            rgaWindow->setObjectName(QStringLiteral("rgaWindow"));
        rgaWindow->resize(529, 688);
        centralwidget = new QWidget(rgaWindow);
        centralwidget->setObjectName(QStringLiteral("centralwidget"));
        status = new QGroupBox(centralwidget);
        status->setObjectName(QStringLiteral("status"));
        status->setGeometry(QRect(0, 10, 511, 161));
        Filament = new QGroupBox(status);
        Filament->setObjectName(QStringLiteral("Filament"));
        Filament->setGeometry(QRect(10, 10, 181, 81));
        qebitstatus_4 = new QEBitStatus(Filament);
        qebitstatus_4->setObjectName(QStringLiteral("qebitstatus_4"));
        qebitstatus_4->setGeometry(QRect(150, 30, 31, 21));
        qebitstatus_4->setNumberOfBits(1);
        qebitstatus_4->setShift(3);
        qebitstatus_4->setShape(QBitStatus::Circle);
        qebitstatus_4->setInvalidColour(QColor(255, 0, 0));
        qebitstatus_4->setOnColour(QColor(255, 0, 4));
        qebitstatus_4->setOffColour(QColor(255, 255, 255));
        label_4 = new QLabel(Filament);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(160, 10, 16, 21));
        QFont font;
        font.setPointSize(6);
        label_4->setFont(font);
        label = new QLabel(Filament);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(90, 10, 31, 21));
        label->setFont(font);
        qebitstatus = new QEBitStatus(Filament);
        qebitstatus->setObjectName(QStringLiteral("qebitstatus"));
        qebitstatus->setGeometry(QRect(90, 30, 31, 21));
        qebitstatus->setNumberOfBits(1);
        qebitstatus->setShape(QBitStatus::Circle);
        qebitstatus->setInvalidColour(QColor(255, 0, 0));
        qebitstatus->setOffColour(QColor(255, 255, 255));
        label_2 = new QLabel(Filament);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(120, 10, 41, 21));
        label_2->setFont(font);
        qebitstatus_2 = new QEBitStatus(Filament);
        qebitstatus_2->setObjectName(QStringLiteral("qebitstatus_2"));
        qebitstatus_2->setGeometry(QRect(120, 30, 31, 21));
        qebitstatus_2->setNumberOfBits(1);
        qebitstatus_2->setShift(1);
        qebitstatus_2->setShape(QBitStatus::Circle);
        qebitstatus_2->setInvalidColour(QColor(255, 0, 0));
        qebitstatus_2->setOnColour(QColor(255, 255, 0));
        qebitstatus_2->setOffColour(QColor(255, 255, 255));
        qelabel = new QELabel(Filament);
        qelabel->setObjectName(QStringLiteral("qelabel"));
        qelabel->setGeometry(QRect(100, 60, 61, 16));
        QFont font1;
        font1.setBold(false);
        font1.setWeight(50);
        qelabel->setFont(font1);
        qepushbutton_2 = new QEPushButton(Filament);
        qepushbutton_2->setObjectName(QStringLiteral("qepushbutton_2"));
        qepushbutton_2->setGeometry(QRect(10, 50, 81, 23));
        qepushbutton_2->setCheckable(true);
        qepushbutton = new QEPushButton(Filament);
        qepushbutton->setObjectName(QStringLiteral("qepushbutton"));
        qepushbutton->setGeometry(QRect(10, 30, 81, 21));
        qepushbutton->setCheckable(true);
        RGAstat = new QGroupBox(status);
        RGAstat->setObjectName(QStringLiteral("RGAstat"));
        RGAstat->setGeometry(QRect(10, 90, 181, 61));
        qebitstatus_19 = new QEBitStatus(RGAstat);
        qebitstatus_19->setObjectName(QStringLiteral("qebitstatus_19"));
        qebitstatus_19->setGeometry(QRect(20, 30, 31, 21));
        qebitstatus_19->setNumberOfBits(1);
        qebitstatus_19->setShape(QBitStatus::Circle);
        qebitstatus_19->setInvalidColour(QColor(255, 0, 0));
        qebitstatus_19->setOnColour(QColor(255, 0, 0));
        qebitstatus_19->setOffColour(QColor(0, 255, 0));
        label_5 = new QLabel(RGAstat);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(20, 10, 51, 21));
        label_5->setFont(font);
        label_25 = new QLabel(RGAstat);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(80, 10, 31, 21));
        label_25->setFont(font);
        qelabel_51 = new QELabel(RGAstat);
        qelabel_51->setObjectName(QStringLiteral("qelabel_51"));
        qelabel_51->setGeometry(QRect(70, 30, 111, 21));
        QFont font2;
        font2.setPointSize(12);
        font2.setBold(false);
        font2.setWeight(50);
        qelabel_51->setFont(font2);
        Mode_2 = new QGroupBox(status);
        Mode_2->setObjectName(QStringLiteral("Mode_2"));
        Mode_2->setGeometry(QRect(190, 10, 111, 141));
        label_7 = new QLabel(Mode_2);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(10, 40, 47, 13));
        qepushbutton_35 = new QEPushButton(Mode_2);
        qepushbutton_35->setObjectName(QStringLiteral("qepushbutton_35"));
        qepushbutton_35->setGeometry(QRect(60, 60, 41, 20));
        qebutton50_2 = new QEPushButton(Mode_2);
        qebutton50_2->setObjectName(QStringLiteral("qebutton50_2"));
        qebutton50_2->setGeometry(QRect(10, 60, 41, 20));
        qebutton200_2 = new QEPushButton(Mode_2);
        qebutton200_2->setObjectName(QStringLiteral("qebutton200_2"));
        qebutton200_2->setGeometry(QRect(10, 100, 41, 20));
        label_8 = new QLabel(Mode_2);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(70, 40, 41, 16));
        qecheckbox_4 = new QECheckBox(Mode_2);
        qecheckbox_4->setObjectName(QStringLiteral("qecheckbox_4"));
        qecheckbox_4->setGeometry(QRect(10, 120, 81, 21));
        qecheckbox_4->setChecked(false);
        qecheckbox_4->setWriteOnPress(false);
        qecheckbox_4->setWriteOnClick(true);
        qebutton100_2 = new QEPushButton(Mode_2);
        qebutton100_2->setObjectName(QStringLiteral("qebutton100_2"));
        qebutton100_2->setGeometry(QRect(10, 80, 41, 20));
        qepushbutton_31 = new QEPushButton(Mode_2);
        qepushbutton_31->setObjectName(QStringLiteral("qepushbutton_31"));
        qepushbutton_31->setGeometry(QRect(10, 20, 41, 21));
        Mode_3 = new QGroupBox(status);
        Mode_3->setObjectName(QStringLiteral("Mode_3"));
        Mode_3->setGeometry(QRect(310, 10, 111, 141));
        qebutton50_4 = new QEPushButton(Mode_3);
        qebutton50_4->setObjectName(QStringLiteral("qebutton50_4"));
        qebutton50_4->setGeometry(QRect(10, 60, 41, 20));
        qebutton200_4 = new QEPushButton(Mode_3);
        qebutton200_4->setObjectName(QStringLiteral("qebutton200_4"));
        qebutton200_4->setGeometry(QRect(10, 100, 41, 20));
        qebutton100_4 = new QEPushButton(Mode_3);
        qebutton100_4->setObjectName(QStringLiteral("qebutton100_4"));
        qebutton100_4->setGeometry(QRect(10, 80, 41, 20));
        qepushbutton_33 = new QEPushButton(Mode_3);
        qepushbutton_33->setObjectName(QStringLiteral("qepushbutton_33"));
        qepushbutton_33->setGeometry(QRect(10, 20, 61, 21));
        qesimpleshape_19 = new QESimpleShape(Mode_3);
        qesimpleshape_19->setObjectName(QStringLiteral("qesimpleshape_19"));
        qesimpleshape_19->setGeometry(QRect(90, 100, 16, 16));
        qesimpleshape_19->setShape(QSimpleShape::ellipse);
        qesimpleshape_19->setProperty("colour3", QVariant(QColor(0, 255, 0)));
        qesimpleshape_19->setProperty("colour7", QVariant(QColor(200, 200, 200)));
        qesimpleshape_19->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        qesimpleshape_20 = new QESimpleShape(Mode_3);
        qesimpleshape_20->setObjectName(QStringLiteral("qesimpleshape_20"));
        qesimpleshape_20->setGeometry(QRect(90, 20, 16, 16));
        qesimpleshape_20->setFocusPolicy(Qt::NoFocus);
        qesimpleshape_20->setContextMenuPolicy(Qt::CustomContextMenu);
        qesimpleshape_20->setShape(QSimpleShape::ellipse);
        qesimpleshape_20->setProperty("colour0", QVariant(QColor(0, 255, 0)));
        qesimpleshape_20->setProperty("colour1", QVariant(QColor(200, 200, 200)));
        qesimpleshape_20->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        qesimpleshape_21 = new QESimpleShape(Mode_3);
        qesimpleshape_21->setObjectName(QStringLiteral("qesimpleshape_21"));
        qesimpleshape_21->setGeometry(QRect(90, 80, 16, 16));
        qesimpleshape_21->setShape(QSimpleShape::ellipse);
        qesimpleshape_21->setProperty("colour2", QVariant(QColor(0, 255, 0)));
        qesimpleshape_21->setProperty("colour6", QVariant(QColor(200, 200, 200)));
        qesimpleshape_21->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        qesimpleshape_22 = new QESimpleShape(Mode_3);
        qesimpleshape_22->setObjectName(QStringLiteral("qesimpleshape_22"));
        qesimpleshape_22->setGeometry(QRect(90, 60, 16, 16));
        qesimpleshape_22->setShape(QSimpleShape::ellipse);
        qesimpleshape_22->setProperty("colour1", QVariant(QColor(0, 255, 0)));
        qesimpleshape_22->setProperty("colour3", QVariant(QColor(200, 200, 200)));
        qesimpleshape_22->setProperty("colour4", QVariant(QColor(200, 200, 200)));
        qesimpleshape_22->setProperty("colour5", QVariant(QColor(200, 200, 200)));
        qesimpleshape_22->setProperty("flash0", QVariant(false));
        qesimpleshape_22->setProperty("flash1", QVariant(false));
        qesimpleshape_22->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        status_2 = new QGroupBox(centralwidget);
        status_2->setObjectName(QStringLiteral("status_2"));
        status_2->setGeometry(QRect(0, 490, 511, 161));
        Filament_3 = new QGroupBox(status_2);
        Filament_3->setObjectName(QStringLiteral("Filament_3"));
        Filament_3->setGeometry(QRect(10, 10, 181, 81));
        qebitstatus_7 = new QEBitStatus(Filament_3);
        qebitstatus_7->setObjectName(QStringLiteral("qebitstatus_7"));
        qebitstatus_7->setGeometry(QRect(150, 30, 31, 21));
        qebitstatus_7->setNumberOfBits(1);
        qebitstatus_7->setShift(3);
        qebitstatus_7->setShape(QBitStatus::Circle);
        qebitstatus_7->setInvalidColour(QColor(255, 0, 0));
        qebitstatus_7->setOnColour(QColor(255, 0, 4));
        qebitstatus_7->setOffColour(QColor(255, 255, 255));
        label_17 = new QLabel(Filament_3);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(160, 10, 16, 21));
        label_17->setFont(font);
        label_18 = new QLabel(Filament_3);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(90, 10, 31, 21));
        label_18->setFont(font);
        qebitstatus_8 = new QEBitStatus(Filament_3);
        qebitstatus_8->setObjectName(QStringLiteral("qebitstatus_8"));
        qebitstatus_8->setGeometry(QRect(90, 30, 31, 21));
        qebitstatus_8->setNumberOfBits(1);
        qebitstatus_8->setShape(QBitStatus::Circle);
        qebitstatus_8->setInvalidColour(QColor(255, 0, 0));
        qebitstatus_8->setOffColour(QColor(255, 255, 255));
        label_19 = new QLabel(Filament_3);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(120, 10, 41, 21));
        label_19->setFont(font);
        qebitstatus_9 = new QEBitStatus(Filament_3);
        qebitstatus_9->setObjectName(QStringLiteral("qebitstatus_9"));
        qebitstatus_9->setGeometry(QRect(120, 30, 31, 21));
        qebitstatus_9->setNumberOfBits(1);
        qebitstatus_9->setShift(1);
        qebitstatus_9->setShape(QBitStatus::Circle);
        qebitstatus_9->setInvalidColour(QColor(255, 0, 0));
        qebitstatus_9->setOnColour(QColor(255, 255, 0));
        qebitstatus_9->setOffColour(QColor(255, 255, 255));
        qelabel_3 = new QELabel(Filament_3);
        qelabel_3->setObjectName(QStringLiteral("qelabel_3"));
        qelabel_3->setGeometry(QRect(100, 60, 61, 16));
        qelabel_3->setFont(font1);
        qepushbutton_5 = new QEPushButton(Filament_3);
        qepushbutton_5->setObjectName(QStringLiteral("qepushbutton_5"));
        qepushbutton_5->setGeometry(QRect(10, 50, 81, 23));
        qepushbutton_5->setCheckable(true);
        qepushbutton_6 = new QEPushButton(Filament_3);
        qepushbutton_6->setObjectName(QStringLiteral("qepushbutton_6"));
        qepushbutton_6->setGeometry(QRect(10, 30, 81, 21));
        qepushbutton_6->setCheckable(true);
        RGAstat_3 = new QGroupBox(status_2);
        RGAstat_3->setObjectName(QStringLiteral("RGAstat_3"));
        RGAstat_3->setGeometry(QRect(10, 90, 181, 61));
        qebitstatus_21 = new QEBitStatus(RGAstat_3);
        qebitstatus_21->setObjectName(QStringLiteral("qebitstatus_21"));
        qebitstatus_21->setGeometry(QRect(20, 30, 31, 21));
        qebitstatus_21->setNumberOfBits(1);
        qebitstatus_21->setShape(QBitStatus::Circle);
        qebitstatus_21->setInvalidColour(QColor(255, 0, 0));
        qebitstatus_21->setOnColour(QColor(255, 0, 0));
        qebitstatus_21->setOffColour(QColor(0, 255, 0));
        label_20 = new QLabel(RGAstat_3);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(20, 10, 51, 21));
        label_20->setFont(font);
        label_27 = new QLabel(RGAstat_3);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(80, 10, 31, 21));
        label_27->setFont(font);
        qelabel_53 = new QELabel(RGAstat_3);
        qelabel_53->setObjectName(QStringLiteral("qelabel_53"));
        qelabel_53->setGeometry(QRect(70, 30, 111, 21));
        qelabel_53->setFont(font2);
        Mode_6 = new QGroupBox(status_2);
        Mode_6->setObjectName(QStringLiteral("Mode_6"));
        Mode_6->setGeometry(QRect(190, 10, 111, 141));
        label_21 = new QLabel(Mode_6);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(10, 40, 47, 13));
        qepushbutton_40 = new QEPushButton(Mode_6);
        qepushbutton_40->setObjectName(QStringLiteral("qepushbutton_40"));
        qepushbutton_40->setGeometry(QRect(60, 60, 41, 20));
        qebutton50_7 = new QEPushButton(Mode_6);
        qebutton50_7->setObjectName(QStringLiteral("qebutton50_7"));
        qebutton50_7->setGeometry(QRect(10, 60, 41, 20));
        qebutton200_7 = new QEPushButton(Mode_6);
        qebutton200_7->setObjectName(QStringLiteral("qebutton200_7"));
        qebutton200_7->setGeometry(QRect(10, 100, 41, 20));
        label_22 = new QLabel(Mode_6);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(70, 40, 41, 16));
        qecheckbox_7 = new QECheckBox(Mode_6);
        qecheckbox_7->setObjectName(QStringLiteral("qecheckbox_7"));
        qecheckbox_7->setGeometry(QRect(10, 120, 81, 21));
        qecheckbox_7->setChecked(false);
        qecheckbox_7->setWriteOnPress(false);
        qecheckbox_7->setWriteOnClick(true);
        qebutton100_7 = new QEPushButton(Mode_6);
        qebutton100_7->setObjectName(QStringLiteral("qebutton100_7"));
        qebutton100_7->setGeometry(QRect(10, 80, 41, 20));
        qepushbutton_41 = new QEPushButton(Mode_6);
        qepushbutton_41->setObjectName(QStringLiteral("qepushbutton_41"));
        qepushbutton_41->setGeometry(QRect(10, 20, 41, 21));
        Mode_7 = new QGroupBox(status_2);
        Mode_7->setObjectName(QStringLiteral("Mode_7"));
        Mode_7->setGeometry(QRect(310, 10, 111, 141));
        qebutton50_8 = new QEPushButton(Mode_7);
        qebutton50_8->setObjectName(QStringLiteral("qebutton50_8"));
        qebutton50_8->setGeometry(QRect(10, 60, 41, 20));
        qebutton200_8 = new QEPushButton(Mode_7);
        qebutton200_8->setObjectName(QStringLiteral("qebutton200_8"));
        qebutton200_8->setGeometry(QRect(10, 100, 41, 20));
        qebutton100_8 = new QEPushButton(Mode_7);
        qebutton100_8->setObjectName(QStringLiteral("qebutton100_8"));
        qebutton100_8->setGeometry(QRect(10, 80, 41, 20));
        qepushbutton_42 = new QEPushButton(Mode_7);
        qepushbutton_42->setObjectName(QStringLiteral("qepushbutton_42"));
        qepushbutton_42->setGeometry(QRect(10, 20, 61, 21));
        qesimpleshape_31 = new QESimpleShape(Mode_7);
        qesimpleshape_31->setObjectName(QStringLiteral("qesimpleshape_31"));
        qesimpleshape_31->setGeometry(QRect(90, 60, 16, 16));
        qesimpleshape_31->setShape(QSimpleShape::ellipse);
        qesimpleshape_31->setProperty("colour1", QVariant(QColor(0, 255, 0)));
        qesimpleshape_31->setProperty("colour3", QVariant(QColor(200, 200, 200)));
        qesimpleshape_31->setProperty("colour4", QVariant(QColor(200, 200, 200)));
        qesimpleshape_31->setProperty("colour5", QVariant(QColor(200, 200, 200)));
        qesimpleshape_31->setProperty("flash0", QVariant(false));
        qesimpleshape_31->setProperty("flash1", QVariant(false));
        qesimpleshape_31->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        qesimpleshape_32 = new QESimpleShape(Mode_7);
        qesimpleshape_32->setObjectName(QStringLiteral("qesimpleshape_32"));
        qesimpleshape_32->setGeometry(QRect(90, 100, 16, 16));
        qesimpleshape_32->setShape(QSimpleShape::ellipse);
        qesimpleshape_32->setProperty("colour3", QVariant(QColor(0, 255, 0)));
        qesimpleshape_32->setProperty("colour7", QVariant(QColor(200, 200, 200)));
        qesimpleshape_32->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        qesimpleshape_33 = new QESimpleShape(Mode_7);
        qesimpleshape_33->setObjectName(QStringLiteral("qesimpleshape_33"));
        qesimpleshape_33->setGeometry(QRect(90, 80, 16, 16));
        qesimpleshape_33->setShape(QSimpleShape::ellipse);
        qesimpleshape_33->setProperty("colour2", QVariant(QColor(0, 255, 0)));
        qesimpleshape_33->setProperty("colour6", QVariant(QColor(200, 200, 200)));
        qesimpleshape_33->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        qesimpleshape_34 = new QESimpleShape(Mode_7);
        qesimpleshape_34->setObjectName(QStringLiteral("qesimpleshape_34"));
        qesimpleshape_34->setGeometry(QRect(90, 20, 16, 16));
        qesimpleshape_34->setFocusPolicy(Qt::NoFocus);
        qesimpleshape_34->setContextMenuPolicy(Qt::CustomContextMenu);
        qesimpleshape_34->setShape(QSimpleShape::ellipse);
        qesimpleshape_34->setProperty("colour0", QVariant(QColor(0, 255, 0)));
        qesimpleshape_34->setProperty("colour1", QVariant(QColor(200, 200, 200)));
        qesimpleshape_34->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        status_3 = new QGroupBox(centralwidget);
        status_3->setObjectName(QStringLiteral("status_3"));
        status_3->setGeometry(QRect(0, 170, 511, 161));
        Filament_4 = new QGroupBox(status_3);
        Filament_4->setObjectName(QStringLiteral("Filament_4"));
        Filament_4->setGeometry(QRect(10, 10, 181, 81));
        qebitstatus_10 = new QEBitStatus(Filament_4);
        qebitstatus_10->setObjectName(QStringLiteral("qebitstatus_10"));
        qebitstatus_10->setGeometry(QRect(150, 30, 31, 21));
        qebitstatus_10->setNumberOfBits(1);
        qebitstatus_10->setShift(3);
        qebitstatus_10->setShape(QBitStatus::Circle);
        qebitstatus_10->setInvalidColour(QColor(255, 0, 0));
        qebitstatus_10->setOnColour(QColor(255, 0, 4));
        qebitstatus_10->setOffColour(QColor(255, 255, 255));
        label_23 = new QLabel(Filament_4);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(160, 10, 16, 21));
        label_23->setFont(font);
        label_24 = new QLabel(Filament_4);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(90, 10, 31, 21));
        label_24->setFont(font);
        qebitstatus_11 = new QEBitStatus(Filament_4);
        qebitstatus_11->setObjectName(QStringLiteral("qebitstatus_11"));
        qebitstatus_11->setGeometry(QRect(90, 30, 31, 21));
        qebitstatus_11->setNumberOfBits(1);
        qebitstatus_11->setShape(QBitStatus::Circle);
        qebitstatus_11->setInvalidColour(QColor(255, 0, 0));
        qebitstatus_11->setOffColour(QColor(255, 255, 255));
        label_28 = new QLabel(Filament_4);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(120, 10, 41, 21));
        label_28->setFont(font);
        qebitstatus_12 = new QEBitStatus(Filament_4);
        qebitstatus_12->setObjectName(QStringLiteral("qebitstatus_12"));
        qebitstatus_12->setGeometry(QRect(120, 30, 31, 21));
        qebitstatus_12->setNumberOfBits(1);
        qebitstatus_12->setShift(1);
        qebitstatus_12->setShape(QBitStatus::Circle);
        qebitstatus_12->setInvalidColour(QColor(255, 0, 0));
        qebitstatus_12->setOnColour(QColor(255, 255, 0));
        qebitstatus_12->setOffColour(QColor(255, 255, 255));
        qelabel_4 = new QELabel(Filament_4);
        qelabel_4->setObjectName(QStringLiteral("qelabel_4"));
        qelabel_4->setGeometry(QRect(100, 60, 61, 16));
        qelabel_4->setFont(font1);
        qepushbutton_7 = new QEPushButton(Filament_4);
        qepushbutton_7->setObjectName(QStringLiteral("qepushbutton_7"));
        qepushbutton_7->setGeometry(QRect(10, 50, 81, 23));
        qepushbutton_7->setCheckable(true);
        qepushbutton_8 = new QEPushButton(Filament_4);
        qepushbutton_8->setObjectName(QStringLiteral("qepushbutton_8"));
        qepushbutton_8->setGeometry(QRect(10, 30, 81, 21));
        qepushbutton_8->setCheckable(true);
        RGAstat_4 = new QGroupBox(status_3);
        RGAstat_4->setObjectName(QStringLiteral("RGAstat_4"));
        RGAstat_4->setGeometry(QRect(10, 90, 181, 61));
        qebitstatus_22 = new QEBitStatus(RGAstat_4);
        qebitstatus_22->setObjectName(QStringLiteral("qebitstatus_22"));
        qebitstatus_22->setGeometry(QRect(20, 30, 31, 21));
        qebitstatus_22->setNumberOfBits(1);
        qebitstatus_22->setShape(QBitStatus::Circle);
        qebitstatus_22->setInvalidColour(QColor(255, 0, 0));
        qebitstatus_22->setOnColour(QColor(255, 0, 0));
        qebitstatus_22->setOffColour(QColor(0, 255, 0));
        label_29 = new QLabel(RGAstat_4);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(20, 10, 51, 21));
        label_29->setFont(font);
        label_30 = new QLabel(RGAstat_4);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(80, 10, 31, 21));
        label_30->setFont(font);
        qelabel_54 = new QELabel(RGAstat_4);
        qelabel_54->setObjectName(QStringLiteral("qelabel_54"));
        qelabel_54->setGeometry(QRect(70, 30, 111, 21));
        qelabel_54->setFont(font2);
        Mode_8 = new QGroupBox(status_3);
        Mode_8->setObjectName(QStringLiteral("Mode_8"));
        Mode_8->setGeometry(QRect(190, 10, 111, 141));
        label_31 = new QLabel(Mode_8);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(10, 40, 47, 13));
        qepushbutton_43 = new QEPushButton(Mode_8);
        qepushbutton_43->setObjectName(QStringLiteral("qepushbutton_43"));
        qepushbutton_43->setGeometry(QRect(60, 60, 41, 20));
        qebutton50_9 = new QEPushButton(Mode_8);
        qebutton50_9->setObjectName(QStringLiteral("qebutton50_9"));
        qebutton50_9->setGeometry(QRect(10, 60, 41, 20));
        qebutton200_9 = new QEPushButton(Mode_8);
        qebutton200_9->setObjectName(QStringLiteral("qebutton200_9"));
        qebutton200_9->setGeometry(QRect(10, 100, 41, 20));
        label_32 = new QLabel(Mode_8);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(70, 40, 41, 16));
        qecheckbox_8 = new QECheckBox(Mode_8);
        qecheckbox_8->setObjectName(QStringLiteral("qecheckbox_8"));
        qecheckbox_8->setGeometry(QRect(10, 120, 81, 21));
        qecheckbox_8->setChecked(false);
        qecheckbox_8->setWriteOnPress(false);
        qecheckbox_8->setWriteOnClick(true);
        qebutton100_9 = new QEPushButton(Mode_8);
        qebutton100_9->setObjectName(QStringLiteral("qebutton100_9"));
        qebutton100_9->setGeometry(QRect(10, 80, 41, 20));
        qepushbutton_44 = new QEPushButton(Mode_8);
        qepushbutton_44->setObjectName(QStringLiteral("qepushbutton_44"));
        qepushbutton_44->setGeometry(QRect(10, 20, 41, 21));
        Mode_9 = new QGroupBox(status_3);
        Mode_9->setObjectName(QStringLiteral("Mode_9"));
        Mode_9->setGeometry(QRect(310, 10, 111, 141));
        qebutton50_10 = new QEPushButton(Mode_9);
        qebutton50_10->setObjectName(QStringLiteral("qebutton50_10"));
        qebutton50_10->setGeometry(QRect(10, 60, 41, 20));
        qebutton200_10 = new QEPushButton(Mode_9);
        qebutton200_10->setObjectName(QStringLiteral("qebutton200_10"));
        qebutton200_10->setGeometry(QRect(10, 100, 41, 20));
        qebutton100_10 = new QEPushButton(Mode_9);
        qebutton100_10->setObjectName(QStringLiteral("qebutton100_10"));
        qebutton100_10->setGeometry(QRect(10, 80, 41, 20));
        qepushbutton_45 = new QEPushButton(Mode_9);
        qepushbutton_45->setObjectName(QStringLiteral("qepushbutton_45"));
        qepushbutton_45->setGeometry(QRect(10, 20, 61, 21));
        qesimpleshape_23 = new QESimpleShape(Mode_9);
        qesimpleshape_23->setObjectName(QStringLiteral("qesimpleshape_23"));
        qesimpleshape_23->setGeometry(QRect(90, 60, 16, 16));
        qesimpleshape_23->setShape(QSimpleShape::ellipse);
        qesimpleshape_23->setProperty("colour1", QVariant(QColor(0, 255, 0)));
        qesimpleshape_23->setProperty("colour3", QVariant(QColor(200, 200, 200)));
        qesimpleshape_23->setProperty("colour4", QVariant(QColor(200, 200, 200)));
        qesimpleshape_23->setProperty("colour5", QVariant(QColor(200, 200, 200)));
        qesimpleshape_23->setProperty("flash0", QVariant(false));
        qesimpleshape_23->setProperty("flash1", QVariant(false));
        qesimpleshape_23->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        qesimpleshape_24 = new QESimpleShape(Mode_9);
        qesimpleshape_24->setObjectName(QStringLiteral("qesimpleshape_24"));
        qesimpleshape_24->setGeometry(QRect(90, 100, 16, 16));
        qesimpleshape_24->setShape(QSimpleShape::ellipse);
        qesimpleshape_24->setProperty("colour3", QVariant(QColor(0, 255, 0)));
        qesimpleshape_24->setProperty("colour7", QVariant(QColor(200, 200, 200)));
        qesimpleshape_24->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        qesimpleshape_25 = new QESimpleShape(Mode_9);
        qesimpleshape_25->setObjectName(QStringLiteral("qesimpleshape_25"));
        qesimpleshape_25->setGeometry(QRect(90, 80, 16, 16));
        qesimpleshape_25->setShape(QSimpleShape::ellipse);
        qesimpleshape_25->setProperty("colour2", QVariant(QColor(0, 255, 0)));
        qesimpleshape_25->setProperty("colour6", QVariant(QColor(200, 200, 200)));
        qesimpleshape_25->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        qesimpleshape_26 = new QESimpleShape(Mode_9);
        qesimpleshape_26->setObjectName(QStringLiteral("qesimpleshape_26"));
        qesimpleshape_26->setGeometry(QRect(90, 20, 16, 16));
        qesimpleshape_26->setFocusPolicy(Qt::NoFocus);
        qesimpleshape_26->setContextMenuPolicy(Qt::CustomContextMenu);
        qesimpleshape_26->setShape(QSimpleShape::ellipse);
        qesimpleshape_26->setProperty("colour0", QVariant(QColor(0, 255, 0)));
        qesimpleshape_26->setProperty("colour1", QVariant(QColor(200, 200, 200)));
        qesimpleshape_26->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        status_4 = new QGroupBox(centralwidget);
        status_4->setObjectName(QStringLiteral("status_4"));
        status_4->setGeometry(QRect(0, 330, 511, 161));
        Filament_5 = new QGroupBox(status_4);
        Filament_5->setObjectName(QStringLiteral("Filament_5"));
        Filament_5->setGeometry(QRect(10, 10, 181, 81));
        qebitstatus_13 = new QEBitStatus(Filament_5);
        qebitstatus_13->setObjectName(QStringLiteral("qebitstatus_13"));
        qebitstatus_13->setGeometry(QRect(150, 30, 31, 21));
        qebitstatus_13->setNumberOfBits(1);
        qebitstatus_13->setShift(3);
        qebitstatus_13->setShape(QBitStatus::Circle);
        qebitstatus_13->setInvalidColour(QColor(255, 0, 0));
        qebitstatus_13->setOnColour(QColor(255, 0, 4));
        qebitstatus_13->setOffColour(QColor(255, 255, 255));
        label_33 = new QLabel(Filament_5);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(160, 10, 16, 21));
        label_33->setFont(font);
        label_34 = new QLabel(Filament_5);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(90, 10, 31, 21));
        label_34->setFont(font);
        qebitstatus_14 = new QEBitStatus(Filament_5);
        qebitstatus_14->setObjectName(QStringLiteral("qebitstatus_14"));
        qebitstatus_14->setGeometry(QRect(90, 30, 31, 21));
        qebitstatus_14->setNumberOfBits(1);
        qebitstatus_14->setShape(QBitStatus::Circle);
        qebitstatus_14->setInvalidColour(QColor(255, 0, 0));
        qebitstatus_14->setOffColour(QColor(255, 255, 255));
        label_35 = new QLabel(Filament_5);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(120, 10, 41, 21));
        label_35->setFont(font);
        qebitstatus_15 = new QEBitStatus(Filament_5);
        qebitstatus_15->setObjectName(QStringLiteral("qebitstatus_15"));
        qebitstatus_15->setGeometry(QRect(120, 30, 31, 21));
        qebitstatus_15->setNumberOfBits(1);
        qebitstatus_15->setShift(1);
        qebitstatus_15->setShape(QBitStatus::Circle);
        qebitstatus_15->setInvalidColour(QColor(255, 0, 0));
        qebitstatus_15->setOnColour(QColor(255, 255, 0));
        qebitstatus_15->setOffColour(QColor(255, 255, 255));
        qelabel_5 = new QELabel(Filament_5);
        qelabel_5->setObjectName(QStringLiteral("qelabel_5"));
        qelabel_5->setGeometry(QRect(100, 60, 61, 16));
        qelabel_5->setFont(font1);
        qepushbutton_9 = new QEPushButton(Filament_5);
        qepushbutton_9->setObjectName(QStringLiteral("qepushbutton_9"));
        qepushbutton_9->setGeometry(QRect(10, 50, 81, 23));
        qepushbutton_9->setCheckable(true);
        qepushbutton_10 = new QEPushButton(Filament_5);
        qepushbutton_10->setObjectName(QStringLiteral("qepushbutton_10"));
        qepushbutton_10->setGeometry(QRect(10, 30, 81, 21));
        qepushbutton_10->setCheckable(true);
        RGAstat_5 = new QGroupBox(status_4);
        RGAstat_5->setObjectName(QStringLiteral("RGAstat_5"));
        RGAstat_5->setGeometry(QRect(10, 90, 181, 61));
        qebitstatus_23 = new QEBitStatus(RGAstat_5);
        qebitstatus_23->setObjectName(QStringLiteral("qebitstatus_23"));
        qebitstatus_23->setGeometry(QRect(20, 30, 31, 21));
        qebitstatus_23->setNumberOfBits(1);
        qebitstatus_23->setShape(QBitStatus::Circle);
        qebitstatus_23->setInvalidColour(QColor(255, 0, 0));
        qebitstatus_23->setOnColour(QColor(255, 0, 0));
        qebitstatus_23->setOffColour(QColor(0, 255, 0));
        label_36 = new QLabel(RGAstat_5);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(20, 10, 51, 21));
        label_36->setFont(font);
        label_37 = new QLabel(RGAstat_5);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(80, 10, 31, 21));
        label_37->setFont(font);
        qelabel_55 = new QELabel(RGAstat_5);
        qelabel_55->setObjectName(QStringLiteral("qelabel_55"));
        qelabel_55->setGeometry(QRect(70, 30, 111, 21));
        qelabel_55->setFont(font2);
        Mode_10 = new QGroupBox(status_4);
        Mode_10->setObjectName(QStringLiteral("Mode_10"));
        Mode_10->setGeometry(QRect(190, 10, 111, 141));
        label_38 = new QLabel(Mode_10);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(10, 40, 47, 13));
        qepushbutton_46 = new QEPushButton(Mode_10);
        qepushbutton_46->setObjectName(QStringLiteral("qepushbutton_46"));
        qepushbutton_46->setGeometry(QRect(60, 60, 41, 20));
        qebutton50_11 = new QEPushButton(Mode_10);
        qebutton50_11->setObjectName(QStringLiteral("qebutton50_11"));
        qebutton50_11->setGeometry(QRect(10, 60, 41, 20));
        qebutton200_11 = new QEPushButton(Mode_10);
        qebutton200_11->setObjectName(QStringLiteral("qebutton200_11"));
        qebutton200_11->setGeometry(QRect(10, 100, 41, 20));
        label_39 = new QLabel(Mode_10);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(70, 40, 41, 16));
        qecheckbox_9 = new QECheckBox(Mode_10);
        qecheckbox_9->setObjectName(QStringLiteral("qecheckbox_9"));
        qecheckbox_9->setGeometry(QRect(10, 120, 81, 21));
        qecheckbox_9->setChecked(false);
        qecheckbox_9->setWriteOnPress(false);
        qecheckbox_9->setWriteOnClick(true);
        qebutton100_11 = new QEPushButton(Mode_10);
        qebutton100_11->setObjectName(QStringLiteral("qebutton100_11"));
        qebutton100_11->setGeometry(QRect(10, 80, 41, 20));
        qepushbutton_47 = new QEPushButton(Mode_10);
        qepushbutton_47->setObjectName(QStringLiteral("qepushbutton_47"));
        qepushbutton_47->setGeometry(QRect(10, 20, 41, 21));
        Mode_11 = new QGroupBox(status_4);
        Mode_11->setObjectName(QStringLiteral("Mode_11"));
        Mode_11->setGeometry(QRect(310, 10, 111, 141));
        qebutton50_12 = new QEPushButton(Mode_11);
        qebutton50_12->setObjectName(QStringLiteral("qebutton50_12"));
        qebutton50_12->setGeometry(QRect(10, 60, 41, 20));
        qebutton200_12 = new QEPushButton(Mode_11);
        qebutton200_12->setObjectName(QStringLiteral("qebutton200_12"));
        qebutton200_12->setGeometry(QRect(10, 100, 41, 20));
        qebutton100_12 = new QEPushButton(Mode_11);
        qebutton100_12->setObjectName(QStringLiteral("qebutton100_12"));
        qebutton100_12->setGeometry(QRect(10, 80, 41, 20));
        qepushbutton_48 = new QEPushButton(Mode_11);
        qepushbutton_48->setObjectName(QStringLiteral("qepushbutton_48"));
        qepushbutton_48->setGeometry(QRect(10, 20, 61, 21));
        qesimpleshape_27 = new QESimpleShape(Mode_11);
        qesimpleshape_27->setObjectName(QStringLiteral("qesimpleshape_27"));
        qesimpleshape_27->setGeometry(QRect(90, 60, 16, 16));
        qesimpleshape_27->setShape(QSimpleShape::ellipse);
        qesimpleshape_27->setProperty("colour1", QVariant(QColor(0, 255, 0)));
        qesimpleshape_27->setProperty("colour3", QVariant(QColor(200, 200, 200)));
        qesimpleshape_27->setProperty("colour4", QVariant(QColor(200, 200, 200)));
        qesimpleshape_27->setProperty("colour5", QVariant(QColor(200, 200, 200)));
        qesimpleshape_27->setProperty("flash0", QVariant(false));
        qesimpleshape_27->setProperty("flash1", QVariant(false));
        qesimpleshape_27->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        qesimpleshape_28 = new QESimpleShape(Mode_11);
        qesimpleshape_28->setObjectName(QStringLiteral("qesimpleshape_28"));
        qesimpleshape_28->setGeometry(QRect(90, 100, 16, 16));
        qesimpleshape_28->setShape(QSimpleShape::ellipse);
        qesimpleshape_28->setProperty("colour3", QVariant(QColor(0, 255, 0)));
        qesimpleshape_28->setProperty("colour7", QVariant(QColor(200, 200, 200)));
        qesimpleshape_28->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        qesimpleshape_29 = new QESimpleShape(Mode_11);
        qesimpleshape_29->setObjectName(QStringLiteral("qesimpleshape_29"));
        qesimpleshape_29->setGeometry(QRect(90, 80, 16, 16));
        qesimpleshape_29->setShape(QSimpleShape::ellipse);
        qesimpleshape_29->setProperty("colour2", QVariant(QColor(0, 255, 0)));
        qesimpleshape_29->setProperty("colour6", QVariant(QColor(200, 200, 200)));
        qesimpleshape_29->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        qesimpleshape_30 = new QESimpleShape(Mode_11);
        qesimpleshape_30->setObjectName(QStringLiteral("qesimpleshape_30"));
        qesimpleshape_30->setGeometry(QRect(90, 20, 16, 16));
        qesimpleshape_30->setFocusPolicy(Qt::NoFocus);
        qesimpleshape_30->setContextMenuPolicy(Qt::CustomContextMenu);
        qesimpleshape_30->setShape(QSimpleShape::ellipse);
        qesimpleshape_30->setProperty("colour0", QVariant(QColor(0, 255, 0)));
        qesimpleshape_30->setProperty("colour1", QVariant(QColor(200, 200, 200)));
        qesimpleshape_30->setProperty("displayAlarmStateOption", QVariant(QESimpleShape::Never));
        rgaWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(rgaWindow);
        menubar->setObjectName(QStringLiteral("menubar"));
        menubar->setGeometry(QRect(0, 0, 529, 21));
        rgaWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(rgaWindow);
        statusbar->setObjectName(QStringLiteral("statusbar"));
        rgaWindow->setStatusBar(statusbar);

        retranslateUi(rgaWindow);

        QMetaObject::connectSlotsByName(rgaWindow);
    } // setupUi

    void retranslateUi(QMainWindow *rgaWindow)
    {
        rgaWindow->setWindowTitle(QApplication::translate("rgaWindow", "MainWindow", 0));
        status->setTitle(QApplication::translate("rgaWindow", "RGA 1", 0));
        Filament->setTitle(QApplication::translate("rgaWindow", "Filament Status", 0));
        qebitstatus_4->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA1):FILSTA", 0)));
        label_4->setText(QApplication::translate("rgaWindow", "Fail", 0));
        label->setText(QApplication::translate("rgaWindow", "On/Off", 0));
        qebitstatus->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA1):FILSTA", 0)));
        label_2->setText(QApplication::translate("rgaWindow", "Cool/Warm", 0));
        qebitstatus_2->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA1):FILSTA", 0)));
        qelabel->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA1):FIL", 0)));
        qepushbutton_2->setText(QApplication::translate("rgaWindow", "Filament select", 0));
        qepushbutton_2->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA1):SETFIL", 0)));
        qepushbutton_2->setProperty("altReadbackVariable", QVariant(QString()));
        qepushbutton_2->setPressText(QApplication::translate("rgaWindow", "1", 0));
        qepushbutton->setText(QApplication::translate("rgaWindow", "Filament Power", 0));
        qepushbutton->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA1):FILCON", 0)));
        qepushbutton->setProperty("altReadbackVariable", QVariant(QString()));
        qepushbutton->setPressText(QApplication::translate("rgaWindow", "1", 0));
        RGAstat->setTitle(QApplication::translate("rgaWindow", "RGA Status", 0));
        qebitstatus_19->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA1):ILK", 0)));
        label_5->setText(QApplication::translate("rgaWindow", "IMG Interlock", 0));
        label_25->setText(QApplication::translate("rgaWindow", "Control", 0));
        qelabel_51->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA1):HEADSTA", 0)));
        qelabel_51->setText(QApplication::translate("rgaWindow", "Analog 1-200", 0));
        Mode_2->setTitle(QApplication::translate("rgaWindow", "Mode", 0));
        label_7->setText(QApplication::translate("rgaWindow", "Bar Chart", 0));
        qepushbutton_35->setText(QApplication::translate("rgaWindow", "1-200", 0));
        qepushbutton_35->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA1):CON", 0)));
        qepushbutton_35->setProperty("altReadbackVariable", QVariant(QString()));
        qepushbutton_35->setProperty("variableSubstitutions", QVariant(QString()));
        qepushbutton_35->setClickText(QApplication::translate("rgaWindow", "8", 0));
        qepushbutton_35->setClickCheckedText(QString());
        qebutton50_2->setText(QApplication::translate("rgaWindow", "1-50", 0));
        qebutton50_2->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA1):CON", 0)));
        qebutton50_2->setProperty("altReadbackVariable", QVariant(QString()));
        qebutton50_2->setProperty("variableSubstitutions", QVariant(QString()));
        qebutton50_2->setClickText(QApplication::translate("rgaWindow", "5", 0));
        qebutton50_2->setClickCheckedText(QString());
        qebutton200_2->setText(QApplication::translate("rgaWindow", "1-200", 0));
        qebutton200_2->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA1):CON", 0)));
        qebutton200_2->setProperty("altReadbackVariable", QVariant(QString()));
        qebutton200_2->setProperty("variableSubstitutions", QVariant(QString()));
        qebutton200_2->setClickText(QApplication::translate("rgaWindow", "7", 0));
        qebutton200_2->setClickCheckedText(QString());
        label_8->setText(QApplication::translate("rgaWindow", "Ana", 0));
        qecheckbox_4->setText(QApplication::translate("rgaWindow", "Single Scan", 0));
        qecheckbox_4->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA1):SETSCAN", 0)));
        qecheckbox_4->setPressText(QApplication::translate("rgaWindow", "0", 0));
        qecheckbox_4->setReleaseText(QApplication::translate("rgaWindow", "1", 0));
        qecheckbox_4->setClickText(QApplication::translate("rgaWindow", "1", 0));
        qecheckbox_4->setClickCheckedText(QApplication::translate("rgaWindow", "0", 0));
        qebutton100_2->setText(QApplication::translate("rgaWindow", "1-100", 0));
        qebutton100_2->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA1):CON", 0)));
        qebutton100_2->setProperty("altReadbackVariable", QVariant(QString()));
        qebutton100_2->setProperty("variableSubstitutions", QVariant(QString()));
        qebutton100_2->setClickText(QApplication::translate("rgaWindow", "6", 0));
        qebutton100_2->setClickCheckedText(QString());
        qepushbutton_31->setText(QApplication::translate("rgaWindow", "Stop", 0));
        qepushbutton_31->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA1):CON", 0)));
        qepushbutton_31->setProperty("altReadbackVariable", QVariant(QString()));
        qepushbutton_31->setProperty("variableSubstitutions", QVariant(QString()));
        qepushbutton_31->setClickText(QApplication::translate("rgaWindow", "Stop", 0));
        qepushbutton_31->setClickCheckedText(QString());
        Mode_3->setTitle(QApplication::translate("rgaWindow", "Faraday/Mult", 0));
        qebutton50_4->setText(QApplication::translate("rgaWindow", "M1", 0));
        qebutton50_4->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA1):MLTCON", 0)));
        qebutton50_4->setProperty("altReadbackVariable", QVariant(QString()));
        qebutton50_4->setProperty("variableSubstitutions", QVariant(QString()));
        qebutton50_4->setClickText(QApplication::translate("rgaWindow", "1", 0));
        qebutton50_4->setClickCheckedText(QString());
        qebutton200_4->setText(QApplication::translate("rgaWindow", "M3", 0));
        qebutton200_4->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA1):MLTCON", 0)));
        qebutton200_4->setProperty("altReadbackVariable", QVariant(QString()));
        qebutton200_4->setProperty("variableSubstitutions", QVariant(QString()));
        qebutton200_4->setClickText(QApplication::translate("rgaWindow", "3", 0));
        qebutton200_4->setClickCheckedText(QString());
        qebutton100_4->setText(QApplication::translate("rgaWindow", "M2", 0));
        qebutton100_4->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA1):MLTCON", 0)));
        qebutton100_4->setProperty("altReadbackVariable", QVariant(QString()));
        qebutton100_4->setProperty("variableSubstitutions", QVariant(QString()));
        qebutton100_4->setClickText(QApplication::translate("rgaWindow", "2", 0));
        qebutton100_4->setClickCheckedText(QString());
        qepushbutton_33->setText(QApplication::translate("rgaWindow", "Faraday", 0));
        qepushbutton_33->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA1):MLTCON", 0)));
        qepushbutton_33->setProperty("altReadbackVariable", QVariant(QString()));
        qepushbutton_33->setProperty("variableSubstitutions", QVariant(QString()));
        qepushbutton_33->setClickText(QApplication::translate("rgaWindow", "0", 0));
        qepushbutton_33->setClickCheckedText(QString());
        qesimpleshape_19->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA1):MLTSTA", 0)));
        qesimpleshape_20->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA1):MLTSTA", 0)));
        qesimpleshape_20->setProperty("variableSubstitutions", QVariant(QString()));
        qesimpleshape_21->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA1):MLTSTA", 0)));
        qesimpleshape_22->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA1):MLTSTA", 0)));
        status_2->setTitle(QApplication::translate("rgaWindow", "RGA 4", 0));
        Filament_3->setTitle(QApplication::translate("rgaWindow", "Filament Status", 0));
        qebitstatus_7->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA4):FILSTA", 0)));
        label_17->setText(QApplication::translate("rgaWindow", "Fail", 0));
        label_18->setText(QApplication::translate("rgaWindow", "On/Off", 0));
        qebitstatus_8->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA4):FILSTA", 0)));
        label_19->setText(QApplication::translate("rgaWindow", "Cool/Warm", 0));
        qebitstatus_9->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA4):FILSTA", 0)));
        qelabel_3->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA4):FIL", 0)));
        qepushbutton_5->setText(QApplication::translate("rgaWindow", "Filament select", 0));
        qepushbutton_5->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA4):SETFIL", 0)));
        qepushbutton_5->setProperty("altReadbackVariable", QVariant(QString()));
        qepushbutton_5->setPressText(QApplication::translate("rgaWindow", "1", 0));
        qepushbutton_6->setText(QApplication::translate("rgaWindow", "Filament Power", 0));
        qepushbutton_6->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA4):FILCON", 0)));
        qepushbutton_6->setProperty("altReadbackVariable", QVariant(QString()));
        qepushbutton_6->setPressText(QApplication::translate("rgaWindow", "1", 0));
        RGAstat_3->setTitle(QApplication::translate("rgaWindow", "RGA Status", 0));
        qebitstatus_21->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA4):ILK", 0)));
        label_20->setText(QApplication::translate("rgaWindow", "IMG Interlock", 0));
        label_27->setText(QApplication::translate("rgaWindow", "Control", 0));
        qelabel_53->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA4):HEADSTA", 0)));
        qelabel_53->setText(QApplication::translate("rgaWindow", "Analog 1-200", 0));
        Mode_6->setTitle(QApplication::translate("rgaWindow", "Mode", 0));
        label_21->setText(QApplication::translate("rgaWindow", "Bar Chart", 0));
        qepushbutton_40->setText(QApplication::translate("rgaWindow", "1-200", 0));
        qepushbutton_40->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA4):CON", 0)));
        qepushbutton_40->setProperty("altReadbackVariable", QVariant(QString()));
        qepushbutton_40->setProperty("variableSubstitutions", QVariant(QString()));
        qepushbutton_40->setClickText(QApplication::translate("rgaWindow", "8", 0));
        qepushbutton_40->setClickCheckedText(QString());
        qebutton50_7->setText(QApplication::translate("rgaWindow", "1-50", 0));
        qebutton50_7->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA4):CON", 0)));
        qebutton50_7->setProperty("altReadbackVariable", QVariant(QString()));
        qebutton50_7->setProperty("variableSubstitutions", QVariant(QString()));
        qebutton50_7->setClickText(QApplication::translate("rgaWindow", "5", 0));
        qebutton50_7->setClickCheckedText(QString());
        qebutton200_7->setText(QApplication::translate("rgaWindow", "1-200", 0));
        qebutton200_7->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA4):CON", 0)));
        qebutton200_7->setProperty("altReadbackVariable", QVariant(QString()));
        qebutton200_7->setProperty("variableSubstitutions", QVariant(QString()));
        qebutton200_7->setClickText(QApplication::translate("rgaWindow", "7", 0));
        qebutton200_7->setClickCheckedText(QString());
        label_22->setText(QApplication::translate("rgaWindow", "Ana", 0));
        qecheckbox_7->setText(QApplication::translate("rgaWindow", "Single Scan", 0));
        qecheckbox_7->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA4):SETSCAN", 0)));
        qecheckbox_7->setPressText(QApplication::translate("rgaWindow", "0", 0));
        qecheckbox_7->setReleaseText(QApplication::translate("rgaWindow", "1", 0));
        qecheckbox_7->setClickText(QApplication::translate("rgaWindow", "1", 0));
        qecheckbox_7->setClickCheckedText(QApplication::translate("rgaWindow", "0", 0));
        qebutton100_7->setText(QApplication::translate("rgaWindow", "1-100", 0));
        qebutton100_7->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA4):CON", 0)));
        qebutton100_7->setProperty("altReadbackVariable", QVariant(QString()));
        qebutton100_7->setProperty("variableSubstitutions", QVariant(QString()));
        qebutton100_7->setClickText(QApplication::translate("rgaWindow", "6", 0));
        qebutton100_7->setClickCheckedText(QString());
        qepushbutton_41->setText(QApplication::translate("rgaWindow", "Stop", 0));
        qepushbutton_41->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA4):CON", 0)));
        qepushbutton_41->setProperty("altReadbackVariable", QVariant(QString()));
        qepushbutton_41->setProperty("variableSubstitutions", QVariant(QString()));
        qepushbutton_41->setClickText(QApplication::translate("rgaWindow", "Stop", 0));
        qepushbutton_41->setClickCheckedText(QString());
        Mode_7->setTitle(QApplication::translate("rgaWindow", "Faraday/Mult", 0));
        qebutton50_8->setText(QApplication::translate("rgaWindow", "M1", 0));
        qebutton50_8->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA4):MLTCON", 0)));
        qebutton50_8->setProperty("altReadbackVariable", QVariant(QString()));
        qebutton50_8->setProperty("variableSubstitutions", QVariant(QString()));
        qebutton50_8->setClickText(QApplication::translate("rgaWindow", "1", 0));
        qebutton50_8->setClickCheckedText(QString());
        qebutton200_8->setText(QApplication::translate("rgaWindow", "M3", 0));
        qebutton200_8->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA4):MLTCON", 0)));
        qebutton200_8->setProperty("altReadbackVariable", QVariant(QString()));
        qebutton200_8->setProperty("variableSubstitutions", QVariant(QString()));
        qebutton200_8->setClickText(QApplication::translate("rgaWindow", "3", 0));
        qebutton200_8->setClickCheckedText(QString());
        qebutton100_8->setText(QApplication::translate("rgaWindow", "M2", 0));
        qebutton100_8->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA4):MLTCON", 0)));
        qebutton100_8->setProperty("altReadbackVariable", QVariant(QString()));
        qebutton100_8->setProperty("variableSubstitutions", QVariant(QString()));
        qebutton100_8->setClickText(QApplication::translate("rgaWindow", "2", 0));
        qebutton100_8->setClickCheckedText(QString());
        qepushbutton_42->setText(QApplication::translate("rgaWindow", "Faraday", 0));
        qepushbutton_42->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA4):MLTCON", 0)));
        qepushbutton_42->setProperty("altReadbackVariable", QVariant(QString()));
        qepushbutton_42->setProperty("variableSubstitutions", QVariant(QString()));
        qepushbutton_42->setClickText(QApplication::translate("rgaWindow", "0", 0));
        qepushbutton_42->setClickCheckedText(QString());
        qesimpleshape_31->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA4):MLTSTA", 0)));
        qesimpleshape_32->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA4):MLTSTA", 0)));
        qesimpleshape_33->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA4):MLTSTA", 0)));
        qesimpleshape_34->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA4):MLTSTA", 0)));
        qesimpleshape_34->setProperty("variableSubstitutions", QVariant(QString()));
        status_3->setTitle(QApplication::translate("rgaWindow", "RGA 2", 0));
        Filament_4->setTitle(QApplication::translate("rgaWindow", "Filament Status", 0));
        qebitstatus_10->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA2):FILSTA", 0)));
        label_23->setText(QApplication::translate("rgaWindow", "Fail", 0));
        label_24->setText(QApplication::translate("rgaWindow", "On/Off", 0));
        qebitstatus_11->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA2):FILSTA", 0)));
        label_28->setText(QApplication::translate("rgaWindow", "Cool/Warm", 0));
        qebitstatus_12->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA2):FILSTA", 0)));
        qelabel_4->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA2):FIL", 0)));
        qepushbutton_7->setText(QApplication::translate("rgaWindow", "Filament select", 0));
        qepushbutton_7->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA2):SETFIL", 0)));
        qepushbutton_7->setProperty("altReadbackVariable", QVariant(QString()));
        qepushbutton_7->setPressText(QApplication::translate("rgaWindow", "1", 0));
        qepushbutton_8->setText(QApplication::translate("rgaWindow", "Filament Power", 0));
        qepushbutton_8->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA2):FILCON", 0)));
        qepushbutton_8->setProperty("altReadbackVariable", QVariant(QString()));
        qepushbutton_8->setPressText(QApplication::translate("rgaWindow", "1", 0));
        RGAstat_4->setTitle(QApplication::translate("rgaWindow", "RGA Status", 0));
        qebitstatus_22->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA2):ILK", 0)));
        label_29->setText(QApplication::translate("rgaWindow", "IMG Interlock", 0));
        label_30->setText(QApplication::translate("rgaWindow", "Control", 0));
        qelabel_54->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA2):HEADSTA", 0)));
        qelabel_54->setText(QApplication::translate("rgaWindow", "Analog 1-200", 0));
        Mode_8->setTitle(QApplication::translate("rgaWindow", "Mode", 0));
        label_31->setText(QApplication::translate("rgaWindow", "Bar Chart", 0));
        qepushbutton_43->setText(QApplication::translate("rgaWindow", "1-200", 0));
        qepushbutton_43->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA2):CON", 0)));
        qepushbutton_43->setProperty("altReadbackVariable", QVariant(QString()));
        qepushbutton_43->setProperty("variableSubstitutions", QVariant(QString()));
        qepushbutton_43->setClickText(QApplication::translate("rgaWindow", "8", 0));
        qepushbutton_43->setClickCheckedText(QString());
        qebutton50_9->setText(QApplication::translate("rgaWindow", "1-50", 0));
        qebutton50_9->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA2):CON", 0)));
        qebutton50_9->setProperty("altReadbackVariable", QVariant(QString()));
        qebutton50_9->setProperty("variableSubstitutions", QVariant(QString()));
        qebutton50_9->setClickText(QApplication::translate("rgaWindow", "5", 0));
        qebutton50_9->setClickCheckedText(QString());
        qebutton200_9->setText(QApplication::translate("rgaWindow", "1-200", 0));
        qebutton200_9->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA2):CON", 0)));
        qebutton200_9->setProperty("altReadbackVariable", QVariant(QString()));
        qebutton200_9->setProperty("variableSubstitutions", QVariant(QString()));
        qebutton200_9->setClickText(QApplication::translate("rgaWindow", "7", 0));
        qebutton200_9->setClickCheckedText(QString());
        label_32->setText(QApplication::translate("rgaWindow", "Ana", 0));
        qecheckbox_8->setText(QApplication::translate("rgaWindow", "Single Scan", 0));
        qecheckbox_8->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA2):SETSCAN", 0)));
        qecheckbox_8->setPressText(QApplication::translate("rgaWindow", "0", 0));
        qecheckbox_8->setReleaseText(QApplication::translate("rgaWindow", "1", 0));
        qecheckbox_8->setClickText(QApplication::translate("rgaWindow", "1", 0));
        qecheckbox_8->setClickCheckedText(QApplication::translate("rgaWindow", "0", 0));
        qebutton100_9->setText(QApplication::translate("rgaWindow", "1-100", 0));
        qebutton100_9->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA2):CON", 0)));
        qebutton100_9->setProperty("altReadbackVariable", QVariant(QString()));
        qebutton100_9->setProperty("variableSubstitutions", QVariant(QString()));
        qebutton100_9->setClickText(QApplication::translate("rgaWindow", "6", 0));
        qebutton100_9->setClickCheckedText(QString());
        qepushbutton_44->setText(QApplication::translate("rgaWindow", "Stop", 0));
        qepushbutton_44->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA2):CON", 0)));
        qepushbutton_44->setProperty("altReadbackVariable", QVariant(QString()));
        qepushbutton_44->setProperty("variableSubstitutions", QVariant(QString()));
        qepushbutton_44->setClickText(QApplication::translate("rgaWindow", "Stop", 0));
        qepushbutton_44->setClickCheckedText(QString());
        Mode_9->setTitle(QApplication::translate("rgaWindow", "Faraday/Mult", 0));
        qebutton50_10->setText(QApplication::translate("rgaWindow", "M1", 0));
        qebutton50_10->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA2):MLTCON", 0)));
        qebutton50_10->setProperty("altReadbackVariable", QVariant(QString()));
        qebutton50_10->setProperty("variableSubstitutions", QVariant(QString()));
        qebutton50_10->setClickText(QApplication::translate("rgaWindow", "1", 0));
        qebutton50_10->setClickCheckedText(QString());
        qebutton200_10->setText(QApplication::translate("rgaWindow", "M3", 0));
        qebutton200_10->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA2):MLTCON", 0)));
        qebutton200_10->setProperty("altReadbackVariable", QVariant(QString()));
        qebutton200_10->setProperty("variableSubstitutions", QVariant(QString()));
        qebutton200_10->setClickText(QApplication::translate("rgaWindow", "3", 0));
        qebutton200_10->setClickCheckedText(QString());
        qebutton100_10->setText(QApplication::translate("rgaWindow", "M2", 0));
        qebutton100_10->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA2):MLTCON", 0)));
        qebutton100_10->setProperty("altReadbackVariable", QVariant(QString()));
        qebutton100_10->setProperty("variableSubstitutions", QVariant(QString()));
        qebutton100_10->setClickText(QApplication::translate("rgaWindow", "2", 0));
        qebutton100_10->setClickCheckedText(QString());
        qepushbutton_45->setText(QApplication::translate("rgaWindow", "Faraday", 0));
        qepushbutton_45->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA2):MLTCON", 0)));
        qepushbutton_45->setProperty("altReadbackVariable", QVariant(QString()));
        qepushbutton_45->setProperty("variableSubstitutions", QVariant(QString()));
        qepushbutton_45->setClickText(QApplication::translate("rgaWindow", "0", 0));
        qepushbutton_45->setClickCheckedText(QString());
        qesimpleshape_23->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA2):MLTSTA", 0)));
        qesimpleshape_24->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA2):MLTSTA", 0)));
        qesimpleshape_25->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA2):MLTSTA", 0)));
        qesimpleshape_26->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA2):MLTSTA", 0)));
        qesimpleshape_26->setProperty("variableSubstitutions", QVariant(QString()));
        status_4->setTitle(QApplication::translate("rgaWindow", "RGA 3", 0));
        Filament_5->setTitle(QApplication::translate("rgaWindow", "Filament Status", 0));
        qebitstatus_13->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA3):FILSTA", 0)));
        label_33->setText(QApplication::translate("rgaWindow", "Fail", 0));
        label_34->setText(QApplication::translate("rgaWindow", "On/Off", 0));
        qebitstatus_14->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA3):FILSTA", 0)));
        label_35->setText(QApplication::translate("rgaWindow", "Cool/Warm", 0));
        qebitstatus_15->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA3):FILSTA", 0)));
        qelabel_5->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA3):FIL", 0)));
        qepushbutton_9->setText(QApplication::translate("rgaWindow", "Filament select", 0));
        qepushbutton_9->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA3):SETFIL", 0)));
        qepushbutton_9->setProperty("altReadbackVariable", QVariant(QString()));
        qepushbutton_9->setPressText(QApplication::translate("rgaWindow", "1", 0));
        qepushbutton_10->setText(QApplication::translate("rgaWindow", "Filament Power", 0));
        qepushbutton_10->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA3):FILCON", 0)));
        qepushbutton_10->setProperty("altReadbackVariable", QVariant(QString()));
        qepushbutton_10->setPressText(QApplication::translate("rgaWindow", "1", 0));
        RGAstat_5->setTitle(QApplication::translate("rgaWindow", "RGA Status", 0));
        qebitstatus_23->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA3):ILK", 0)));
        label_36->setText(QApplication::translate("rgaWindow", "IMG Interlock", 0));
        label_37->setText(QApplication::translate("rgaWindow", "Control", 0));
        qelabel_55->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA3):HEADSTA", 0)));
        qelabel_55->setText(QApplication::translate("rgaWindow", "Analog 1-200", 0));
        Mode_10->setTitle(QApplication::translate("rgaWindow", "Mode", 0));
        label_38->setText(QApplication::translate("rgaWindow", "Bar Chart", 0));
        qepushbutton_46->setText(QApplication::translate("rgaWindow", "1-200", 0));
        qepushbutton_46->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA3):CON", 0)));
        qepushbutton_46->setProperty("altReadbackVariable", QVariant(QString()));
        qepushbutton_46->setProperty("variableSubstitutions", QVariant(QString()));
        qepushbutton_46->setClickText(QApplication::translate("rgaWindow", "8", 0));
        qepushbutton_46->setClickCheckedText(QString());
        qebutton50_11->setText(QApplication::translate("rgaWindow", "1-50", 0));
        qebutton50_11->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA3):CON", 0)));
        qebutton50_11->setProperty("altReadbackVariable", QVariant(QString()));
        qebutton50_11->setProperty("variableSubstitutions", QVariant(QString()));
        qebutton50_11->setClickText(QApplication::translate("rgaWindow", "5", 0));
        qebutton50_11->setClickCheckedText(QString());
        qebutton200_11->setText(QApplication::translate("rgaWindow", "1-200", 0));
        qebutton200_11->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA3):CON", 0)));
        qebutton200_11->setProperty("altReadbackVariable", QVariant(QString()));
        qebutton200_11->setProperty("variableSubstitutions", QVariant(QString()));
        qebutton200_11->setClickText(QApplication::translate("rgaWindow", "7", 0));
        qebutton200_11->setClickCheckedText(QString());
        label_39->setText(QApplication::translate("rgaWindow", "Ana", 0));
        qecheckbox_9->setText(QApplication::translate("rgaWindow", "Single Scan", 0));
        qecheckbox_9->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA3):SETSCAN", 0)));
        qecheckbox_9->setPressText(QApplication::translate("rgaWindow", "0", 0));
        qecheckbox_9->setReleaseText(QApplication::translate("rgaWindow", "1", 0));
        qecheckbox_9->setClickText(QApplication::translate("rgaWindow", "1", 0));
        qecheckbox_9->setClickCheckedText(QApplication::translate("rgaWindow", "0", 0));
        qebutton100_11->setText(QApplication::translate("rgaWindow", "1-100", 0));
        qebutton100_11->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA3):CON", 0)));
        qebutton100_11->setProperty("altReadbackVariable", QVariant(QString()));
        qebutton100_11->setProperty("variableSubstitutions", QVariant(QString()));
        qebutton100_11->setClickText(QApplication::translate("rgaWindow", "6", 0));
        qebutton100_11->setClickCheckedText(QString());
        qepushbutton_47->setText(QApplication::translate("rgaWindow", "Stop", 0));
        qepushbutton_47->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA3):CON", 0)));
        qepushbutton_47->setProperty("altReadbackVariable", QVariant(QString()));
        qepushbutton_47->setProperty("variableSubstitutions", QVariant(QString()));
        qepushbutton_47->setClickText(QApplication::translate("rgaWindow", "Stop", 0));
        qepushbutton_47->setClickCheckedText(QString());
        Mode_11->setTitle(QApplication::translate("rgaWindow", "Faraday/Mult", 0));
        qebutton50_12->setText(QApplication::translate("rgaWindow", "M1", 0));
        qebutton50_12->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA3):MLTCON", 0)));
        qebutton50_12->setProperty("altReadbackVariable", QVariant(QString()));
        qebutton50_12->setProperty("variableSubstitutions", QVariant(QString()));
        qebutton50_12->setClickText(QApplication::translate("rgaWindow", "1", 0));
        qebutton50_12->setClickCheckedText(QString());
        qebutton200_12->setText(QApplication::translate("rgaWindow", "M3", 0));
        qebutton200_12->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA3):MLTCON", 0)));
        qebutton200_12->setProperty("altReadbackVariable", QVariant(QString()));
        qebutton200_12->setProperty("variableSubstitutions", QVariant(QString()));
        qebutton200_12->setClickText(QApplication::translate("rgaWindow", "3", 0));
        qebutton200_12->setClickCheckedText(QString());
        qebutton100_12->setText(QApplication::translate("rgaWindow", "M2", 0));
        qebutton100_12->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA3):MLTCON", 0)));
        qebutton100_12->setProperty("altReadbackVariable", QVariant(QString()));
        qebutton100_12->setProperty("variableSubstitutions", QVariant(QString()));
        qebutton100_12->setClickText(QApplication::translate("rgaWindow", "2", 0));
        qebutton100_12->setClickCheckedText(QString());
        qepushbutton_48->setText(QApplication::translate("rgaWindow", "Faraday", 0));
        qepushbutton_48->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA3):MLTCON", 0)));
        qepushbutton_48->setProperty("altReadbackVariable", QVariant(QString()));
        qepushbutton_48->setProperty("variableSubstitutions", QVariant(QString()));
        qepushbutton_48->setClickText(QApplication::translate("rgaWindow", "0", 0));
        qepushbutton_48->setClickCheckedText(QString());
        qesimpleshape_27->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA3):MLTSTA", 0)));
        qesimpleshape_28->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA3):MLTSTA", 0)));
        qesimpleshape_29->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA3):MLTSTA", 0)));
        qesimpleshape_30->setProperty("variable", QVariant(QApplication::translate("rgaWindow", "$(RGA3):MLTSTA", 0)));
        qesimpleshape_30->setProperty("variableSubstitutions", QVariant(QString()));
    } // retranslateUi

};

namespace Ui {
    class rgaWindow: public Ui_rgaWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MV2_RGADISPLAY_H
